//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface _MBLCullOldMessagesJob : NSObject
{
    NSMutableArray *_messages;
    id _mbl;
}

- (void)dealloc;
- (id)initForMBLMailbox:(id)arg1;
- (void)run;
@property(copy, nonatomic) NSMutableArray *messages;

@end

