//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MCSMessageOperation.h"

@class NSArray;

@interface _MCSJunk : MCSMessageOperation
{
    NSArray *_operations;
}

- (_Bool)willUnflag;
- (_Bool)willFlag;
- (_Bool)willMarkUnread;
- (_Bool)willMarkRead;
- (_Bool)isRevertibleWithMessages:(id)arg1;
- (_Bool)revertOnMessages:(id)arg1 failures:(id)arg2 newMessages:(id)arg3;
- (_Bool)commitToMessages:(id)arg1 failures:(id)arg2 newMessages:(id)arg3;
- (id)applyPendingChangeToObjects:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithSpecialDestination:(int)arg1 markAsRead:(_Bool)arg2 flagsToSet:(id)arg3 flagsToClear:(id)arg4;

@end

