//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class MFSearchSuggestionsManager, NSArray, NSNumber, NSProgress, NSString;

@interface _MFSearchSuggestionsOperation : NSOperation
{
    NSNumber *_identifier;
    NSString *_phrase;
    NSArray *_suggesters;
    MFSearchSuggestionsManager *_manager;
    NSProgress *_progress;
}

+ (id)suggestionsOperationWithPhrase:(id)arg1 manager:(id)arg2 identifier:(id)arg3;
- (void)main;
- (void)cancel;
- (void)dealloc;
- (id)initWithPhrase:(id)arg1 manager:(id)arg2 identifier:(id)arg3;

@end

