//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MailStatusLabelView.h"

@class UIProgressView;

@interface MailStatusProgressBarView : MailStatusLabelView
{
    UIProgressView *_progressView;
    float _filler;
    int _countUsedUp;
    float _lastProgress;
    int _lastUsedCount;
    int _lastUsedTotal;
}

@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
- (void)update;
- (id)getStatusAndProgress:(float *)arg1;
- (void)removeFromSuperview;
- (void)dealloc;

@end

