//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MCSFinalizedObject.h"

@class NSInvocation, NSSet, NSString;

@interface MCSChange : NSObject <MCSFinalizedObject>
{
    NSInvocation *_invocation;
    unsigned long long _committedNumber;
    unsigned long long _managerNumber;
    unsigned int _isFinalized:1;
    _Bool _isReverseOperation;
}

@property(nonatomic) _Bool isReverseOperation; // @synthesize isReverseOperation=_isReverseOperation;
- (void)setInvocation:(id)arg1;
- (id)invocation;
- (_Bool)isFinalized;
- (void)setManagerNumber:(unsigned long long)arg1;
- (id)mailboxParentForMove;
- (id)mailboxToMoveOrRename;
- (id)modifiedMailboxName;
- (id)mailboxToRemove;
@property(readonly, nonatomic) NSSet *messagesSet;
- (unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2;
- (id)copyChangeSetForFullPath:(id)arg1;
- (unsigned long long)committedNumber;
- (long long)localizedChangeDescriptionPriority;
- (id)localizedChangeDescription;
- (id)localizedErrorTitle;
- (id)localizedErrorDescription;
- (id)accounts;
- (id)stores;
- (id)URLStrings;
- (_Bool)isRevertible;
- (_Bool)revert;
- (_Bool)commit;
- (id)applyPendingChangeToObjects:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

