//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "DDDetectionControllerDelegate.h"
#import "MFMailAttachmentPlugInDelegate.h"
#import "MFMailDropBannerDelegate.h"
#import "MFMessageWebLayerDelegate.h"
#import "MessageFoldDelegate.h"
#import "MessageFoldSource.h"
#import "QLPreviewControllerDataSource.h"
#import "QLPreviewControllerDelegate.h"
#import "SKStoreProductViewControllerDelegate.h"
#import "UIActivityViewControllerDelegate.h"

@class DOMRange, LoadMIMEIndicator, LoadRemoteImagesIndicator, MFMessageViewingContext, MFMessageWebLayer, MessageFoldManager, MessageHeaderLayer, MessageLoadIndicator, NSArray, NSLock, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>, NSString, NSURL, PartialMessageIndicator, QLPreviewController, SGSuggestionsService, SKStoreProductViewController;

@interface MessageContentLayer : UIView <SKStoreProductViewControllerDelegate, DDDetectionControllerDelegate, MessageFoldSource, MessageFoldDelegate, MFMessageWebLayerDelegate, MFMailAttachmentPlugInDelegate, QLPreviewControllerDataSource, QLPreviewControllerDelegate, MFMailDropBannerDelegate, UIActivityViewControllerDelegate>
{
    MessageHeaderLayer *_headerLayer;
    struct CGPoint _headerOrigin;
    NSMutableArray *_indicators;
    MessageLoadIndicator *_currentIndicator;
    PartialMessageIndicator *_partialIndicator;
    LoadMIMEIndicator *_loadMIMEIndicator;
    LoadRemoteImagesIndicator *_loadRemoteImagesIndicator;
    id _delegate;
    MFMessageWebLayer *_webLayer;
    MFMessageViewingContext *_viewingContext;
    NSMutableArray *_delayedAttachmentLoadNotifications;
    NSMutableArray *_delayedAttachmentLoadURLs;
    NSURL *_selectedAttachmentURL;
    struct CGRect _selectedAttachmentFrame;
    struct CGRect _selectedAttachmentIconFrame;
    UIView *_selectedAttachmentView;
    struct CGSize _printingPaperSize;
    _Bool _preventNextScrollIndicatorFlash;
    _Bool _messageHasBackgroundColorOrImage;
    _Bool _sourceIsManaged;
    QLPreviewController *_previewController;
    int _displayStyle;
    unsigned int _isZooming:1;
    unsigned int _mainLoadCompleted:1;
    unsigned int _isClearingMessage:1;
    unsigned int _isTweaking:1;
    unsigned int _isNotifyingDraw:1;
    unsigned int _hasDisplayedAttachmentError:1;
    SKStoreProductViewController *_storeViewController;
    double _bottomPadding;
    MessageFoldManager *_foldManager;
    _Bool _messageFoldDidUnfold;
    double _foldContentOffsetY;
    DOMRange *_bottomReplyRange;
    unsigned long long _bottomReplyLastQuoteLevel;
    _Bool _isBottomOfFoldLocationCached;
    struct CGPoint _bottomOfFoldCachedLocation;
    _Bool _displayPreparationDidEnd;
    _Bool _shouldReloadOnNetworkConfigurationChange;
    unsigned long long _numberOfReloadRetry;
    _Bool _visibleWidthChanged;
    NSObject<OS_dispatch_semaphore> *_mediaSaveSemaphore;
    SGSuggestionsService *_suggestions;
    NSObject<OS_dispatch_queue> *_suggestionsQueue;
    NSObject<OS_dispatch_queue> *_attachmentsQueue;
    NSLock *_attachmentsLock;
    NSArray *_currentAttachments;
    NSArray *_imageAttachments;
}

+ (id)_defaultLayer;
@property(retain, nonatomic) QLPreviewController *previewController; // @synthesize previewController=_previewController;
@property(nonatomic) _Bool sourceIsManaged; // @synthesize sourceIsManaged=_sourceIsManaged;
- (id)_bodyInnerHTML;
- (id)_bodyDOMHTMLElement;
- (void)messageFoldManagerDidUnfoldMessage:(id)arg1;
- (void)messageFoldManager:(id)arg1 didUpdateFoldWithProgress:(double)arg2 fadeInAlpha:(double)arg3;
- (void)messageFoldManager:(id)arg1 willFoldMessageWithContentOffset:(struct CGPoint)arg2;
- (void)_stopCachingBottomOfFoldLocation;
- (void)_startCachingBottomOfFoldLocation;
- (unsigned long long)lastQuoteLevelForMessageFoldManager:(id)arg1;
- (double)messageFoldManager:(id)arg1 topOfSubjectInView:(id)arg2;
- (double)messageFoldManager:(id)arg1 topOfOriginalTextInView:(id)arg2;
- (double)messageFoldManager:(id)arg1 bottomOfFoldInView:(id)arg2;
- (double)_topOfBottomReplyInView:(id)arg1 withOffsetBlock:(CDUnknownBlockType)arg2;
- (id)headerViewForMessageFoldManager:(id)arg1;
- (id)foldedViewForMessageFoldManager:(id)arg1;
- (struct UIEdgeInsets)originalScrollViewContentInsetForFoldManager:(id)arg1;
- (id)scrollViewForMessageFoldManager:(id)arg1;
- (void)previewController:(id)arg1 willMarkUpAtURL:(id)arg2;
- (void)quicklookMarkupAction:(id)arg1;
- (void)previewControllerWillDismiss:(id)arg1;
- (id)previewController:(id)arg1 transitionImageForPreviewItem:(id)arg2 contentRect:(struct CGRect *)arg3;
- (struct CGRect)previewController:(id)arg1 frameForPreviewItem:(id)arg2 inSourceView:(id *)arg3;
- (long long)_indexOfImageElement:(id)arg1;
- (id)_attachmentForImageElement:(id)arg1;
- (id)previewController:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewController:(id)arg1;
- (void)handleMarkupItems:(id)arg1 attachment:(id)arg2;
- (CDUnknownBlockType)_activityCompletionHandlerForAttachment:(id)arg1;
- (_Bool)webView:(id)arg1 showCustomImageSheetForElement:(id)arg2 fromLocation:(struct CGPoint)arg3;
- (struct CGRect)displayRectFromPoint:(struct CGPoint)arg1;
- (void)downloadAllMailDropAttachments;
- (id)_maildropAttachments;
- (id)messageWebLayer:(id)arg1 attachmentsWithURLs:(id)arg2;
- (void)productViewControllerDidFinish:(id)arg1;
- (_Bool)messageWebLayerShouldHaveCozyMargins:(id)arg1;
- (_Bool)messageWebLayerShouldUsePadDisplayStyle:(id)arg1;
- (void)messageWebLayer:(id)arg1 openURL:(id)arg2;
- (void)messageWebLayer:(id)arg1 didFindBottomReplyRange:(id)arg2 lastQuoteLevel:(unsigned long long)arg3;
- (struct UIEdgeInsets)basePaddingForWebLayer:(id)arg1;
- (double)canvasWidthForWebLayer:(id)arg1;
- (void)messageWebLayer:(id)arg1 didFailToPaintAttachmentURL:(id)arg2;
- (id)webView:(id)arg1 actionsForImageElement:(id)arg2 withTargetURL:(id)arg3 suggestedActions:(id)arg4;
- (id)selectedAttachmentView;
- (struct CGRect)attachmentPopoverSourceRect;
- (struct CGRect)selectedAttachmentIconFrame;
- (struct CGRect)selectedAttachmentFrame;
- (void)attachment:(id)arg1 displayMenuFromRect:(struct CGRect)arg2 iconRect:(struct CGRect)arg3 inView:(id)arg4;
- (void)attachment:(id)arg1 displayViewerFromRect:(struct CGRect)arg2 inView:(id)arg3;
- (void)_attachment:(id)arg1 sendDisplayAction:(SEL)arg2 fromRect:(struct CGRect)arg3 iconRect:(struct CGRect)arg4 inView:(id)arg5;
- (_Bool)startDownloadAndSaveToCameraRollForAttachment:(id)arg1 withDownloadProgress:(id)arg2;
- (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (_Bool)attachment:(id)arg1 cancelDownloadWithProgress:(id)arg2;
- (void)_alertMailDropDownloadIsTooLargeForCell:(_Bool)arg1;
- (_Bool)attachment:(id)arg1 startDownloadWithProgress:(id)arg2 userInitiated:(_Bool)arg3;
- (id)_pluginForAttachmentWithCID:(id)arg1;
- (id)attachment:(id)arg1 iconForSize:(struct CGSize)arg2;
- (id)attachmentWithIdentifier:(id)arg1;
- (void)_updateImageAttachmentInWebView:(id)arg1 withImage:(id)arg2;
- (void)attachmentFinishedLoadingForURL:(id)arg1 withData:(id)arg2;
- (void)_attachmentFinishedLoading:(id)arg1;
- (void)_networkConfigurationChanged:(id)arg1;
- (void)_tryViewingContextReload;
- (void)triggerAutomaticDownloadOfAttachments;
- (void)purgeDelayedAttachmentLoads;
- (void)displayAttachmentDownloadError:(id)arg1;
- (void)displayAttachmentTooLargeAlert;
- (_Bool)isAttachmentDownloadable:(id)arg1;
- (_Bool)isAttachmentTooLargeToDownload:(id)arg1;
- (void)_setupAttachmentPluginWithNotification:(id)arg1;
- (id)_existingAttachmentForContentID:(id)arg1;
- (id)_existingAttachmentForURL:(id)arg1;
- (void)_resetCachedAttachments;
@property(readonly, nonatomic) NSArray *imageAttachments;
@property(readonly, nonatomic) NSArray *attachments;
- (void)documentViewDidRotateToInterfaceOrientation:(long long)arg1;
- (void)documentViewWillFinishAnimatingRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)documentViewWillAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)documentViewWillRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)documentViewDidEndZoomingWithNewScale:(double)arg1;
- (void)documentViewDidZoom;
- (void)documentViewWillBeginZooming;
- (void)documentViewDidScroll;
- (void)documentViewDidEndDecelerating;
- (void)documentViewDidEndDraggingWillDecelerate:(_Bool)arg1;
- (_Bool)documentViewWillEndDraggingWithVelocity:(struct CGPoint)arg1 targetContentOffset:(inout struct CGPoint *)arg2;
- (void)documentViewWillBeginDragging;
- (struct CGPoint)adjustDocumentViewContentOffset:(struct CGPoint)arg1;
- (void)contentAreaOffsetChanged;
- (void)layoutSubviews;
- (void)setVisibleWidthChanged;
- (struct UIEdgeInsets)layoutMargins;
- (struct CGSize)visibleSize;
- (struct CGRect)bodyRect;
- (float)headerEnd;
- (struct CGRect)minimumBodyRect;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setNeedsLayout;
- (void)setWebViewVisibleSize:(struct CGSize)arg1 andMinimumSize:(struct CGSize)arg2;
- (void)headerHeightWillChange:(float)arg1;
- (void)headerHeightDidChange:(float)arg1 afterAnimation:(_Bool)arg2;
- (float)bottomMargin;
- (void)messageWebLayerDidDrawEntirely:(id)arg1;
- (void)messsageWebLayerDidDrawTile:(id)arg1;
- (void)messageWebLayer:(id)arg1 didDrawTileAtBounds:(struct CGRect)arg2;
- (void)messageWebLayer:(id)arg1 sizeDidChange:(struct CGSize)arg2;
- (struct CGRect)messageWebLayer:(id)arg1 newFrameForRect:(struct CGRect)arg2;
- (void)_layoutLoadIndicators;
- (id)enclosingScrollView;
- (_Bool)usePadDisplayStyle;
- (void)setFrame:(struct CGRect)arg1;
- (void)_adjustHeaderAndFooters;
- (double)_scrollerHeightOffset;
- (void)unfoldMessageIfApplicable;
- (void)refoldMessageIfApplicable;
- (_Bool)messageFoldDidUnfold;
- (_Bool)messageIsFolded;
- (id)bottomReplyRange;
- (void)displayDidEnd;
- (void)displayPreparationDidEnd;
- (void)displayPreparationWillStart;
- (void)unfreeze;
- (void)freeze;
- (_Bool)isReadyForPrinting;
- (void)preventNextScrollIndicatorFlash;
- (id)headerView;
- (id)documentView;
- (id)_attachmentForMailDropMetaData:(id)arg1;
- (void)messageWebLayer:(id)arg1 didEncounterMailDropNodes:(id)arg2 whileParsingDocument:(id)arg3;
- (void)messageWebLayerDidFinishLoading:(id)arg1;
- (void)messageWebLayerDidFirstVisuallyNonEmptyLayout:(id)arg1;
- (void)messageWebLayerDidFinishTweaking:(id)arg1;
- (void)loadMessageFragments:(id)arg1 isFromEntourage:(_Bool)arg2;
- (void)loadRequest:(id)arg1;
- (void)zoomWebView;
- (_Bool)webView:(id)arg1 shouldImmediatelyShowImageSheetForElement:(id)arg2;
- (void)setupWebLayer;
- (void)redisplayForRemoteImageToggling;
- (void)updateTextSize;
- (void)loadRemoteImages:(id)arg1;
- (void)loadBestAlternative:(id)arg1;
- (void)loadMoreOfCurrentMessage:(id)arg1;
@property(nonatomic) double bottomPadding;
- (void)setPaperSize:(struct CGSize)arg1;
- (_Bool)isCancelled;
- (void)viewingContextFinishedLoading:(id)arg1;
- (unsigned long long)_loadState;
- (id)_bestAlternativePart;
- (unsigned long long)_bytesLeft;
- (id)_libraryMessage;
- (id)ddContextForViewingContext:(id)arg1;
- (id)detectionController:(id)arg1 coreRecentsWeightForResult:(struct __DDResult *)arg2 fromScanQuery:(struct __DDScanQuery *)arg3 inContainer:(id)arg4 partOfSignature:(_Bool)arg5;
- (_Bool)isResultAtEndOfContent:(struct __DDResult *)arg1 fromScanQuery:(struct __DDScanQuery *)arg2;
- (id)coreRecentsMetadataForViewingContext:(id)arg1;
- (void)updateForRedisplay;
- (void)displayMessage:(id)arg1 withStyle:(int)arg2;
- (id)selectedAttachment;
- (id)selectedText;
- (void)clearMessage;
- (void)_clearMessageBodyOnly:(_Bool)arg1;
- (double)removeIndicator:(id)arg1;
- (double)addIndicator:(id)arg1 onTop:(_Bool)arg2;
- (double)removeAllIndicators;
- (double)_setCurrentIndicator:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

