//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MessageFoldViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class MessageFoldTopFillView, MessageFoldView, NSString, UIPinchGestureRecognizer, UIScrollView, UIView;

@interface MessageFoldManager : NSObject <MessageFoldViewDelegate, UIGestureRecognizerDelegate>
{
    id <MessageFoldSource> _source;
    id <MessageFoldDelegate> _delegate;
    UIScrollView *_scrollView;
    UIView *_foldedView;
    UIView *_headerView;
    MessageFoldView *_foldView;
    MessageFoldTopFillView *_topFillView;
    UIView *_bottomFillView;
    UIPinchGestureRecognizer *_pinchGestureRecognizer;
    struct MessageFoldPinch _lastPinch;
    _Bool _isReleasingPinch;
    double _pinchStartContentOffsetY;
    double _pinchTargetContentOffsetY;
    double _pinchStartFoldHeight;
    double _pinchEndFoldHeight;
    struct CGRect _headerFrame;
    double _bottomOfFold;
    double _foldHeight;
    double _unfoldingInitialContentOffsetY;
    double _unfoldingDistance;
    double _maxUnfoldingDistance;
    struct CGRect _coveredRect;
    int _foldState;
    int _lastAction;
    _Bool _isReleasingFlick;
    double _flickStartContentOffsetY;
    double _flickUnfoldingStartProgress;
    double _flickUnfoldingDistance;
    double _lastApparentHeaderPositionY;
    _Bool _messageIsFolded;
    _Bool _isAnimatingRotation;
    _Bool _isRotatingWithHeaderAtTop;
    _Bool _isFoldUnfolding;
    _Bool _isHeaderMovingUp;
    _Bool _isDragging;
    _Bool _isZooming;
    _Bool _isHeaderHeightChanging;
    _Bool _isFoldExtendingToTop;
}

@property(nonatomic) id <MessageFoldDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <MessageFoldSource> source; // @synthesize source=_source;
- (void)messageFoldView:(id)arg1 didUpdateFoldWithProgress:(double)arg2 fadeInAlpha:(double)arg3;
- (double)_roundY:(double)arg1;
- (double)_headerViewOriginY;
- (double)_unfoldingInitialContentOffsetY;
- (double)_apparentHeaderPositionY;
- (_Bool)_gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct MessageFoldPinch)messageFoldPinchForGestureRecognizer:(id)arg1;
- (void)_setScrollViewContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)_foldPinch:(id)arg1;
- (void)_foldTap:(id)arg1;
- (void)_prepareForAction:(int)arg1;
- (void)_rotationDidFinish;
- (void)_updateEverything;
- (void)_layoutFoldViews;
- (void)_updateMessageFold;
- (void)_updateFoldHeight;
- (void)_updateCoveredRect;
- (void)_updateMaxUnfoldingDistance;
- (void)_updateBottomOfFold;
- (void)forceFoldUpdate;
- (void)textSizeDidChange;
- (void)didEndZooming;
- (void)didZoom;
- (void)willBeginZooming;
- (void)didRotateToInterfaceOrientation:(long long)arg1;
- (void)willFinishAnimatingRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didScroll;
- (void)didEndDecelerating;
- (void)didEndDraggingWillDecelerate:(_Bool)arg1;
- (_Bool)willEndDraggingWithVelocity:(struct CGPoint)arg1 targetContentOffset:(inout struct CGPoint *)arg2;
- (void)willBeginDragging;
- (void)headerHeightDidChange;
- (void)headerHeightWillChange:(double)arg1;
- (struct CGPoint)adjustContentOffset:(struct CGPoint)arg1;
- (struct CGRect)adjustHeaderFrame:(struct CGRect)arg1;
- (_Bool)messageIsFolded;
- (void)removeMessageFold;
- (void)foldMessageIfNeccessary;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

