//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "_MFResultsGenerator.h"

@class MFAttachmentManager, MFConditionLock, MFLibraryMessage;

@interface MFMessageResultsGenerator : _MFResultsGenerator
{
    void *_addressBook;
    MFConditionLock *_contextLoadConditionLock;
    _Bool _shouldDownload;
    MFAttachmentManager *_attachmentManager;
    MFLibraryMessage *_message;
}

@property(retain, nonatomic) MFLibraryMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) MFAttachmentManager *attachmentManager; // @synthesize attachmentManager=_attachmentManager;
- (id)_headerValueForKey:(id)arg1;
- (id)_headerData:(id)arg1;
- (id)_bestAlternativePart:(id)arg1;
- (id)_rfc822Data:(id)arg1;
- (id)_attachmentValueForKey:(id)arg1;
- (CDUnknownBlockType)_testForAttachmentLimiterType:(id)arg1;
- (id)_knownAttachmentLimiterTests;
- (id)_suppressionContexts:(id)arg1;
- (id)_outgoing:(id)arg1;
- (id)_isLocalDraft:(id)arg1;
- (id)_status:(id)arg1;
- (id)_dateReceived:(id)arg1;
- (id)_dateSent:(id)arg1;
- (id)_receivingAddresses:(id)arg1;
- (id)_recipientTo:(id)arg1;
- (id)_recipientCc:(id)arg1;
- (id)_recipientBcc:(id)arg1;
- (id)_sender:(id)arg1;
- (id)_convertEmailAddresses:(id)arg1;
- (id)_convertEmailAddress:(id)arg1;
- (void *)_addressBook;
- (id)_copyPredictiveModelSummaryForMessage:(id)arg1 downloadIfNecessary:(_Bool)arg2;
- (id)_predictiveModelSummary:(id)arg1;
- (id)_bodySummary:(id)arg1;
- (id)_subject:(id)arg1;
- (id)_mailboxURL:(id)arg1;
- (id)_accountReference:(id)arg1;
- (id)_conversationReference:(id)arg1;
- (id)_localMessageReference:(id)arg1;
- (id)_messageReference:(id)arg1;
- (SEL)selectorForKey:(id)arg1;
- (void)dealloc;
- (id)initWithKeys:(id)arg1 downloadIfNecessary:(_Bool)arg2;

@end

