//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFMailMessage, MFMailboxUid, MFMessageCriterion, MFMessageInfo, MailAccount, NSArray, NSDate, NSObject<MiniMallSourceBulkOperationsDelegate>, NSSet, NSString, SourceSearchContext;

@protocol MiniMallSource <NSObject>
@property(getter=isProtectedDataAvailable) _Bool protectedDataAvailable;
- (NSString *)diagnosticDescription;
- (NSArray *)copyMessagesWithRemoteIDs:(NSSet *)arg1 options:(unsigned int)arg2;
- (long long)fetchMessagesMatchingCriterion:(MFMessageCriterion *)arg1 limit:(unsigned int)arg2;
- (NSSet *)remoteIDsUsingSearchContext:(SourceSearchContext *)arg1 limit:(unsigned long long)arg2 error:(id *)arg3;
- (MFMessageCriterion *)equivalentCriterion;
- (_Bool)canFetchSearchResults;
- (MailAccount *)accountForAutoFetch;
- (NSSet *)mailboxUids;
- (_Bool)isBaseSource;
- (NSString *)noMessagesLabelText;
- (unsigned long long)type;
- (void)reloadPreferences;
- (MFMailMessage *)messageForMessageID:(NSString *)arg1;
- (void)setLastViewedMessage:(MFMailMessage *)arg1;
- (NSDate *)lastViewedMessageDate;
- (MFMailMessage *)lastViewedMessage;
- (_Bool)shouldPlayNewMailSound;
- (_Bool)shouldShowUnreadCount;
- (_Bool)shouldIncludeWholeThreads;
- (_Bool)shouldThreadConversations;
- (void)emptyTrashAsNeeded;
- (_Bool)shouldArchiveByDefaultForMessageInfos:(id <NSFastEnumeration>)arg1;
- (_Bool)supportsArchivingForMessageInfos:(id <NSFastEnumeration>)arg1;
- (_Bool)deleteMovesToTrashForMessageInfos:(id <NSFastEnumeration>)arg1;
- (_Bool)supportsThreadOperations;
- (_Bool)shouldArchiveByDefault;
- (_Bool)supportsArchiving;
- (_Bool)deleteMovesToTrash;
- (_Bool)supportsFlagging;
- (_Bool)supportsSearch;
- (_Bool)supportsMarkAll;
- (_Bool)supportsMoveAllAcrossSources;
- (_Bool)supportsMoveAll;
- (_Bool)supportsDeleteAllAcrossSources;
- (_Bool)supportsDeleteAll;
- (NSString *)bulletinsContext;
- (NSString *)uniqueIDForStorage;
- (NSString *)uniqueIDForStatus;
- (NSString *)mailboxName;
- (CDUnknownFunctionPointerType)comparator;
- (int)correspondingType;
- (_Bool)representsMailboxID:(unsigned int)arg1;
- (_Bool)representsMailboxUid:(MFMailboxUid *)arg1;
- (_Bool)canLoadOlderMessages;
- (_Bool)shouldGrowFetchWindow;
- (_Bool)shouldCompactOnFetch;
- (_Bool)needsFetch;
- (unsigned long long)currentFetchWindow;
- (long long)fetchNumOlderMessages:(unsigned long long)arg1 preservingUID:(NSString *)arg2;
- (long long)fetchMobileSynchronously:(unsigned long long)arg1 preservingUID:(NSString *)arg2 options:(unsigned long long)arg3 error:(id *)arg4;
- (void)applyChanges;
- (struct __CFDictionary *)copySendersByLibraryIDForConversation:(long long)arg1;
- (MFMailMessage *)oldestKnownMessage;
- (long long)oldestKnownConversation;
- (MFMailMessage *)cachedMessageForMessageInfo:(MFMessageInfo *)arg1;
- (MFMailMessage *)messageForMessageInfo:(MFMessageInfo *)arg1 cacheIfNotAlready:(_Bool)arg2;
- (NSArray *)copyMessageInfosForConversationsContainingMessagesMatchingCriterion:(MFMessageCriterion *)arg1;
- (NSArray *)copyMessageInfosMatchingCriterion:(MFMessageCriterion *)arg1;
- (NSArray *)copyMessageInfos;
- (unsigned long long)onlyRemoteUnreadCount;
- (unsigned long long)remoteAndLocalUnreadCount;
- (unsigned long long)remoteMessageCount;
- (unsigned long long)allMessageCount;
- (unsigned long long)messageCount;
- (void)flushCaches;
- (void)close;
- (void)open;

@optional
- (void)moveAllMessagesWithObserver:(NSObject<MiniMallSourceBulkOperationsDelegate> *)arg1 toMailbox:(MFMailboxUid *)arg2;
- (void)markAllMessagesAsDeletedOrArchived:(unsigned long long)arg1 withObserver:(NSObject<MiniMallSourceBulkOperationsDelegate> *)arg2;
- (void)markAllMessagesAsViewed;
- (void)markAllMessagesAsNotViewed;
- (void)markAllMessagesAsFlagged;
- (void)markAllMessagesAsNotFlagged;
@end

