//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SourceSearchContext.h"

@class MFMessageCriterion, NSArray, NSString;

@interface MutableSourceSearchContext : SourceSearchContext
{
}


// Remaining properties
@property(retain, nonatomic) MFMessageCriterion *criterion; // @dynamic criterion;
@property(copy, nonatomic) NSArray *searchTerms; // @dynamic searchTerms;
@property(copy, nonatomic) NSString *searchText; // @dynamic searchText;
@property(nonatomic) _Bool shouldSearchAllMail; // @dynamic shouldSearchAllMail;
@end

