//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StackController, UIView;

@protocol StackDelegate <NSObject>

@optional
- (void)stackController:(StackController *)arg1 willRemoveViewForItem:(id)arg2;
- (void)stackController:(StackController *)arg1 willDisplayView:(UIView *)arg2 forItem:(id)arg3;
- (void)stackController:(StackController *)arg1 willStackView:(UIView *)arg2 forItem:(id)arg3;
- (void)stackController:(StackController *)arg1 dataLoadTimedOutInView:(UIView *)arg2 forItem:(id)arg3;
- (void)stackControllerDidStopAnimatingViews:(StackController *)arg1;
- (void)stackControllerWillStartAnimatingViews:(StackController *)arg1;
- (void)stackControllerDidStopStackingViews:(StackController *)arg1;
- (void)stackControllerWillStartStackingViews:(StackController *)arg1;
@end

