//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICAudioAttachmentView.h"

@interface ICAudioAttachmentView (ICAccessibility_iOS)
- (id)_icaxSpeechTextForSubtitle;
- (_Bool)icaxActivate;
- (id)accessibilityCustomActions;
- (id)accessibilityHint;
- (id)accessibilityValue;
- (id)accessibilityLabel;
@end

