//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ICSearchIndexable.h"

@class NSArray, NSDate, NSString;

@protocol ICSearchIndexableNote <ICSearchIndexable>
- (NSDate *)dateForCurrentSortType;
- (NSString *)contentInfoText;
- (NSString *)noteAsPlainTextWithoutTitle;
- (NSString *)title;
- (_Bool)isPasswordProtected;
- (NSArray *)searchableContentKeyPaths;
@end

