//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _YKBCBlockHolder : NSObject
{
    _Bool _limit;
    CDUnknownBlockType _sucess;
    CDUnknownBlockType _fail;
    CDUnknownBlockType _commonSucess;
    CDUnknownBlockType _commonFail;
}

@property _Bool limit; // @synthesize limit=_limit;
@property(copy, nonatomic) CDUnknownBlockType commonFail; // @synthesize commonFail=_commonFail;
@property(copy, nonatomic) CDUnknownBlockType commonSucess; // @synthesize commonSucess=_commonSucess;
@property(copy, nonatomic) CDUnknownBlockType fail; // @synthesize fail=_fail;
@property(copy, nonatomic) CDUnknownBlockType sucess; // @synthesize sucess=_sucess;
- (void).cxx_destruct;

@end

