//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSDictionary;

@interface AEHttpRequestUserInfo : NSObject <NSCopying>
{
    NSDictionary *_infoAppendingAfterQueryString;
    NSDictionary *_infoInHttpHeader;
}

+ (id)infoWithAppending:(id)arg1 andHeader:(id)arg2;
@property(retain, nonatomic) NSDictionary *infoInHttpHeader; // @synthesize infoInHttpHeader=_infoInHttpHeader;
@property(retain, nonatomic) NSDictionary *infoAppendingAfterQueryString; // @synthesize infoAppendingAfterQueryString=_infoAppendingAfterQueryString;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

