//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AILPLMicInfo, NSDictionary, NSString;

@interface AILPLPlayeInfo : NSObject
{
    NSString *_liveId;
    long long _liveState;
    AILPLMicInfo *_micInfo;
    NSDictionary *_dataDic;
    NSString *_dataContent;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *dataContent; // @synthesize dataContent=_dataContent;
@property(copy, nonatomic) NSDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(copy, nonatomic) AILPLMicInfo *micInfo; // @synthesize micInfo=_micInfo;
@property(nonatomic) long long liveState; // @synthesize liveState=_liveState;
@property(copy, nonatomic) NSString *liveId; // @synthesize liveId=_liveId;
- (void).cxx_destruct;
- (void)makeDataDictionary;

@end

