//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AIACMsg.h"

@class NSMutableArray, NSMutableDictionary;

@interface AILPMsg : AIACMsg
{
    NSMutableArray *_messageArray;
    NSMutableDictionary *_originalDictionary;
}

@property(retain, nonatomic) NSMutableDictionary *originalDictionary; // @synthesize originalDictionary=_originalDictionary;
@property(retain, nonatomic) NSMutableArray *messageArray; // @synthesize messageArray=_messageArray;
- (void).cxx_destruct;
- (void)fromPMMessage:(id)arg1;
- (id)setupMessageDictionary:(id)arg1 originDic:(id)arg2;
- (void)toPMMessage:(id)arg1;
- (id)toDictionary;

@end

