//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface AILPSessionServiceManager : NSObject
{
    NSMutableDictionary *_services;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)serviceWithURL:(id)arg1;
- (void)addService:(id)arg1;
- (id)services;
- (id)fetcherWithURL:(id)arg1;
- (id)init;

@end

