//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AILPLogging : NSObject
{
    unsigned long long _level;
    id <AILPLoggingProtocol> _adapter;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <AILPLoggingProtocol> adapter; // @synthesize adapter=_adapter;
@property(nonatomic) unsigned long long level; // @synthesize level=_level;
- (void).cxx_destruct;
- (void)error:(id)arg1 func:(const char *)arg2 format:(id)arg3;
- (void)error:(id)arg1;
- (void)warn:(id)arg1 func:(const char *)arg2 format:(id)arg3;
- (void)warn:(id)arg1;
- (void)info:(id)arg1 func:(const char *)arg2 format:(id)arg3;
- (void)info:(id)arg1;
- (void)debug:(id)arg1 func:(const char *)arg2 format:(id)arg3;
- (void)debug:(id)arg1;

@end

