//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AILPChatConnection.h"

#import "AIACMsgListenerProtocol.h"

@class AIACMsgHandler, AIASLiveSession, AILPChatRoomConfigExt, NSObject<OS_dispatch_queue>, NSString;

@interface AILPPMChatConnection : AILPChatConnection <AIACMsgListenerProtocol>
{
    id _protocol;
    AILPChatRoomConfigExt *_ext;
    AIACMsgHandler *_msgHandler;
    AIASLiveSession *_session;
    NSObject<OS_dispatch_queue> *_messageQueue;
}

+ (void)asyncInitAIASContainer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(retain, nonatomic) AIASLiveSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AIACMsgHandler *msgHandler; // @synthesize msgHandler=_msgHandler;
@property(retain, nonatomic) AILPChatRoomConfigExt *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) id protocol; // @synthesize protocol=_protocol;
- (void).cxx_destruct;
- (void)msgArrive:(id)arg1;
- (void)pmsgConnect:(id)arg1;
- (long long)state;
- (void)disConnect;
- (void)connect;
- (void)sendMessage:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;
- (void)setProtocol:(id)arg1 ext:(id)arg2;
- (id)initWithProtocol:(id)arg1 ext:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

