//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@protocol ALBBUserTrackProtocol <NSObject>
+ (id <ALBBUserTrackProtocol>)instance;
- (void)addTraceLog:(NSString *)arg1 propertys:(NSDictionary *)arg2;
- (void)addTraceLog:(NSString *)arg1;
@end

