//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MtopAuthProtocol.h"

@class ALiAuthViewController, NSString;

@interface ALiAuthService : NSObject <MtopAuthProtocol>
{
    ALiAuthViewController *_authBiz;
    id <ALiHintProtocol> _hintSvr;
}

+ (id)sharedInstantce;
@property(nonatomic) __weak id <ALiHintProtocol> hintSvr; // @synthesize hintSvr=_hintSvr;
@property(retain, nonatomic) ALiAuthViewController *authBiz; // @synthesize authBiz=_authBiz;
- (void).cxx_destruct;
- (id)getBizId:(id)arg1;
- (id)getApiHint:(id)arg1;
- (id)getHintList:(id)arg1 apiHint:(id)arg2;
- (void)installHintService:(id)arg1;
- (void)markInvalidAuth;
- (_Bool)isProcessingAuth;
- (id)currentSession;
- (void)authWithAuthOption:(int)arg1 extraInfo:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 cancelationHandler:(CDUnknownBlockType)arg4;
- (void)authWithAuthOption:(int)arg1 completionHandler:(CDUnknownBlockType)arg2 cancelationHandler:(CDUnknownBlockType)arg3;
- (_Bool)isValidAuth;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

