//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioPlayerDelegate.h"

@class AVAudioPlayer, NSString, NSTimer, NSURL;

@interface AliAVAudioPlayer : NSObject <AVAudioPlayerDelegate>
{
    _Bool _isPauseByUser;
    _Bool _isPrepared;
    id <AliAVAudioPlayerDelegate> _delegate;
    long long _numberOfLoops;
    double _currentPlayTime;
    NSURL *_url;
    CDUnknownBlockType _playCompleteBlock;
    CDUnknownBlockType _playErrorBlock;
    AVAudioPlayer *_player;
    NSTimer *_playTimer;
    double _startPlayTime;
    double _totalPlayTime;
}

@property(nonatomic) double totalPlayTime; // @synthesize totalPlayTime=_totalPlayTime;
@property(nonatomic) double startPlayTime; // @synthesize startPlayTime=_startPlayTime;
@property(retain, nonatomic) NSTimer *playTimer; // @synthesize playTimer=_playTimer;
@property(nonatomic) _Bool isPrepared; // @synthesize isPrepared=_isPrepared;
@property(nonatomic) _Bool isPauseByUser; // @synthesize isPauseByUser=_isPauseByUser;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player=_player;
@property(copy, nonatomic) CDUnknownBlockType playErrorBlock; // @synthesize playErrorBlock=_playErrorBlock;
@property(copy, nonatomic) CDUnknownBlockType playCompleteBlock; // @synthesize playCompleteBlock=_playCompleteBlock;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) double currentPlayTime; // @synthesize currentPlayTime=_currentPlayTime;
@property(nonatomic) long long numberOfLoops; // @synthesize numberOfLoops=_numberOfLoops;
@property(nonatomic) __weak id <AliAVAudioPlayerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(nonatomic) double volume;
@property(nonatomic) double rate;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) _Bool isPlaying;
@property(nonatomic) _Bool mute;
@property(nonatomic) double currentTime;
- (void)seek:(double)arg1;
- (void)audioRouteChangeListenerCallback:(id)arg1;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)stop;
- (void)pause;
- (_Bool)play;
- (_Bool)prepareToPlay;
- (void)reset;
- (void)startTimer;
- (void)stopTimer;
- (void)dealloc;
- (id)initWithUrl:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

