//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AliBElementSnapshot, NSString;

@interface AliBBaseElement : NSObject
{
    NSString *_name;
    AliBElementSnapshot *_snapBegin;
    AliBElementSnapshot *_snapEnd;
}

@property(retain, nonatomic) AliBElementSnapshot *snapEnd; // @synthesize snapEnd=_snapEnd;
@property(retain, nonatomic) AliBElementSnapshot *snapBegin; // @synthesize snapBegin=_snapBegin;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)setEndContainer:(id)arg1;
- (void)setBeginContainer:(id)arg1;
- (id)initWithElement:(id)arg1;

@end

