//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AliBatonUtils : NSObject
{
}

+ (_Bool)isInBlackWithVersions:(id)arg1;
+ (_Bool)isInBlackWithDevices:(id)arg1;
+ (id)deviceModelStr;
+ (struct CATransform3D)transform3DMakePerspective:(struct CGPoint)arg1 disZ:(float)arg2;
+ (_Bool)bundleLoadDynamicLibWithPath:(id)arg1;
+ (_Bool)loadDylibFramework:(id)arg1;
+ (id)getAnimationUniqueName:(id)arg1;
+ (id)JSONStrToDictionary:(id)arg1;

@end

