//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AliBDownloadServer : NSObject
{
}

+ (void)downLoadFileWithUrl:(id)arg1 md5:(id)arg2 destination:(id)arg3 progressHandler:(CDUnknownBlockType)arg4 result:(CDUnknownBlockType)arg5;
+ (void)downLoadFileWithUrl:(id)arg1 md5:(id)arg2 destination:(id)arg3 result:(CDUnknownBlockType)arg4;
+ (void)downLoadWithUrl:(id)arg1 destination:(id)arg2 md5:(id)arg3 bizCode:(id)arg4 progressHandler:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;

@end

