//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AliFilterTool : NSObject
{
    float _saturation;
    float _contrast;
    float _light;
}

+ (id)filter;
@property(nonatomic) float light; // @synthesize light=_light;
@property(nonatomic) float contrast; // @synthesize contrast=_contrast;
@property(nonatomic) float saturation; // @synthesize saturation=_saturation;
- (id)renderCIImage:(id)arg1;

@end

