//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALiNetServiceBase.h"

@interface ALiNetServiceMtop : ALiNetServiceBase
{
}

+ (id)sharedInstance;
- (_Bool)shouldRetry:(id)arg1;
- (id)proccessMtopError:(id)arg1;
- (_Bool)performSend:(id)arg1;
- (id)init;

@end

