//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AliVideoItem, NSURL, UIImage, UIView;

@protocol AliPlayerCore <NSObject>
- (void)setAutoRunloop:(_Bool)arg1;
- (void)setAutoPauseInBackground:(_Bool)arg1;
- (void)setScalingAspectFill:(_Bool)arg1;
- (void)setDelegate:(id <AliPlayerDelegate>)arg1;
- (void)setMuted:(_Bool)arg1;
- (UIImage *)shotImage;
- (UIView *)renderView;
- (_Bool)isSeeking;
- (_Bool)isPlaying;
- (void)stop;
- (void)resume;
- (void)pause;
- (void)prepareToPlay;

@optional
+ (id)playerWithVideoItem:(AliVideoItem *)arg1;
+ (id)playerWithPlayerUrl:(NSURL *)arg1 isLive:(_Bool)arg2;
+ (id)playerWithPlayerUrl:(NSURL *)arg1;
- (float)volume;
- (void)setVolume:(float)arg1;
- (long long)avgKeyFrameSize;
- (long long)avgvideoBitRate;
- (double)videoFrameRate;
- (double)playBackTime;
- (double)playableDuration;
- (double)duration;
- (NSURL *)playerUrl;
- (void)setCallBackPlayTimeInterval:(double)arg1;
- (void)seek:(double)arg1;
- (id)initWithVideoItem:(AliVideoItem *)arg1;
- (id)initWithPlayerUrl:(NSURL *)arg1 isLive:(_Bool)arg2 isHardwareDecoder:(_Bool)arg3;
- (id)initWithPlayerUrl:(NSURL *)arg1 isLive:(_Bool)arg2;
- (id)initWithPlayerUrl:(NSURL *)arg1;
@end

