//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class AliRecordSession, NSArray, NSString, UICollectionView, UILabel, UIView;

@interface AliRecordFilterViewController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _exitForClickOutside;
    id <AliRecordFilterViewControllerDelegate> _delegate;
    NSString *_currentFilterName;
    NSArray *_dataEntity;
    long long _selectedIndex;
    UIView *_headerView;
    UICollectionView *_collectionView;
    AliRecordSession *_session;
    UILabel *_mLabel;
}

@property(retain, nonatomic) UILabel *mLabel; // @synthesize mLabel=_mLabel;
@property(retain, nonatomic) AliRecordSession *session; // @synthesize session=_session;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool exitForClickOutside; // @synthesize exitForClickOutside=_exitForClickOutside;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) NSArray *dataEntity; // @synthesize dataEntity=_dataEntity;
@property(copy, nonatomic) NSString *currentFilterName; // @synthesize currentFilterName=_currentFilterName;
@property(nonatomic) __weak id <AliRecordFilterViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)changeFitler:(unsigned long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)firstSelectFilter;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)selectFilter;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

