//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AliRecordBaseViewController.h"

#import "AliPlayerDelegate.h"

@class AliAVPlayerCore, AliCircleProgressView, AliSVDraftsProjectInfoModel, AliVideoAlbumItem, AliVideoSnapShootBar, NSArray, NSString, UIButton, UILabel;

@interface AliVideoImportViewController : AliRecordBaseViewController <AliPlayerDelegate>
{
    AliAVPlayerCore *_player;
    AliVideoSnapShootBar *_snapShootBar;
    AliVideoAlbumItem *_videoAlbumItem;
    NSArray *_imgArray;
    UIButton *_cancelBtn;
    UIButton *_okBtn;
    UILabel *_timeLabel;
    UIButton *_rotateBtn;
    double _startPlayTime;
    double _endPlayTime;
    double _videoMaxTime;
    double _normalTimeOneImg;
    double _degree;
    AliCircleProgressView *_circleProgress;
    AliSVDraftsProjectInfoModel *_projectInfo;
    double _maxRecordDuration;
}

@property(nonatomic) double maxRecordDuration; // @synthesize maxRecordDuration=_maxRecordDuration;
@property(retain, nonatomic) AliSVDraftsProjectInfoModel *projectInfo; // @synthesize projectInfo=_projectInfo;
@property(retain, nonatomic) AliCircleProgressView *circleProgress; // @synthesize circleProgress=_circleProgress;
@property(nonatomic) double degree; // @synthesize degree=_degree;
@property(nonatomic) double normalTimeOneImg; // @synthesize normalTimeOneImg=_normalTimeOneImg;
@property(nonatomic) double videoMaxTime; // @synthesize videoMaxTime=_videoMaxTime;
@property(nonatomic) double endPlayTime; // @synthesize endPlayTime=_endPlayTime;
@property(nonatomic) double startPlayTime; // @synthesize startPlayTime=_startPlayTime;
@property(retain, nonatomic) UIButton *rotateBtn; // @synthesize rotateBtn=_rotateBtn;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIButton *okBtn; // @synthesize okBtn=_okBtn;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) NSArray *imgArray; // @synthesize imgArray=_imgArray;
@property(retain, nonatomic) AliVideoAlbumItem *videoAlbumItem; // @synthesize videoAlbumItem=_videoAlbumItem;
@property(retain, nonatomic) AliVideoSnapShootBar *snapShootBar; // @synthesize snapShootBar=_snapShootBar;
@property(retain, nonatomic) AliAVPlayerCore *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)rotate;
- (void)updateProgress:(double)arg1;
- (void)exportVideoWithCompletion:(CDUnknownBlockType)arg1;
- (id)getFirstRenderImgPathWithVideoPath:(id)arg1;
- (void)gotoPreViewControllerWithVideo:(id)arg1 Audio:(id)arg2 music:(id)arg3;
- (void)ok;
- (void)okAction;
- (void)cancel;
- (id)getImageWithTime:(double)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)updateTimeLabel:(double)arg1;
- (struct CGRect)renderViewDefaultFrame;
- (void)playerNotify:(unsigned long long)arg1;
- (void)playBackTime:(double)arg1;
- (void)setUpBar;
- (void)start;
- (id)dataForUserTrack;
- (void)viewDidLoad;
- (void)dealloc;
- (void)setupInitData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

