//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSString;

@protocol ALMCollectionItemProtocol <NSObject>
@property(retain, nonatomic) NSIndexPath *indexPath;

@optional
@property(retain, nonatomic) NSString *itemIdentifier;
@property(nonatomic) _Bool canMove;
@property(nonatomic) struct CGSize itemSize;
@end

