//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITableView;

@interface ALMTableViewUpdateHelper : NSObject
{
    UITableView *_tableView;
}

+ (id)bindUpdateSignal:(id)arg1 toTableView:(id)arg2;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)updateTableRowWithUpdateInfo:(id)arg1;
- (void)updateTableSectionWithUpdateInfo:(id)arg1;
- (void)updateTableViewWithUpdateInfos:(id)arg1;
- (id)initWithSignal:(id)arg1 tableView:(id)arg2;

@end

