//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, NSString, UIImage;

@protocol ALMTableRowProtocol <NSObject>
@property(nonatomic) long long rowHeight;
@property(nonatomic) long long cellStyle;
@property(retain, nonatomic) NSIndexPath *indexPath;

@optional
@property(retain, nonatomic) NSString *cellIdentifier;
@property(nonatomic) _Bool canMove;
@property(copy, nonatomic) NSString *detailLabelText;
@property(retain, nonatomic) UIImage *image;
@property(copy, nonatomic) NSString *title;
@end

