//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AMBaseProcessor, AMBeautifyProcessor, AMFilterSetting, AMFrameData, AMGPUImageColorFilter, AMGPUImageEmptyFilter, AMGPUImageFilterProcessor, AMGPUImageMixFilter, AMPlayMethodConfigModel, AMPlayMethodProcessor, AMStickerItem, AMStickerProcessor, GPUImageView, UIView;

@interface AMProcessingEngine : NSObject
{
    _Bool _dataMirrored;
    _Bool _enable;
    _Bool _paused;
    int _state;
    id <AMProcessingEngineDelegate> _delegate;
    long long _cameraPosition;
    AMFilterSetting *_filter;
    AMFilterSetting *_filterMix;
    double _mixRatio;
    AMPlayMethodConfigModel *_playMethod;
    GPUImageView *_gpuImageView;
    unsigned long long _detectType;
    AMBaseProcessor *_humanDetector;
    AMBeautifyProcessor *_beautifyProcessor;
    AMStickerProcessor *_stickerProcessor;
    AMPlayMethodProcessor *_playMethodProcessor;
    AMGPUImageColorFilter *_colorFilter;
    AMGPUImageColorFilter *_colorFilter2;
    AMGPUImageMixFilter *_mixFilter;
    AMGPUImageEmptyFilter *_outputFilter;
    AMGPUImageFilterProcessor *_colorFilterProcessor;
    AMGPUImageFilterProcessor *_colorFilter2Processor;
    AMGPUImageFilterProcessor *_mixFilterProcessor;
    AMGPUImageFilterProcessor *_outputFilterProcessor;
    AMFrameData *_frameData;
}

+ (id)getFilters;
+ (void)getStickerItemsByTipId:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)getStickerItemsByGroup:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)getStickerGroups:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) AMFrameData *frameData; // @synthesize frameData=_frameData;
@property(retain, nonatomic) AMGPUImageFilterProcessor *outputFilterProcessor; // @synthesize outputFilterProcessor=_outputFilterProcessor;
@property(retain, nonatomic) AMGPUImageFilterProcessor *mixFilterProcessor; // @synthesize mixFilterProcessor=_mixFilterProcessor;
@property(retain, nonatomic) AMGPUImageFilterProcessor *colorFilter2Processor; // @synthesize colorFilter2Processor=_colorFilter2Processor;
@property(retain, nonatomic) AMGPUImageFilterProcessor *colorFilterProcessor; // @synthesize colorFilterProcessor=_colorFilterProcessor;
@property(retain, nonatomic) AMGPUImageEmptyFilter *outputFilter; // @synthesize outputFilter=_outputFilter;
@property(retain, nonatomic) AMGPUImageMixFilter *mixFilter; // @synthesize mixFilter=_mixFilter;
@property(retain, nonatomic) AMGPUImageColorFilter *colorFilter2; // @synthesize colorFilter2=_colorFilter2;
@property(retain, nonatomic) AMGPUImageColorFilter *colorFilter; // @synthesize colorFilter=_colorFilter;
@property(retain, nonatomic) AMPlayMethodProcessor *playMethodProcessor; // @synthesize playMethodProcessor=_playMethodProcessor;
@property(retain, nonatomic) AMStickerProcessor *stickerProcessor; // @synthesize stickerProcessor=_stickerProcessor;
@property(retain, nonatomic) AMBeautifyProcessor *beautifyProcessor; // @synthesize beautifyProcessor=_beautifyProcessor;
@property(retain, nonatomic) AMBaseProcessor *humanDetector; // @synthesize humanDetector=_humanDetector;
@property(nonatomic) unsigned long long detectType; // @synthesize detectType=_detectType;
@property(nonatomic) _Bool paused; // @synthesize paused=_paused;
@property(retain, nonatomic) GPUImageView *gpuImageView; // @synthesize gpuImageView=_gpuImageView;
@property(retain, nonatomic) AMPlayMethodConfigModel *playMethod; // @synthesize playMethod=_playMethod;
@property(nonatomic) double mixRatio; // @synthesize mixRatio=_mixRatio;
@property(retain, nonatomic) AMFilterSetting *filterMix; // @synthesize filterMix=_filterMix;
@property(retain, nonatomic) AMFilterSetting *filter; // @synthesize filter=_filter;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(nonatomic) long long cameraPosition; // @synthesize cameraPosition=_cameraPosition;
@property(nonatomic) _Bool dataMirrored; // @synthesize dataMirrored=_dataMirrored;
@property(nonatomic) __weak id <AMProcessingEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)enablePlayMethod:(_Bool)arg1;
- (void)restartCurrentPlayMethod;
@property(retain, nonatomic) AMStickerItem *sticker;
- (double)beautifyValueForParam:(int)arg1;
- (void)setBeautifyValue:(double)arg1 forParam:(int)arg2;
@property(readonly, nonatomic) UIView *renderView;
- (void)ResumeEngine;
- (void)PauseEngine;
- (void)SetInputFrameByCVPixelBuffer:(struct __CVBuffer *)arg1 time:(CDStruct_1b6d18a9)arg2;
- (void)registerSTProcessor;
- (void)registerProcessor:(int)arg1 withClassName:(id)arg2 selector:(SEL)arg3;
- (void)registerProcessor:(int)arg1 withObj:(id)arg2;
- (void)setupHandle;
- (void)prepare;

@end

