//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APBCPostContentViewModelProtocol.h"

@class APBCPostCardModel, NSArray, NSAttributedString, NSString;

@protocol APBCFooterViewModelProtocol <APBCPostContentViewModelProtocol>
@property(nonatomic) struct CGSize fromFandomNameSize;
@property(retain, nonatomic) NSAttributedString *fromFandomName;
- (_Bool)isPostByArtist;
- (NSString *)displayTimeString;
- (NSString *)posterName;
- (NSString *)avatarUrl;
- (_Bool)isPraised;
- (long long)fandomId;
- (void)goToFromFandomPage;
- (NSString *)displayCommentCountString;
- (NSString *)displayPraiseCountString;

@optional
- (void)excuteExtensionInfoClickedAction;
- (NSAttributedString *)extensionInfoString;
- (void)clickedActionWithRelativeInfo:(NSString *)arg1;
- (NSArray *)relativeInfos;
- (NSString *)dramaInfoURL;
- (NSString *)dramaInfoImage;
- (NSAttributedString *)dramaInfoTitle;
- (void)routeToPersonalHomepage;
- (_Bool)hideBottomLine;
- (Class)footerViewClass;
- (long long)praiseType;
- (long long)praiseCount;
- (APBCPostCardModel *)cardModel;
- (long long)bizId;
@end

