//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APBCBasePostCardView.h"

@class YKFBlockCellAdapter, YKFPlanetBlocksCellPlugin, YKFVoteBlocksCell, YKFVotePreviewBlocksCell;

@interface APBCVotePostCardView : APBCBasePostCardView
{
    YKFPlanetBlocksCellPlugin *_blockCellPlugin;
    YKFVoteBlocksCell *_voteBlockCell;
    YKFBlockCellAdapter *_blockCellAdapter;
    YKFVotePreviewBlocksCell *_votePreviewBlockCell;
}

+ (double)calculateContentHeightWithViewModel:(id)arg1 maxWidth:(double)arg2;
+ (double)heightWithViewModel:(id)arg1 maxWidth:(double)arg2;
@property(retain, nonatomic) YKFVotePreviewBlocksCell *votePreviewBlockCell; // @synthesize votePreviewBlockCell=_votePreviewBlockCell;
@property(retain, nonatomic) YKFBlockCellAdapter *blockCellAdapter; // @synthesize blockCellAdapter=_blockCellAdapter;
@property(retain, nonatomic) YKFVoteBlocksCell *voteBlockCell; // @synthesize voteBlockCell=_voteBlockCell;
@property(retain, nonatomic) YKFPlanetBlocksCellPlugin *blockCellPlugin; // @synthesize blockCellPlugin=_blockCellPlugin;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)trackUserDataWhenSelected;
- (void)trackUserDataWhenDisplay;
- (void)updateCardViewWithViewModel:(id)arg1 width:(double)arg2;

@end

