//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ALMBaseViewModel.h"

@class NSAttributedString;

@interface APPPostTextViewModel : ALMBaseViewModel
{
    long long _index;
    NSAttributedString *_contentString;
}

@property(copy, nonatomic) NSAttributedString *contentString; // @synthesize contentString=_contentString;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (_Bool)needSeparator;
- (id)initWithContent:(id)arg1 tags:(id)arg2 associatedTopic:(id)arg3 contentTopics:(id)arg4;

@end

