//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ASAbstractLayoutController.h"

@class ASCollectionView, UICollectionViewLayout;

@interface ASCollectionViewLayoutController : ASAbstractLayoutController
{
    ASCollectionView *_collectionView;
    UICollectionViewLayout *_collectionViewLayout;
}

- (void).cxx_destruct;
- (struct CGRect)rangeBoundsWithScrollDirection:(long long)arg1 rangeTuningParameters:(CDStruct_8caa76fc)arg2;
- (id)elementsWithinRangeBounds:(struct CGRect)arg1 map:(id)arg2;
- (void)allElementsForScrolling:(long long)arg1 rangeMode:(long long)arg2 displaySet:(id *)arg3 preloadSet:(id *)arg4 map:(id)arg5;
- (id)elementsForScrolling:(long long)arg1 rangeMode:(long long)arg2 rangeType:(long long)arg3 map:(id)arg4;
- (id)initWithCollectionView:(id)arg1;

@end

