//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ASKDrawerScheduleSubItem : NSObject
{
    NSString *_title;
    NSString *_scheme;
    NSString *_imageUrlString;
}

@property(copy, nonatomic) NSString *imageUrlString; // @synthesize imageUrlString=_imageUrlString;
@property(copy, nonatomic) NSString *scheme; // @synthesize scheme=_scheme;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)segueModel;
- (id)init;

@end

