//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AUIBannerScrollView;

@protocol AUIBannerScrollViewDelegate <NSObject>

@optional
- (void)auiBannerScrollView:(AUIBannerScrollView *)arg1 didClickedAtIndex:(unsigned long long)arg2;
- (void)auiBannerScrollView:(AUIBannerScrollView *)arg1 didScrolledToIndex:(unsigned long long)arg2;
@end

