//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString;

@interface ChannelNavItem : NSObject <NSCoding>
{
    _Bool _hasCollection;
    _Bool _showFilter;
    NSString *_color;
    long long _tid;
    NSString *_title;
}

+ (id)parseChannelNavItem:(id)arg1;
@property(nonatomic) _Bool showFilter; // @synthesize showFilter=_showFilter;
@property(nonatomic) _Bool hasCollection; // @synthesize hasCollection=_hasCollection;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long tid; // @synthesize tid=_tid;
@property(retain, nonatomic) NSString *color; // @synthesize color=_color;
- (void).cxx_destruct;
- (id)bridgeToGroupItem;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

