//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface ChildHistoryComponentModel : NSObject
{
    _Bool _isLocal;
    NSString *_title;
    NSArray *_modelArray;
}

@property(nonatomic) _Bool isLocal; // @synthesize isLocal=_isLocal;
@property(retain, nonatomic) NSArray *modelArray; // @synthesize modelArray=_modelArray;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (_Bool)isValid;
- (void)initWithLocalHistory:(id)arg1;
- (void)initWithCmsData:(id)arg1;

@end

