//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChildOPPlugin.h"

@class UIButton, UIView;

@interface ChildDialogPlugin : ChildOPPlugin
{
    UIButton *_backgroundBtn;
    UIView *_contentView;
}

@property(nonatomic) __weak UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIButton *backgroundBtn; // @synthesize backgroundBtn=_backgroundBtn;
- (void).cxx_destruct;
- (void)onVideoSizeChanged;
- (void)onBackgroundBtnClick:(id)arg1;
- (void)dismiss;
- (void)show:(id)arg1;
- (void)onDeInit;
- (void)onReceived:(id)arg1;
- (void)onRun;
- (void)onInit;

@end

