//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ChildDownloadFlag : NSObject
{
    _Bool _downloadable;
    _Bool _passwordDownloadFlag;
    _Bool _privateDownloadFlag;
    _Bool _subScribeDownloadFlag;
    _Bool _isMemberDownloadableOnly;
    _Bool _vipMark;
    _Bool _hasNextPage;
    NSString *_vid;
    NSString *_title;
    NSString *_desc;
}

+ (id)instanceWithVideoId:(id)arg1 title:(id)arg2;
+ (id)modelWithJSONDictionary:(id)arg1;
@property(nonatomic) _Bool hasNextPage; // @synthesize hasNextPage=_hasNextPage;
@property(nonatomic) _Bool vipMark; // @synthesize vipMark=_vipMark;
@property(nonatomic) _Bool isMemberDownloadableOnly; // @synthesize isMemberDownloadableOnly=_isMemberDownloadableOnly;
@property(nonatomic) _Bool subScribeDownloadFlag; // @synthesize subScribeDownloadFlag=_subScribeDownloadFlag;
@property(nonatomic) _Bool privateDownloadFlag; // @synthesize privateDownloadFlag=_privateDownloadFlag;
@property(nonatomic) _Bool passwordDownloadFlag; // @synthesize passwordDownloadFlag=_passwordDownloadFlag;
@property(nonatomic) _Bool downloadable; // @synthesize downloadable=_downloadable;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
- (void).cxx_destruct;
- (id)initWithJSONDictionrary:(id)arg1;

@end

