//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class ChildBaseCardView;

@interface ChildBaseCardViewController : UIViewController
{
    ChildBaseCardView *_cardView;
    id _data;
}

@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(retain, nonatomic) ChildBaseCardView *cardView; // @synthesize cardView=_cardView;
- (void).cxx_destruct;
- (id)getMarkItem;
- (id)getCardShowId;
- (struct CGSize)childBaseCardView:(id)arg1 sizeForMarkView:(id)arg2;
- (id)childBaseCardView:(id)arg1 contentForMarkView:(id)arg2;
- (id)createMarkViewWithData:(id)arg1;
- (void)updateData:(id)arg1;
- (void)viewDidLoad;
- (id)init;

@end

