//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ChildBaseAppInfoProtocol.h"

@class NSString;

@interface ChildBaseAppImpl : NSObject <ChildBaseAppInfoProtocol>
{
}

- (_Bool)audioVideoPlayEnable;
- (id)getServerTime;
- (void)saveBabyInfo:(id)arg1 success:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (id)getBabyInfo;
- (id)getSystemInfo;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

