//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, UIVisualEffectView;

@interface ChildVideoToast : UIView
{
    UIVisualEffectView *_blurView;
    UIVisualEffectView *_vibrancyView;
    UILabel *_titleLabel;
    long long _style;
    double _position;
}

+ (id)keyWindow;
+ (void)hide;
+ (void)showMessage:(id)arg1 style:(long long)arg2 position:(double)arg3 duration:(double)arg4;
+ (void)showMessage:(id)arg1 style:(long long)arg2 duration:(double)arg3;
+ (void)showMessage:(id)arg1 style:(long long)arg2;
+ (void)showMessage:(id)arg1 style:(long long)arg2 position:(double)arg3;
+ (void)showMessage:(id)arg1;
@property(nonatomic) double position; // @synthesize position=_position;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIVisualEffectView *vibrancyView; // @synthesize vibrancyView=_vibrancyView;
@property(retain, nonatomic) UIVisualEffectView *blurView; // @synthesize blurView=_blurView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)labelTop;
- (double)labelLeft;
- (void)sizeToFit;
- (void)showMessage:(id)arg1 duration:(double)arg2;
- (void)hide;
- (void)tapped:(id)arg1;
- (void)setup;
- (id)initWithStyle:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

