//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel, YKCircleAnimationView;

@interface ChildTextHeaderView : UIView
{
    UILabel *_label;
    YKCircleAnimationView *_imageView;
}

@property(retain, nonatomic) YKCircleAnimationView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

