//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ChildBaseCardView, UIImageView, UIView;

@protocol ChildBaseCardViewDataSource <NSObject>
- (UIView *)childBaseCardView:(ChildBaseCardView *)arg1 contentForMarkView:(UIView *)arg2;
- (struct CGSize)childBaseCardView:(ChildBaseCardView *)arg1 sizeForMarkView:(UIView *)arg2;
- (UIView *)childBaseCardView:(ChildBaseCardView *)arg1 contentForHeaderView:(UIView *)arg2;
- (struct CGSize)childBaseCardView:(ChildBaseCardView *)arg1 sizeForHeaderView:(UIView *)arg2;
- (UIView *)childBaseCardView:(ChildBaseCardView *)arg1 contentForTitleView:(UIView *)arg2;
- (struct CGSize)childBaseCardView:(ChildBaseCardView *)arg1 sizeForTitleView:(UIView *)arg2;
- (UIView *)childBaseCardView:(ChildBaseCardView *)arg1 contentForPosterImageView:(UIImageView *)arg2;
- (struct CGSize)childBaseCardView:(ChildBaseCardView *)arg1 sizeForPosterImageView:(UIView *)arg2;
@end

