//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ClaritySettingModel : NSObject
{
    _Bool _VIP;
    NSString *_title;
    long long _code;
}

+ (id)modelsFromClarityCode:(long long)arg1;
@property(nonatomic) _Bool VIP; // @synthesize VIP=_VIP;
@property(nonatomic) long long code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

