//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "CMSComponentCellProtocol.h"
#import "CardVideoViewDelegate.h"

@class CMSCardVideo, NSString, UIImageView, UIView, YKVIPCardVideoView, YKVIPStarInterface;

@interface CMSComponentVIPStarBigCell : UICollectionViewCell <CMSComponentCellProtocol, CardVideoViewDelegate>
{
    CMSCardVideo *_model;
    YKVIPCardVideoView *_cardVideoView;
    YKVIPStarInterface *_interface;
    UIImageView *_v;
    NSString *_videoId;
    NSString *_imageHorizontalUrl;
    UIImageView *_imageView;
    UIView *_playView;
}

@property(retain, nonatomic) UIView *playView; // @synthesize playView=_playView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSString *imageHorizontalUrl; // @synthesize imageHorizontalUrl=_imageHorizontalUrl;
@property(retain, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(retain, nonatomic) UIImageView *v; // @synthesize v=_v;
@property(nonatomic) __weak YKVIPStarInterface *interface; // @synthesize interface=_interface;
@property(retain, nonatomic) YKVIPCardVideoView *cardVideoView; // @synthesize cardVideoView=_cardVideoView;
@property(retain, nonatomic) CMSCardVideo *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)dealloc;
- (void)clearPlayerInterface;
- (void)updateInterface:(id)arg1;
- (void)networkChange:(id)arg1;
- (void)updateNetworkStatus:(int)arg1;
- (void)playVideo;
- (void)cardVideoViewDidSelectVideo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setupModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

