//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMSJsonResponse.h"

@class DetailJsonRequest, DetailPageItem;

@interface DetailJsonResponse : CMSJsonResponse
{
}


// Remaining properties
@property(retain, nonatomic) DetailJsonRequest *request; // @dynamic request;
@property(retain, nonatomic) DetailPageItem *requestPageItem; // @dynamic requestPageItem;
@end

