//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

@interface DetailComponentCorpsTopCell : UICollectionViewCell
{
    UIImageView *_coverImageView;
    UIImageView *_shadowImageView;
    UIImageView *_logoImageView;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    double _cellLabelWidth;
    double _cellLabelHeight;
}

@property(nonatomic) double cellLabelHeight; // @synthesize cellLabelHeight=_cellLabelHeight;
@property(nonatomic) double cellLabelWidth; // @synthesize cellLabelWidth=_cellLabelWidth;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UIImageView *shadowImageView; // @synthesize shadowImageView=_shadowImageView;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setupWithCardVideo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

