//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DetailComponentCommon.h"

@class BoxCardItem, CardList, NSString;

@interface DetailComponentAdditional : DetailComponentCommon
{
    NSString *_playingVid;
    long long _playingIndex;
    CardList *_cardList;
    BoxCardItem *_item;
    NSString *_vid;
    long long _indexOfCurrentVid;
}

@property(nonatomic) long long indexOfCurrentVid; // @synthesize indexOfCurrentVid=_indexOfCurrentVid;
@property(copy, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(retain, nonatomic) BoxCardItem *item; // @synthesize item=_item;
@property(retain, nonatomic) CardList *cardList; // @synthesize cardList=_cardList;
- (void).cxx_destruct;
- (long long)queryPlayingVideoIndex;
- (_Bool)componentCard:(id)arg1 shouldRequestCardsWhenVideoChangedTo:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (double)collectionViewMinimumLineSpacingInComponentCard:(id)arg1;
- (void)componentCard:(id)arg1 collectionViewDidSelectItemAtIndexPath:(id)arg2;
- (void)componentCard:(id)arg1 didSelectCardHeader:(id)arg2;
- (void)componentCard:(id)arg1 collectionViewReuseCell:(id)arg2 indexPath:(id)arg3;
- (id)collectionViewCellIdentifierInComponentCard:(id)arg1;
- (Class)collectionViewCellClassInComponentCard:(id)arg1;
- (struct CGSize)collectionViewItemSizeInComponentCard:(id)arg1;
- (double)tableViewRowHeightInComponentCard:(id)arg1;
- (void)didFinishFetchDataSourceInComponentCard:(id)arg1;
- (void)didFinishInitConfigurationInComponentCard:(id)arg1;
- (void)resetLayoutItem;
- (double)itemWidth;
- (void)setComponentContext:(id)arg1;

@end

