//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PlayVideoController, UIButton;

@interface DetailPlayerFoldedView : UIView
{
    PlayVideoController *_playVideoController;
    UIButton *_backButton;
}

@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak PlayVideoController *playVideoController; // @synthesize playVideoController=_playVideoController;
- (void).cxx_destruct;
- (void)playAction;
- (void)backAction;
- (void)setupSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

