//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DetailPickerView, NSAttributedString, NSString, UIView;

@protocol DetailPickerViewDelegate <NSObject>

@optional
- (void)pickerView:(DetailPickerView *)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (UIView *)pickerView:(DetailPickerView *)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(UIView *)arg4;
- (NSAttributedString *)pickerView:(DetailPickerView *)arg1 attributedTitleForRow:(long long)arg2 forComponent:(long long)arg3;
- (NSString *)pickerView:(DetailPickerView *)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (double)pickerView:(DetailPickerView *)arg1 rowHeightForComponent:(long long)arg2;
- (double)pickerView:(DetailPickerView *)arg1 widthForComponent:(long long)arg2;
@end

