//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DetailDownloadPickerViewController, DetailPickerView;

@protocol DetailDownloadPickerViewControllerDelegate <NSObject>
- (void)pickerViewControllerDidDismiss:(DetailDownloadPickerViewController *)arg1;
- (void)pickerViewControllerDoneClick:(DetailDownloadPickerViewController *)arg1 pickerView:(DetailPickerView *)arg2;
@end

