//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface DetailSeriesCircleCell : UITableViewCell
{
    UIImageView *_headImage;
    UILabel *_mainTitle;
    UILabel *_subTitle;
    UIImageView *_fansButtonImage;
    UILabel *_fansButtonLabel;
}

@property(retain, nonatomic) UILabel *fansButtonLabel; // @synthesize fansButtonLabel=_fansButtonLabel;
@property(retain, nonatomic) UIImageView *fansButtonImage; // @synthesize fansButtonImage=_fansButtonImage;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *mainTitle; // @synthesize mainTitle=_mainTitle;
@property(retain, nonatomic) UIImageView *headImage; // @synthesize headImage=_headImage;
- (void).cxx_destruct;
- (void)setupWithCardVideo:(id)arg1;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

