//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DownloadError : NSObject
{
    long long _errCode;
    long long _UPSErrorCode;
    long long _oldErrorCode;
    long long _enderrCode;
}

@property(nonatomic) long long enderrCode; // @synthesize enderrCode=_enderrCode;
@property(nonatomic) long long oldErrorCode; // @synthesize oldErrorCode=_oldErrorCode;
@property(nonatomic) long long UPSErrorCode; // @synthesize UPSErrorCode=_UPSErrorCode;
@property(nonatomic) long long errCode; // @synthesize errCode=_errCode;
- (id)init;

@end

