//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DYBottomMessageBoxView, NSMutableArray;

@interface DYBottomMessageBox : NSObject
{
    DYBottomMessageBoxView *_messageBoxView;
    NSMutableArray *_messageQueue;
}

+ (void)hideWithAnimated:(id)arg1;
+ (void)hideItem:(id)arg1;
+ (void)hide;
+ (void)showBottomMessageWithImage:(id)arg1 url:(id)arg2 imageFrame:(struct CGRect)arg3 title:(id)arg4 titleColor:(id)arg5 titleFont:(id)arg6 duration:(double)arg7 animted:(_Bool)arg8;
+ (void)showBottomMessageWithImageUrl:(id)arg1 title:(id)arg2;
+ (void)showBottomMessageWithImage:(id)arg1 title:(id)arg2;
+ (id)shareInstance;
+ (void)dy_showMessage:(id)arg1;
+ (void)dy_showPGCMessageItem:(id)arg1;
+ (void)dy_showPGCHeaderImageUrl:(id)arg1 PGCName:(id)arg2 inDisCoverPage:(_Bool)arg3;
+ (void)dy_showPGCHeaderImageUrl:(id)arg1 PGCName:(id)arg2;
+ (_Bool)dy_shouldShowToast;
@property(retain, nonatomic) NSMutableArray *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(retain, nonatomic) DYBottomMessageBoxView *messageBoxView; // @synthesize messageBoxView=_messageBoxView;
- (void).cxx_destruct;
- (struct CGRect)p_calculateMessageViewFrameWithMessageItem:(id)arg1;
- (void)p_removeMessageItem:(id)arg1;
- (void)p_addMessageItem:(id)arg1;
- (void)p_showFromMessageQueue;
- (void)showBottomMessageWithMessageItem:(id)arg1;
- (id)init;

@end

