//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DYKLauncherItem;

@protocol DYKAppLaunchProtocol <NSObject>

@optional
+ (void)launcherItem:(DYKLauncherItem *)arg1 launchWithConfiguration:(id <DYKAppConfigurationProtocol>)arg2;
+ (void)homePageDidFinishLaunchingWithConfiguration:(id <DYKAppConfigurationProtocol>)arg1;
+ (void)appDidFinishLaunchingWithConfiguration:(id <DYKAppConfigurationProtocol>)arg1;
@end

