//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DYKLauncherQueue, DYKLauncherStatistics, NSDictionary, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_semaphore>;

@interface DYKAppLauncher : NSObject
{
    NSDictionary *_launchItemsConfig;
    unsigned long long _launchStage;
    DYKLauncherQueue *_launcherQueue;
    id <DYKAppConfigurationProtocol> _appConfiguration;
    DYKLauncherStatistics *_launcherStatistics;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _beginBlock;
    CDUnknownBlockType _endBlock;
    NSDictionary *_sessionNameDic;
    unsigned long long _maxConcurrency;
    NSObject<OS_dispatch_semaphore> *_sema;
    NSObject<OS_dispatch_queue> *_receiverQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *receiverQueue; // @synthesize receiverQueue=_receiverQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *sema; // @synthesize sema=_sema;
@property(nonatomic) unsigned long long maxConcurrency; // @synthesize maxConcurrency=_maxConcurrency;
@property(copy, nonatomic) NSDictionary *sessionNameDic; // @synthesize sessionNameDic=_sessionNameDic;
@property(copy, nonatomic) CDUnknownBlockType endBlock; // @synthesize endBlock=_endBlock;
@property(copy, nonatomic) CDUnknownBlockType beginBlock; // @synthesize beginBlock=_beginBlock;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) DYKLauncherStatistics *launcherStatistics; // @synthesize launcherStatistics=_launcherStatistics;
@property(retain, nonatomic) id <DYKAppConfigurationProtocol> appConfiguration; // @synthesize appConfiguration=_appConfiguration;
@property(retain, nonatomic) DYKLauncherQueue *launcherQueue; // @synthesize launcherQueue=_launcherQueue;
@property(nonatomic) unsigned long long launchStage; // @synthesize launchStage=_launchStage;
@property(copy, nonatomic) NSDictionary *launchItemsConfig; // @synthesize launchItemsConfig=_launchItemsConfig;
- (void).cxx_destruct;
- (void)setTaskEndBlock:(CDUnknownBlockType)arg1;
- (void)setTaskBeginBlock:(CDUnknownBlockType)arg1;
- (void)setAppConfiguration:(id)arg1 withLaunchOptions:(id)arg2;
- (void)releaseResource;
- (void)notifyNotification:(id)arg1;
- (void)launchItem:(id)arg1 launchType:(unsigned long long)arg2;
- (void)asyncLaunchIdleQueue:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)syncLaunchItemQueue:(id)arg1 launchType:(unsigned long long)arg2;
- (void)idleTaskLaunch;
- (void)homePageDidFinishLaunch;
- (_Bool)appDidFinishLaunching;
- (id)init;

@end

