//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSNumber, NSString;

@interface DYKLauncherSessionStatisticsModel : NSObject
{
    NSNumber *_costTime;
    NSString *_sessionName;
    NSMutableArray *_items;
}

@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *sessionName; // @synthesize sessionName=_sessionName;
@property(retain, nonatomic) NSNumber *costTime; // @synthesize costTime=_costTime;
- (void).cxx_destruct;
- (id)launchStatisticsItems;
- (void)addItemStatistics:(id)arg1;
- (id)description;

@end

