//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DYKLauncherItem : NSObject
{
    _Bool _isMainThread;
    _Bool _isOptional;
    NSString *_className;
}

@property(nonatomic) _Bool isOptional; // @synthesize isOptional=_isOptional;
@property(nonatomic) _Bool isMainThread; // @synthesize isMainThread=_isMainThread;
@property(copy, nonatomic) NSString *className; // @synthesize className=_className;
- (void).cxx_destruct;
- (void)parseWithInfo:(id)arg1;
- (id)initWitInfo:(id)arg1;

@end

