//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "DYKURLRouterViewControllerProtocol.h"

@class NSString, UIButton, UILabel;

@interface DYKNavigatorUnitTestViewController : UIViewController <DYKURLRouterViewControllerProtocol>
{
    NSString *_objName;
    CDUnknownBlockType _backblock;
    UILabel *_textlabel;
    UIButton *_backButton;
}

@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) UILabel *textlabel; // @synthesize textlabel=_textlabel;
@property(copy, nonatomic) CDUnknownBlockType backblock; // @synthesize backblock=_backblock;
@property(copy, nonatomic) NSString *objName; // @synthesize objName=_objName;
- (void).cxx_destruct;
- (_Bool)lowerViewController:(id)arg1 sameWithTopViewController:(id)arg2;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2 nativeParams:(id)arg3;
- (void)vcExcuteBack;
- (void)click:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

