//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface DYKUploadOSSPartInfoManager : NSObject
{
    NSMutableDictionary *_dbDic;
}

+ (_Bool)removeLocalPartInfosForKey:(id)arg1;
+ (id)loadLastLocalOSSpartInfoForKey:(id)arg1;
+ (id)loadLocalOSSpartInfosForKey:(id)arg1;
+ (_Bool)storeLocalOSSPartInfo:(id)arg1 forKey:(id)arg2;
+ (id)partInfoDBForKey:(id)arg1;
+ (id)targetFilePathForKey:(id)arg1;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)removePartInfoDBForKey:(id)arg1;
- (id)partInfoDBForKey:(id)arg1;
- (id)init;

@end

