//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DYKUploadStateDelegate.h"

@class NSString;

@interface DYKUploadStateOSSCheck : NSObject <DYKUploadStateDelegate>
{
}

+ (unsigned long long)decideNextStateOnTask:(id)arg1 operation:(id)arg2;
+ (unsigned long long)mtopErrorAnalyseOnTask:(id)arg1 operation:(id)arg2;
+ (unsigned long long)ossErrorAnalyseOnTask:(id)arg1 operation:(id)arg2;
+ (unsigned long long)preprocessErrorAnalyseOnTask:(id)arg1 operation:(id)arg2;
+ (_Bool)mtopCheckOnTask:(id)arg1 operation:(id)arg2;
+ (_Bool)ossErrorCheckOnTask:(id)arg1 operation:(id)arg2;
+ (_Bool)preprocessCheck:(id)arg1 operation:(id)arg2;
+ (void)uploadExecute:(id)arg1 operation:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

