//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EBJSEase : NSObject
{
}

+ (id)cubicBezier;
+ (id)linear;
+ (id)easeInOutBounce;
+ (id)easeOutBounce;
+ (id)easeInBounce;
+ (id)easeInOutBack;
+ (id)easeOutBack;
+ (id)easeInBack;
+ (id)easeInOutElastic;
+ (id)easeOutElastic;
+ (id)easeInElastic;
+ (id)easeInOutCirc;
+ (id)easeOutCirc;
+ (id)easeInCirc;
+ (id)easeInOutExpo;
+ (id)easeOutExpo;
+ (id)easeInExpo;
+ (id)easeInOutSine;
+ (id)easeOutSine;
+ (id)easeInSine;
+ (id)easeInOutQuint;
+ (id)easeOutQuint;
+ (id)easeInQuint;
+ (id)easeInOutQuart;
+ (id)easeOutQuart;
+ (id)easeInQuart;
+ (id)easeInOutCubic;
+ (id)easeOutCubic;
+ (id)easeInCubic;
+ (id)easeInOutQuad;
+ (id)easeOutQuad;
+ (id)easeInQuad;

@end

