//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EPCSand : NSObject
{
    _Bool _useNormalizedUVs;
    _Bool _sequenceLoop;
    CDStruct_6181342a _backgroundColor;
    int _sandType;
    float _sizeX;
    float _sizeY;
    float _sizeZ;
    int _lastParticleCountInX;
    int _lastParticleCountInY;
    int _lastParticleCountInZ;
    int _particleCountInX;
    int _particleCountInY;
    int _particleCountInZ;
    float _rotationX;
    float _rotationY;
    float _rotationZ;
    int _sequenceCount;
    float _density;
    float _sequenceSpeed;
    int _sequenceOffset;
    float _curSequenceFlow;
    int _lastSequenceOffset;
    float _sequenceFlowUpdateTime;
    NSString *_OBJModelFile;
    CDStruct_03942939 _position;
    CDStruct_03942939 _gridLMCoordScale;
    CDStruct_03942939 _gridTexCoordScale;
    CDStruct_03942939 _gridPositionScale;
    CDStruct_03942939 _gridPositionOrigin;
}

@property(nonatomic) float sequenceFlowUpdateTime; // @synthesize sequenceFlowUpdateTime=_sequenceFlowUpdateTime;
@property(nonatomic) int lastSequenceOffset; // @synthesize lastSequenceOffset=_lastSequenceOffset;
@property(nonatomic) float curSequenceFlow; // @synthesize curSequenceFlow=_curSequenceFlow;
@property(nonatomic) int sequenceOffset; // @synthesize sequenceOffset=_sequenceOffset;
@property(nonatomic) float sequenceSpeed; // @synthesize sequenceSpeed=_sequenceSpeed;
@property(nonatomic) _Bool sequenceLoop; // @synthesize sequenceLoop=_sequenceLoop;
@property(nonatomic) _Bool useNormalizedUVs; // @synthesize useNormalizedUVs=_useNormalizedUVs;
@property(nonatomic) float density; // @synthesize density=_density;
@property(nonatomic) int sequenceCount; // @synthesize sequenceCount=_sequenceCount;
@property(copy, nonatomic) NSString *OBJModelFile; // @synthesize OBJModelFile=_OBJModelFile;
@property(nonatomic) CDStruct_03942939 gridPositionOrigin; // @synthesize gridPositionOrigin=_gridPositionOrigin;
@property(nonatomic) CDStruct_03942939 gridPositionScale; // @synthesize gridPositionScale=_gridPositionScale;
@property(nonatomic) CDStruct_03942939 gridTexCoordScale; // @synthesize gridTexCoordScale=_gridTexCoordScale;
@property(nonatomic) CDStruct_03942939 gridLMCoordScale; // @synthesize gridLMCoordScale=_gridLMCoordScale;
@property(nonatomic) float rotationZ; // @synthesize rotationZ=_rotationZ;
@property(nonatomic) float rotationY; // @synthesize rotationY=_rotationY;
@property(nonatomic) float rotationX; // @synthesize rotationX=_rotationX;
@property(nonatomic) CDStruct_03942939 position; // @synthesize position=_position;
@property(nonatomic) int particleCountInZ; // @synthesize particleCountInZ=_particleCountInZ;
@property(nonatomic) int particleCountInY; // @synthesize particleCountInY=_particleCountInY;
@property(nonatomic) int particleCountInX; // @synthesize particleCountInX=_particleCountInX;
@property(nonatomic) int lastParticleCountInZ; // @synthesize lastParticleCountInZ=_lastParticleCountInZ;
@property(nonatomic) int lastParticleCountInY; // @synthesize lastParticleCountInY=_lastParticleCountInY;
@property(nonatomic) int lastParticleCountInX; // @synthesize lastParticleCountInX=_lastParticleCountInX;
@property(nonatomic) float sizeZ; // @synthesize sizeZ=_sizeZ;
@property(nonatomic) float sizeY; // @synthesize sizeY=_sizeY;
@property(nonatomic) float sizeX; // @synthesize sizeX=_sizeX;
@property(nonatomic) int sandType; // @synthesize sandType=_sandType;
@property(nonatomic) CDStruct_6181342a backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (_Bool)shouldMorphingSequence;
- (void)updateSequenceStatusWithTime:(double)arg1;
- (void)resetSequenceWithFile:(id)arg1 time:(double)arg2;

@end

