//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "HYDialogueContainerViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class HYDialogueContainerView, NSString, UIScrollView, UIVisualEffectView;

@interface HYDialogueViewController : UIViewController <UIGestureRecognizerDelegate, HYDialogueContainerViewDelegate>
{
    UIScrollView *_scrollView;
    HYDialogueContainerView *_containerView;
    double _containerHeight;
    double _containerWidth;
    UIVisualEffectView *_visualView;
}

@property(retain, nonatomic) UIVisualEffectView *visualView; // @synthesize visualView=_visualView;
@property(nonatomic) double containerWidth; // @synthesize containerWidth=_containerWidth;
@property(nonatomic) double containerHeight; // @synthesize containerHeight=_containerHeight;
@property(retain, nonatomic) HYDialogueContainerView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)updateLayout;
- (void)dismissDialogueViewControllerWith:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)onTableViewWasTapped:(id)arg1;
- (void)handleKeyboardWillHideByScrollingView:(id)arg1;
- (void)handleKeyboardWillShowByScrollingView:(id)arg1;
- (void)keyboardWillBeHidden:(id)arg1;
- (void)keyboardWillBeShown:(id)arg1;
- (void)dismissViewController;
- (void)unregisterForKeyboardNotifications;
- (void)registerForKeyboardNotifications;
- (void)dismissDialogueCompletion:(CDUnknownBlockType)arg1;
- (id)bgImageViewFrow:(id)arg1;
- (void)showDialogue;
- (void)setDialogueView:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

