//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIActivityIndicatorView, UIColor, UIView;

@interface HYNormalButton : UIButton
{
    _Bool _isLoading;
    _Bool _disableGlobalColor;
    UIView *_hyMaskView;
    UIActivityIndicatorView *_activityIndicatorView;
    UIColor *_tempBGColor;
}

@property(retain, nonatomic) UIColor *tempBGColor; // @synthesize tempBGColor=_tempBGColor;
@property(nonatomic) _Bool disableGlobalColor; // @synthesize disableGlobalColor=_disableGlobalColor;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIView *hyMaskView; // @synthesize hyMaskView=_hyMaskView;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (void)setBgColor:(id)arg1;
- (void)disableGlobalColor:(_Bool)arg1;
- (void)customInterface;
- (void)setEnabled:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setUpWithCornRaidus:(double)arg1;
- (void)setup;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

