//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HYBaseDialogueView.h"

#import "HYDialogueProtocol.h"

@class HYDialogueAvatarView, HYDialogueButtonView, HYDialogueTitleView, HYRecommendLoginInfo, NSString;

@interface HYOAuthLoginDialogue : HYBaseDialogueView <HYDialogueProtocol>
{
    HYDialogueAvatarView *_avatarView;
    HYDialogueTitleView *_titleView;
    HYRecommendLoginInfo *_recommendLoginInfo;
    HYDialogueButtonView *_submitView;
    long long _titleHeight;
}

@property(nonatomic) long long titleHeight; // @synthesize titleHeight=_titleHeight;
@property(retain, nonatomic) HYDialogueButtonView *submitView; // @synthesize submitView=_submitView;
@property(retain, nonatomic) HYRecommendLoginInfo *recommendLoginInfo; // @synthesize recommendLoginInfo=_recommendLoginInfo;
@property(retain, nonatomic) HYDialogueTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) HYDialogueAvatarView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (_Bool)disableEdge;
- (double)dialogueWidth;
- (double)dialogueHeight;
- (id)pageName;
- (id)spm;
- (void)closeButtonTapped;
- (void)handleOAuthLoginSuccess;
- (void)submitButtonTap;
- (void)setLoginInfo:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *backgroundImageUrl;
@property(copy, nonatomic) NSString *closeIconImageUrl;
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <HYDialogueContainerViewDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

