//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSURL;

@interface HYUserYoukuAuthManager : NSObject
{
    _Bool _didFinishLaunchApp;
    NSMutableDictionary *_proxyObjects;
    NSURL *_authUrl;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSURL *authUrl; // @synthesize authUrl=_authUrl;
@property(nonatomic) _Bool didFinishLaunchApp; // @synthesize didFinishLaunchApp=_didFinishLaunchApp;
@property(retain, nonatomic) NSMutableDictionary *proxyObjects; // @synthesize proxyObjects=_proxyObjects;
- (void).cxx_destruct;
- (void)receivedAppFinishLaunchNotification:(id)arg1;
- (void)registerProxyObject:(id)arg1 withName:(id)arg2;
- (_Bool)handleOpenURL:(id)arg1;
- (id)init;

@end

