//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HYBaseWebviewController.h"

#import "NSURLConnectionDelegate.h"
#import "UIWebViewDelegate.h"

@class HYJSBridge, HYWebViewProxy, JSContext, NSString, UIBarButtonItem;

@interface HYUserWebViewController : HYBaseWebviewController <UIWebViewDelegate, NSURLConnectionDelegate>
{
    _Bool _needShowLoggedInTip;
    id <HYUserCredentialProtocol> _credential;
    JSContext *_jsContext;
    HYWebViewProxy *_webViewProxy;
    HYJSBridge *_jsBridge;
    UIBarButtonItem *_backItem;
    UIBarButtonItem *_closeItem;
}

@property(retain, nonatomic) UIBarButtonItem *closeItem; // @synthesize closeItem=_closeItem;
@property(retain, nonatomic) UIBarButtonItem *backItem; // @synthesize backItem=_backItem;
@property(retain, nonatomic) HYJSBridge *jsBridge; // @synthesize jsBridge=_jsBridge;
@property(retain, nonatomic) HYWebViewProxy *webViewProxy; // @synthesize webViewProxy=_webViewProxy;
@property(retain, nonatomic) JSContext *jsContext; // @synthesize jsContext=_jsContext;
@property(retain, nonatomic) id <HYUserCredentialProtocol> credential; // @synthesize credential=_credential;
@property(nonatomic) _Bool needShowLoggedInTip; // @synthesize needShowLoggedInTip=_needShowLoggedInTip;
- (void).cxx_destruct;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)hideCloseItem:(_Bool)arg1;
- (void)closeSelf;
- (void)hyWebGoBackAction:(_Bool)arg1;
- (void)closeWebView;
- (void)hyWebGoBackAction;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

