//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextView.h"

@interface HYWordDetectTextView : UITextView
{
    id <HYWordDetectDelegate> _wordDetectDelegate;
}

@property(nonatomic) __weak id <HYWordDetectDelegate> wordDetectDelegate; // @synthesize wordDetectDelegate=_wordDetectDelegate;
- (void).cxx_destruct;
- (void)tapResponse:(id)arg1;
- (void)setUp;
- (void)awakeFromNib;
- (id)init;

@end

