//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSObjectionEntry.h"

@interface JSObjectionBindingEntry : JSObjectionEntry
{
    id _instance;
}

- (void).cxx_destruct;
- (void)dealloc;
- (int)lifeCycle;
- (id)extractObject:(id)arg1;
- (id)initWithObject:(id)arg1;

@end

