//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JSObjectionInjector;

@interface JSObjectFactory : NSObject
{
    JSObjectionInjector *_injector;
}

@property(readonly, nonatomic) __weak JSObjectionInjector *injector; // @synthesize injector=_injector;
- (void).cxx_destruct;
- (id)getObjectWithArgs:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (id)getObject:(id)arg1 named:(id)arg2 withArgumentList:(id)arg3;
- (id)getObject:(id)arg1 initializer:(SEL)arg2 withArgumentList:(id)arg3;
- (id)getObject:(id)arg1 withArgumentList:(id)arg2;
- (id)getObject:(id)arg1;
- (id)initWithInjector:(id)arg1;

@end

