//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YKKKRecommendMoreViewDelegate.h"

@class KKRecommendCardsViewController, NSString, YKJSONClient, YKKKRecommendMoreView;

@interface KKYKHLMoreActionModule : NSObject <YKKKRecommendMoreViewDelegate>
{
    KKRecommendCardsViewController *_superViewController;
    YKKKRecommendMoreView *_moreView;
    YKJSONClient *_collectJosnClient;
}

@property(retain, nonatomic) YKJSONClient *collectJosnClient; // @synthesize collectJosnClient=_collectJosnClient;
@property(retain, nonatomic) YKKKRecommendMoreView *moreView; // @synthesize moreView=_moreView;
@property(nonatomic) __weak KKRecommendCardsViewController *superViewController; // @synthesize superViewController=_superViewController;
- (void).cxx_destruct;
- (void)ykRecommendMoreView:(id)arg1 selectIndex:(long long)arg2;
- (void)ykRecommendMoreView:(id)arg1 didSelectSharePlatform:(id)arg2;
- (void)unCollection;
- (void)collection;
- (void)collectionClick;
- (void)showRecommendMoreView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

