//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKBaseModel.h"

@class NSMutableArray, NSString;

@interface KuboxSuggestAllModels : SKBaseModel
{
    NSString *_engine;
    NSMutableArray *_allModels;
}

@property(retain, nonatomic) NSMutableArray *allModels; // @synthesize allModels=_allModels;
@property(copy, nonatomic) NSString *engine; // @synthesize engine=_engine;
- (void).cxx_destruct;
- (id)getMatchingHistoryWords;
- (id)initWithDic:(id)arg1;

@end

