//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFDropGiftModel, UIImage;

@interface LFDropGiftManager : NSObject
{
    _Bool _giftDroped;
    CDUnknownBlockType _popupFlowingDropGiftImage;
    LFDropGiftModel *_giftDropInfo;
    UIImage *_giftFlowingImage;
}

+ (id)sharedManager;
@property(nonatomic) _Bool giftDroped; // @synthesize giftDroped=_giftDroped;
@property(retain, nonatomic) UIImage *giftFlowingImage; // @synthesize giftFlowingImage=_giftFlowingImage;
@property(retain, nonatomic) LFDropGiftModel *giftDropInfo; // @synthesize giftDropInfo=_giftDropInfo;
@property(copy, nonatomic) CDUnknownBlockType popupFlowingDropGiftImage; // @synthesize popupFlowingDropGiftImage=_popupFlowingDropGiftImage;
- (void).cxx_destruct;
- (void)downloadAndShowGiftImage;
- (id)fireFlowingIsFropGift;
- (void)downDropImg:(id)arg1;
- (id)init;

@end

