//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFFeedbackView, NSArray, NSString;

@protocol LFFeedbackViewDelegate <NSObject>
- (void)feedbackView:(LFFeedbackView *)arg1 didChangeText:(NSString *)arg2;
- (void)feedbackView:(LFFeedbackView *)arg1 didChangeReasons:(NSArray *)arg2;
@end

