//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFFeedbackUser, NSArray, NSString;

@interface LFFeedbackModel : NSObject
{
    unsigned long long _type;
    LFFeedbackUser *_toUser;
    LFFeedbackUser *_fromUser;
    NSString *_roomID;
    NSArray *_assets;
    NSString *_text;
    NSArray *_reasons;
}

@property(retain, nonatomic) NSArray *reasons; // @synthesize reasons=_reasons;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSArray *assets; // @synthesize assets=_assets;
@property(retain, nonatomic) NSString *roomID; // @synthesize roomID=_roomID;
@property(retain, nonatomic) LFFeedbackUser *fromUser; // @synthesize fromUser=_fromUser;
@property(retain, nonatomic) LFFeedbackUser *toUser; // @synthesize toUser=_toUser;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
@property(readonly) _Bool isValid;
- (id)init;

@end

