//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface LFLiveExtendItemView : UIView
{
    CDUnknownBlockType _beautyButtonClickedBlock;
    CDUnknownBlockType _flashButtonClickedBlock;
    UIButton *_beautyButton;
    UIButton *_flashButton;
    UIView *_weakFromeView;
}

@property(nonatomic) __weak UIView *weakFromeView; // @synthesize weakFromeView=_weakFromeView;
@property(retain, nonatomic) UIButton *flashButton; // @synthesize flashButton=_flashButton;
@property(retain, nonatomic) UIButton *beautyButton; // @synthesize beautyButton=_beautyButton;
@property(copy, nonatomic) CDUnknownBlockType flashButtonClickedBlock; // @synthesize flashButtonClickedBlock=_flashButtonClickedBlock;
@property(copy, nonatomic) CDUnknownBlockType beautyButtonClickedBlock; // @synthesize beautyButtonClickedBlock=_beautyButtonClickedBlock;
- (void).cxx_destruct;
- (void)flashButtonClicked:(id)arg1;
- (void)beautyButtonClicked:(id)arg1;
- (void)hideView;
- (void)showInView:(id)arg1 fromView:(id)arg2 captureDevicePosition:(long long)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

