//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface LFLoginSettings : NSObject
{
    NSString *_passportAppID;
    char *_passportAppSecret;
}

+ (id)sharedSettings;
@property(copy, nonatomic) NSString *passportAppID; // @synthesize passportAppID=_passportAppID;
- (void).cxx_destruct;
- (char *)passportAppSecret;

@end

