//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LFPanGestureConfig : NSObject
{
    double _beganTimeStamp;
    long long _direction;
    double _delta;
    double _percent;
    struct CGPoint _beganPoint;
    struct CGPoint _currentPoint;
    struct CGPoint _prevPoint;
}

@property(nonatomic) double percent; // @synthesize percent=_percent;
@property(nonatomic) double delta; // @synthesize delta=_delta;
@property(nonatomic) struct CGPoint prevPoint; // @synthesize prevPoint=_prevPoint;
@property(nonatomic) struct CGPoint currentPoint; // @synthesize currentPoint=_currentPoint;
@property(nonatomic) struct CGPoint beganPoint; // @synthesize beganPoint=_beganPoint;
@property(nonatomic) long long direction; // @synthesize direction=_direction;
@property(nonatomic) double beganTimeStamp; // @synthesize beganTimeStamp=_beganTimeStamp;
- (void)resetStatus;

@end

