//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface LFPlayerReportModel : NSObject
{
    NSString *_roomId;
    NSString *_alias;
    NSString *_userId;
    NSString *_url;
    NSString *_scid;
    NSString *_idfa;
    long long _loadingTime;
    long long _cbec;
    NSMutableArray *_kaTimes;
    NSString *_lastKaTime;
}

@property(copy, nonatomic) NSString *lastKaTime; // @synthesize lastKaTime=_lastKaTime;
@property(retain, nonatomic) NSMutableArray *kaTimes; // @synthesize kaTimes=_kaTimes;
@property(nonatomic) long long cbec; // @synthesize cbec=_cbec;
@property(nonatomic) long long loadingTime; // @synthesize loadingTime=_loadingTime;
@property(copy, nonatomic) NSString *idfa; // @synthesize idfa=_idfa;
@property(copy, nonatomic) NSString *scid; // @synthesize scid=_scid;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *netTypeStr;
- (id)init;

@end

