//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFUIEmotion, LFUIEmotionPageCell;

@protocol LFUIEmotionPageCellDelegate <NSObject>

@optional
- (void)didSelectDeleteButtonInEmotionPageCell:(LFUIEmotionPageCell *)arg1;
- (void)emotionPageCell:(LFUIEmotionPageCell *)arg1 didSelectEmotion:(LFUIEmotion *)arg2 atIndex:(long long)arg3;
@end

