//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFUIInputTextView;

@protocol LFUIInputTextViewDelegate <NSObject>

@optional
- (void)textView:(LFUIInputTextView *)arg1 changeFrameFrom:(struct CGRect)arg2 toFrame:(struct CGRect)arg3 duration:(double)arg4;
@end

