//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSArray, NSMutableArray, UIButton, UITapGestureRecognizer;

@interface LFUIEmotionPageCell : UICollectionViewCell
{
    id _delegate;
    UIButton *_deleteButton;
    NSArray *_emotions;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSMutableArray *_emotionHittingRects;
}

@property(retain, nonatomic) NSMutableArray *emotionHittingRects; // @synthesize emotionHittingRects=_emotionHittingRects;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(copy, nonatomic) NSArray *emotions; // @synthesize emotions=_emotions;
@property(retain, nonatomic) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleDeleteButtonEvent:(id)arg1;
- (void)handleTapGestureRecognizer:(id)arg1;
- (void)drawImage:(id)arg1 inRect:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

