//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LFUsersLibrary : NSObject
{
}

+ (void)updateGender:(long long)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)updateNickname:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)updateIntroduction:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (void)updateAvatar:(id)arg1 up:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)fetchBlockedUsersWithParameters:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)unblockUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)blockUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)fetchfollowedUsersWithParameters:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)unfollowUser:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)followUser:(id)arg1 roomID:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)initialize;
+ (unsigned long long)blockTotalNumber;
+ (unsigned long long)followTotalNumber;
+ (void)setBlockTotalNumber:(unsigned long long)arg1;
+ (void)setFollowTotalNumber:(unsigned long long)arg1;

@end

