//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LFVideoCapture;

@protocol LFVideoCaptureDelegate <NSObject>

@optional
- (void)captureVideoOutput:(LFVideoCapture *)arg1 sampleBuffer:(struct opaqueCMSampleBuffer *)arg2;
- (void)captureOutput:(LFVideoCapture *)arg1 pixelBuffer:(struct __CVBuffer *)arg2 time:(CDStruct_1b6d18a9)arg3;
@end

