//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView<LSQuizInputProtocol>, UIView<UITextInput>;

@protocol LSQuizInputControllerDelegate <NSObject>

@optional
- (void)inputController:(id)arg1 inputView:(UIView<LSQuizInputProtocol> *)arg2 field:(UIView<UITextInput> *)arg3 commitText:(NSString *)arg4;
@end

