//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MCMobileMessageJumpModel : NSObject
{
    NSString *_jump_url;
    long long _jump_type;
}

@property(nonatomic) long long jump_type; // @synthesize jump_type=_jump_type;
@property(retain, nonatomic) NSString *jump_url; // @synthesize jump_url=_jump_url;
- (void).cxx_destruct;

@end

