//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MotuReportAdapteHandler : NSObject
{
}

- (_Bool)adapterSyncWithExceptionModule:(id)arg1;
- (void)adapterWithExceptionModule:(id)arg1;

@end

