//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (LFHTTPResponseSerializerV1Addtions)
+ (id)_ln_dictionary:(id)arg1 objectForKey:(id)arg2 class:(Class)arg3;
+ (id)_ln_dictionary:(id)arg1 stringValueForKey:(id)arg2;
@end

