//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (YKCSModelValueAdditions)
- (id)ykcs_objectForKey:(id)arg1;
- (id)ykcs_stringForKey:(id)arg1;
- (id)ykcs_numberForKey:(id)arg1;
- (unsigned long long)ykcs_unsignedIntegerForKey:(id)arg1;
- (long long)ykcs_integerForKey:(id)arg1;
- (double)ykcs_doubleForKey:(id)arg1;
- (float)ykcs_floatForKey:(id)arg1;
- (unsigned long long)ykcs_unsignedLongLongForKey:(id)arg1;
- (long long)ykcs_longLongForKey:(id)arg1;
- (unsigned long long)ykcs_unsignedLongForKey:(id)arg1;
- (long long)ykcs_longForKey:(id)arg1;
- (unsigned int)ykcs_unsignedIntForKey:(id)arg1;
- (int)ykcs_intForKey:(id)arg1;
- (unsigned short)ykcs_unsignedShortForKey:(id)arg1;
- (short)ykcs_shortForKey:(id)arg1;
- (unsigned char)ykcs_unsignedCharForKey:(id)arg1;
- (BOOL)ykcs_charForKey:(id)arg1;
- (_Bool)ykcs_boolForKey:(id)arg1;
- (id)ykcs_stringForKey:(id)arg1 withDefault:(id)arg2;
- (id)ykcs_numberForKey:(id)arg1 withDefault:(id)arg2;
- (unsigned long long)ykcs_unsignedIntegerForKey:(id)arg1 withDefault:(unsigned long long)arg2;
- (long long)ykcs_integerForKey:(id)arg1 withDefault:(long long)arg2;
- (double)ykcs_doubleForKey:(id)arg1 withDefault:(double)arg2;
- (float)ykcs_floatForKey:(id)arg1 withDefault:(float)arg2;
- (unsigned long long)ykcs_unsignedLongLongForKey:(id)arg1 withDefault:(unsigned long long)arg2;
- (long long)ykcs_longLongForKey:(id)arg1 withDefault:(long long)arg2;
- (unsigned long long)ykcs_unsignedLongForKey:(id)arg1 withDefault:(unsigned long long)arg2;
- (long long)ykcs_longForKey:(id)arg1 withDefault:(long long)arg2;
- (unsigned int)ykcs_unsignedIntForKey:(id)arg1 withDefault:(unsigned int)arg2;
- (int)ykcs_intForKey:(id)arg1 withDefault:(int)arg2;
- (unsigned short)ykcs_unsignedShortForKey:(id)arg1 withDefault:(unsigned short)arg2;
- (short)ykcs_shortForKey:(id)arg1 withDefault:(short)arg2;
- (unsigned char)ykcs_unsignedCharForKey:(id)arg1 withDefault:(unsigned char)arg2;
- (BOOL)ykcs_charForKey:(id)arg1 withDefault:(BOOL)arg2;
- (_Bool)ykcs_boolForKey:(id)arg1 withDefault:(_Bool)arg2;
- (id)ykcs_objectForKey:(id)arg1 class:(Class)arg2;
- (id)ykcs_queryString;
- (id)ykcs_timestampDataForKey:(id)arg1 withDefault:(id)arg2;
- (double)ykcs_timeIntervalForKey:(id)arg1 withDefault:(double)arg2;
@end

