//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (YKFAdditions)
+ (id)YKF_getAppVer;
+ (id)YKF_cachePath;
+ (_Bool)YKF_addSkipBackupAttributeToItemAtURL:(id)arg1;
+ (id)YKF_documentPath;
- (id)YKF_firstUppercaseString;
- (id)YKF_camelFromUnderline;
- (id)YKF_trim;
- (id)YKF_unescapeHTML;
- (id)YKF_gtm_stringByUnescapingFromHTML;
- (_Bool)YKF_isEmpty;
- (id)YKF_toSongURL;
- (id)YKF_toURL;
@end

