//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (YKSDraw)
+ (struct CGSize)yks_IPStringSize:(id)arg1 maxSize:(struct CGSize)arg2;
+ (struct CGSize)yks_IPStringSize:(id)arg1;
+ (id)yks_mutableAttributedString:(id)arg1 font:(id)arg2 constrainedSize:(struct CGSize)arg3 alignment:(long long)arg4 lineBreakMode:(long long)arg5;
- (struct CGSize)yks_IPStringSizeToFit:(id)arg1 constrainedSize:(struct CGSize)arg2 alignment:(long long)arg3 lineBreakMode:(long long)arg4;
- (struct CGSize)yks_IPStringSizeToFit:(id)arg1 constrainedSize:(struct CGSize)arg2;
- (id)yks_drawIPStringIn:(struct CGRect)arg1 withFont:(id)arg2 textColor:(id)arg3 alignment:(long long)arg4 lineBreakMode:(long long)arg5 attributed:(CDUnknownBlockType)arg6;
- (id)yks_drawIPStringIn:(struct CGRect)arg1 withFont:(id)arg2 textColor:(id)arg3;
- (id)yks_drawIPStringIn:(struct CGRect)arg1 withFont:(id)arg2 textColor:(id)arg3 attributed:(CDUnknownBlockType)arg4;
- (struct CGSize)yks_sizeWithFont:(id)arg1 constrainedToSize:(struct CGSize)arg2 alignment:(long long)arg3 lineBreakMode:(long long)arg4;
- (struct CGSize)yks_sizeWithFont:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (void)yks_drawInRect:(struct CGRect)arg1 font:(id)arg2 color:(id)arg3 alignment:(long long)arg4 lineBreakMode:(long long)arg5;
- (void)yks_drawInRect:(struct CGRect)arg1 font:(id)arg2 color:(id)arg3;
@end

