//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString, NSURLRequest;

@protocol NWSessionAuthenticationProtocol <NSObject>
- (void)onAuthSuccess;
- (void)onAuthResponseError;
- (void)onAuthRequestError:(NSError *)arg1;
- (_Bool)sendAuthRequest:(NSURLRequest *)arg1;
- (NSString *)scheme;
- (NSString *)host;
@end

