//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, OPBarragePosterRecordShareView, UIButton, UIScrollView;

@protocol OPBarragePosterRecordShareViewDelegate <NSObject>

@optional
- (void)shareViewExposeStaticsWithPlatformIdStr:(NSString *)arg1 withYKShareSourceId:(int)arg2;
- (void)interShareViewButtonDidFinishLayout:(OPBarragePosterRecordShareView *)arg1 titledButtons:(UIButton *)arg2;
- (void)interScrollViewDidEndDecelerating:(UIScrollView *)arg1 pageIndex:(long long)arg2;
- (void)interScrollViewWillBeginDragging:(UIScrollView *)arg1 pageIndex:(long long)arg2;
- (void)interShareViewButtonDidClickedWithPlatformId:(int)arg1;
@end

