//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@protocol OPBaseErrorViewDelegate <NSObject>
- (void)clickFeedbackWithErr:(NSDictionary *)arg1 block:(void (^)(_Bool))arg2;
- (void)clickToReportErrorButton;
- (NSArray *)recommendedQuality;
- (void)clickToReplayWithQuality:(NSString *)arg1;
@end

