//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OPPlugin.h"

#import "DYKH5BaseWebViewControllerDelegate.h"
#import "OPInterceptRecordViewDelegate.h"
#import "OPLayoutModelDelegate.h"
#import "YKBarrageManagerDelegate.h"

@class NSDictionary, NSMutableArray, NSString, OPBarrageInputHelper, OPBarragePosterRecordView, OPBottomLayoutModel, OPConsoleBubbleLayoutModel, OPLayoutModel, OPServiceMoreLayoutModel, OPSubmenuH5LayoutModel, OPSubmenuLayoutModel, OPTopLayoutModel, UIButton, UIImage, UIView, YKBarrageManager, YKBarrageUser, YKShareInfoItem, YKVideoSnippet;

@interface OPBarragePlugin : OPPlugin <YKBarrageManagerDelegate, DYKH5BaseWebViewControllerDelegate, OPLayoutModelDelegate, OPInterceptRecordViewDelegate>
{
    YKBarrageManager *_barrageManager;
    YKBarrageUser *_barrageUser;
    int _popularizeAD;
    YKShareInfoItem *_sharedItem;
    NSMutableArray *_sharedList;
    NSMutableArray *_sharedSourceList;
    OPServiceMoreLayoutModel *_moreLayout;
    OPTopLayoutModel *_topLayout;
    OPBottomLayoutModel *_consoleInputLayout;
    OPConsoleBubbleLayoutModel *_bubbleLayout;
    OPSubmenuLayoutModel *_liveSubmenuLayout;
    OPBottomLayoutModel *_liveInteractLayout;
    OPSubmenuH5LayoutModel *_h5SubmenuLayout;
    OPLayoutModel *_shareLayout;
    NSString *_vid;
    YKVideoSnippet *_snippet;
    UIView *_liveControlView;
    NSString *_livePromptText;
    UIButton *_liveBarrageButton;
    UIView *_shareContainerView;
    _Bool _isScreenLocked;
    _Bool _shouldShowMessageWhenUnlock;
    _Bool _isShowConsole;
    _Bool _showActivityNextTime;
    _Bool _showBarrageState;
    long long _originPlayState;
    _Bool _originEnableAutorotateState;
    OPBarrageInputHelper *_inputHelper;
    _Bool _isInputting;
    NSDictionary *_interactivePoints;
    CDUnknownBlockType _layoutBlock;
    long long _realNameAlertNeedResumePlayer;
    OPBarragePosterRecordView *_posterRecordView;
    UIImage *_captureImage;
}

@property(retain, nonatomic) UIImage *captureImage; // @synthesize captureImage=_captureImage;
@property(retain, nonatomic) OPBarragePosterRecordView *posterRecordView; // @synthesize posterRecordView=_posterRecordView;
@property(nonatomic) long long realNameAlertNeedResumePlayer; // @synthesize realNameAlertNeedResumePlayer=_realNameAlertNeedResumePlayer;
@property(copy, nonatomic) CDUnknownBlockType layoutBlock; // @synthesize layoutBlock=_layoutBlock;
@property(nonatomic) _Bool isInputting; // @synthesize isInputting=_isInputting;
@property(copy, nonatomic) NSDictionary *interactivePoints; // @synthesize interactivePoints=_interactivePoints;
- (void).cxx_destruct;
- (void)removeInterceptRecordView;
- (void)didDismissRecordViewInBarragePosterRecordView:(id)arg1;
- (void)recoverPlayerPreStates;
- (void)recordPlayerCurrentStates;
- (void)setupInterceptRecordViewWithImage:(id)arg1 info:(id)arg2;
- (void)playerWillExitCaptureScreenState;
- (id)captureScreen:(id)arg1 hasWaterMark:(_Bool)arg2;
- (void)playerWillEnterCaptureScreenState;
- (void)showLiveBarrageButton;
- (void)hideLiveBarrageButton;
- (void)liveBarrageButtonDidSelect;
- (void)configLiveBarrageButton:(id)arg1;
- (void)showBarrageSettingView;
- (id)convertToYKBarrageShareTypeWithArray:(id)arg1;
- (void)webViewControllercloseBtnClicked:(id)arg1;
- (void)webViewControllerDidExit:(id)arg1;
- (void)layoutWillAppear:(id)arg1;
- (void)layoutDidDisappear:(id)arg1;
- (void)layoutDidAppear:(id)arg1;
- (void)didGetInteractivePoints:(id)arg1;
- (id)getVideoSnippet;
- (void)resumePlayer;
- (void)pausePlayer;
- (void)routeWithUserActionModel:(id)arg1;
- (void)closeHalfScreenH5WithOldVideo:(id)arg1;
- (void)openHalfScreenH5WithPath:(id)arg1;
- (void)barrageSwitchChangedTo:(_Bool)arg1;
- (void)notifyAirplayBarrageSwitchState:(_Bool)arg1;
- (void)postMessage:(id)arg1;
- (void)hideBarrageInputView;
- (void)showBarrageInputView:(id)arg1 needLogin:(_Bool)arg2;
- (_Bool)isInIphoneX;
- (void)showBarrageInputView:(id)arg1;
- (void)showLiveBarrageControlView:(id)arg1 withPrompt:(id)arg2;
- (void)dismissLiveBarrageControlView:(id)arg1;
- (id)getShareItems;
- (void)notifyAnalyticsDataChanged:(id)arg1;
- (void)executeWorldCupBubbleTask;
- (void)executeBubbleTask;
- (void)sendOnAndHeight:(_Bool)arg1 height:(double)arg2;
- (void)registerBarrageTask:(_Bool)arg1;
- (void)registerMoreTask;
- (void)registerConsoleTask;
- (void)registerLiveModuleTask;
- (id)statisticsInfo;
- (void)receiveMemberInfoDidChangeNotification:(id)arg1;
- (void)receiveLoginStateDidChangeNotification:(id)arg1;
- (void)setupBarrageUser;
- (void)hideInputView;
- (void)displayBarrageAtSecond:(double)arg1;
- (void)clearBarrage;
- (void)createBarrage;
- (void)setupBarrage:(_Bool)arg1;
- (void)playDidHideConsole;
- (void)playDidShowConsole;
- (void)playLockScreenDidChange;
- (void)playModeIsChanging;
- (void)playModeWillChange;
- (void)playingTimeDidChange;
- (void)playInterruptCodeDidChange;
- (void)playModeDidChange;
- (void)airplaySupportBarrage;
- (void)playStateDidChange;
- (void)playSceneDidChange;
- (void)unregisterAndCancelTopLayout;
- (void)unregisterAndCancelInputLayout;
- (void)unregisterAndCancelTopAndInputLayout;
- (void)playingVideoDidChange:(id)arg1;
- (void)playingVideoInfoDidPrepare;
- (void)playWillDeactivate;
- (void)playDidActivate;
- (void)receiveShareNotification:(id)arg1;
- (void)receiveCaptureNotification:(id)arg1;
- (void)receiveWirelessPlayerEventNotification:(id)arg1;
- (void)onReceived:(id)arg1;
- (void)onDeInit;
- (void)onRun;
- (void)onInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

