//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OPPlugin.h"

@class PlayVideoController;

@interface OPDetailToFeedPlugin : OPPlugin
{
    PlayVideoController *_playVideoController;
}

+ (id)params;
@property(nonatomic) __weak PlayVideoController *playVideoController; // @synthesize playVideoController=_playVideoController;
- (void).cxx_destruct;
- (void)disableHeadsetPlugged:(_Bool)arg1;
- (void)disableOrientation:(_Bool)arg1;
- (void)pauseDetailPlay;
- (void)onReceived:(id)arg1;
- (void)onRun;
- (void)dealloc;

@end

