//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UILabel, UITapGestureRecognizer;

@interface OPHitSharedErrorView : UIView
{
    UILabel *_titleLabel;
    UIButton *_detailButton;
    long long _screenMode;
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSString *_urlString;
    id <OPHitSharedErrorViewDelegate> _delegate;
}

@property(nonatomic) __weak id <OPHitSharedErrorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tapClick:(id)arg1;
- (void)clickButtonAction:(id)arg1;
- (void)setHitSharedErrorLink:(id)arg1;
- (void)setHitSharedErrorDescription:(id)arg1;
- (void)setHitSharedErrorViewScreenMode:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

