//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class OPMoreSwitch, UILabel;

@interface OPMoreSwitchView : UIView
{
    OPMoreSwitch *_switchButton;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) OPMoreSwitch *switchButton; // @synthesize switchButton=_switchButton;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

