//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class OPPlugin, YTEnginePlayer;

@interface OPPlayerRelatedEventHelper : NSObject
{
    YTEnginePlayer *_player;
    OPPlugin *_plugin;
}

@property(nonatomic) __weak OPPlugin *plugin; // @synthesize plugin=_plugin;
@property(nonatomic) __weak YTEnginePlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)collectVid:(id *)arg1 position:(double *)arg2 fromParams:(id)arg3;
- (unsigned long long)convertDecodeStringToEnum:(id)arg1;
- (_Bool)isShowPlayerInfo:(id)arg1;
- (id)pickUpYoukuIdFromPlayerInfo:(id)arg1;
- (void)onPreparePlayWithData:(id)arg1;
- (void)handlePlayerEventRequest:(id)arg1 params:(id)arg2 result:(id *)arg3;

@end

