//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface OPPreVIPAdvStreamModel : NSObject
{
    double _millisecondsVideo;
    long long _qualityType;
    NSString *_qualityString;
    NSArray *_segments;
}

+ (long long)typeFromString:(id)arg1;
+ (id)parseItem:(id)arg1;
@property(copy, nonatomic) NSArray *segments; // @synthesize segments=_segments;
@property(copy, nonatomic) NSString *qualityString; // @synthesize qualityString=_qualityString;
@property(nonatomic) long long qualityType; // @synthesize qualityType=_qualityType;
@property(nonatomic) double millisecondsVideo; // @synthesize millisecondsVideo=_millisecondsVideo;
- (void).cxx_destruct;

@end

