//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface OPRequestParam : NSObject
{
    _Bool _isHaveList;
    _Bool _isHaveNext;
    _Bool _isPlaylist;
    int _videoSubjectType;
    int _autoPlayType;
    NSString *_aid;
    long long _routerWT;
    NSDictionary *_barrageStatisticsDic;
    NSString *_spmAB;
    NSString *_scgId;
    NSString *_vvEndScgId;
    NSString *_pageId;
    NSString *_trackInfo;
    NSString *_scm;
    NSString *_utparam;
    long long _isVip;
    NSString *_vvid;
    double _vvStartTime;
    NSString *_advanceCache;
    NSString *_startCacheTime;
    NSString *_realVideoLength;
    NSString *_adInfos;
    NSString *_playDolbyTimes;
    NSString *_playDolbyDuration;
    NSString *_playStyle;
    NSString *_playTrigger;
    NSString *_vvreason;
}

@property(copy) NSString *vvreason; // @synthesize vvreason=_vvreason;
@property(copy) NSString *playTrigger; // @synthesize playTrigger=_playTrigger;
@property(copy) NSString *playStyle; // @synthesize playStyle=_playStyle;
@property(copy) NSString *playDolbyDuration; // @synthesize playDolbyDuration=_playDolbyDuration;
@property(copy) NSString *playDolbyTimes; // @synthesize playDolbyTimes=_playDolbyTimes;
@property(copy) NSString *adInfos; // @synthesize adInfos=_adInfos;
@property(copy) NSString *realVideoLength; // @synthesize realVideoLength=_realVideoLength;
@property(copy) NSString *startCacheTime; // @synthesize startCacheTime=_startCacheTime;
@property(copy) NSString *advanceCache; // @synthesize advanceCache=_advanceCache;
@property double vvStartTime; // @synthesize vvStartTime=_vvStartTime;
@property(copy) NSString *vvid; // @synthesize vvid=_vvid;
@property long long isVip; // @synthesize isVip=_isVip;
@property(copy) NSString *utparam; // @synthesize utparam=_utparam;
@property(copy) NSString *scm; // @synthesize scm=_scm;
@property(copy) NSString *trackInfo; // @synthesize trackInfo=_trackInfo;
@property(copy) NSString *pageId; // @synthesize pageId=_pageId;
@property(copy) NSString *vvEndScgId; // @synthesize vvEndScgId=_vvEndScgId;
@property(copy) NSString *scgId; // @synthesize scgId=_scgId;
@property(copy) NSString *spmAB; // @synthesize spmAB=_spmAB;
@property int autoPlayType; // @synthesize autoPlayType=_autoPlayType;
@property(copy) NSDictionary *barrageStatisticsDic; // @synthesize barrageStatisticsDic=_barrageStatisticsDic;
@property long long routerWT; // @synthesize routerWT=_routerWT;
@property int videoSubjectType; // @synthesize videoSubjectType=_videoSubjectType;
@property(copy) NSString *aid; // @synthesize aid=_aid;
@property _Bool isPlaylist; // @synthesize isPlaylist=_isPlaylist;
@property _Bool isHaveNext; // @synthesize isHaveNext=_isHaveNext;
@property _Bool isHaveList; // @synthesize isHaveList=_isHaveList;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *vvUserActionDic;
@property(readonly, copy, nonatomic) NSDictionary *vvFeelingDic;
@property(readonly, copy, nonatomic) NSDictionary *vvEndDic;
@property(readonly, copy, nonatomic) NSDictionary *vvBeginDic;
@property(readonly, copy, nonatomic) NSDictionary *vvDataDic;

@end

