//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OPSSAnalyticsHelper : NSObject
{
}

+ (void)analyticsWithEventid:(id)arg1 arg1:(id)arg2 spmd:(id)arg3 vid:(id)arg4 showid:(id)arg5 result:(id)arg6 type:(id)arg7 share:(id)arg8 mode:(id)arg9;
+ (int)openPlatformId2shareId:(int)arg1;

@end

