//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSString;

@interface OPSSInterceptShapeEditView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _movieConstraintClicked;
    id _delegate;
    unsigned long long _type;
    unsigned long long _shapeType;
    UIView *_maskCoverView;
    UIView *_handlerView;
    NSMutableArray *_shapeButtons;
    NSLayoutConstraint *_handlerViewT;
    NSLayoutConstraint *_handlerViewL;
    NSLayoutConstraint *_handlerViewB;
    NSLayoutConstraint *_handlerViewR;
    NSLayoutConstraint *_handlerWidth;
    NSLayoutConstraint *_handlerHeight;
    NSLayoutConstraint *_handlerCenterX;
    NSLayoutConstraint *_handlerCenterY;
    UIView *_backgroundView;
    struct CGPoint _lengthWayConstraint;
    struct CGPoint _movieConstraint;
    struct CGPoint _squireConstraint;
    struct CGRect _playerViewFrame;
}

@property(nonatomic) struct CGPoint squireConstraint; // @synthesize squireConstraint=_squireConstraint;
@property(nonatomic) struct CGPoint movieConstraint; // @synthesize movieConstraint=_movieConstraint;
@property(nonatomic) struct CGPoint lengthWayConstraint; // @synthesize lengthWayConstraint=_lengthWayConstraint;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSLayoutConstraint *handlerCenterY; // @synthesize handlerCenterY=_handlerCenterY;
@property(retain, nonatomic) NSLayoutConstraint *handlerCenterX; // @synthesize handlerCenterX=_handlerCenterX;
@property(retain, nonatomic) NSLayoutConstraint *handlerHeight; // @synthesize handlerHeight=_handlerHeight;
@property(retain, nonatomic) NSLayoutConstraint *handlerWidth; // @synthesize handlerWidth=_handlerWidth;
@property(retain, nonatomic) NSLayoutConstraint *handlerViewR; // @synthesize handlerViewR=_handlerViewR;
@property(retain, nonatomic) NSLayoutConstraint *handlerViewB; // @synthesize handlerViewB=_handlerViewB;
@property(retain, nonatomic) NSLayoutConstraint *handlerViewL; // @synthesize handlerViewL=_handlerViewL;
@property(retain, nonatomic) NSLayoutConstraint *handlerViewT; // @synthesize handlerViewT=_handlerViewT;
@property(retain, nonatomic) NSMutableArray *shapeButtons; // @synthesize shapeButtons=_shapeButtons;
@property(nonatomic) _Bool movieConstraintClicked; // @synthesize movieConstraintClicked=_movieConstraintClicked;
@property(retain, nonatomic) UIView *handlerView; // @synthesize handlerView=_handlerView;
@property(nonatomic) struct CGRect playerViewFrame; // @synthesize playerViewFrame=_playerViewFrame;
@property(nonatomic) __weak UIView *maskCoverView; // @synthesize maskCoverView=_maskCoverView;
@property(nonatomic) unsigned long long shapeType; // @synthesize shapeType=_shapeType;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)longPressAction:(id)arg1;
- (void)willChangeHandlerShape:(id)arg1;
- (void)updateMask;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)setupMaskView;
- (void)setupHandlerViews;
- (void)setupFeatureViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

