//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "OPPlugin.h"

@class OPOperationLayoutModel, UserSubscb, YKJSONClient;

@interface OPSubscribeTrialPlugin : OPPlugin
{
    OPOperationLayoutModel *_moduleLayout;
    long long _limitPlayTime;
    _Bool _isSubscribed;
    YKJSONClient *_jsonClient;
    UserSubscb *_userSubscbInfo;
}

@property(nonatomic) _Bool isSubscribed; // @synthesize isSubscribed=_isSubscribed;
@property(retain, nonatomic) UserSubscb *userSubscbInfo; // @synthesize userSubscbInfo=_userSubscbInfo;
@property(retain, nonatomic) YKJSONClient *jsonClient; // @synthesize jsonClient=_jsonClient;
- (void).cxx_destruct;
- (void)refreshPlayer:(id)arg1;
- (void)didClickedEvent:(id)arg1;
- (void)removeModuleTask;
- (void)appendModuleTask;
- (void)setupModuleTask;
- (void)playTimeDidChange;
- (void)playSceneDidChange;
- (void)playVideoDidChange;
- (void)playVideoInfoDidPrepare;
- (void)onReceived:(id)arg1;
- (void)onDeInit;
- (void)onRun;
- (void)onInit;
- (void)dealloc;

@end

