//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIView;

@interface PCCardCell : UITableViewCell
{
    UIView *_bottomSeparatorView;
    long long _cellSeparatorStyle;
}

@property(nonatomic) long long cellSeparatorStyle; // @synthesize cellSeparatorStyle=_cellSeparatorStyle;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

