//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSNumber, NSString, UIImage;

@protocol PlayDelegate <NSObject>
@property(retain, nonatomic) NSString *showVThumbUrl;
@property(retain, nonatomic) NSString *showThumbUrl;
@property(retain, nonatomic) NSString *showKind;
@property(retain, nonatomic) NSString *showName;
@property(retain, nonatomic) NSNumber *language;
@property(copy, nonatomic) NSString *show_videostage;
@property(retain, nonatomic) NSNumber *show_videotype;
@property(retain, nonatomic) NSString *videoCategory;
@property(retain, nonatomic) NSNumber *playlistVideoCount;
@property(retain, nonatomic) NSString *playlistid;
@property(retain, nonatomic) NSNumber *needPlayMidAd;
@property(retain, nonatomic) NSDate *lastupdate;
@property(retain, nonatomic) NSNumber *playedSeconds;
@property(retain, nonatomic) NSNumber *totalSeconds;
@property(retain, nonatomic) NSString *sid;
@property(retain, nonatomic) NSString *vid;
@property(retain, nonatomic) UIImage *thumbImage;
@property(retain, nonatomic) NSString *thumbURL;
@property(retain, nonatomic) NSString *title;
- (double)playedTimePercent;
@end

