//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PLMenuBar, UIGestureRecognizer;

@interface PLBaseViewController : UIViewController
{
    PLMenuBar *_menuBar;
    UIGestureRecognizer *_recognizer;
}

@property(retain, nonatomic) UIGestureRecognizer *recognizer; // @synthesize recognizer=_recognizer;
@property(retain, nonatomic) PLMenuBar *menuBar; // @synthesize menuBar=_menuBar;
- (void).cxx_destruct;
- (_Bool)isWantsSwipeBackGesture;
- (void)setWantsSwipeBackGesture:(_Bool)arg1;
- (void)swipeBack;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

