//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PLGBaseRequest.h"

@class NSString, PLGGetLogBizModel<Ignore>;

@interface PLGGetLogsRequest : PLGBaseRequest
{
    PLGGetLogBizModel<Ignore> *_bizModel;
    NSString *_version;
}

@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) PLGGetLogBizModel<Ignore> *bizModel; // @synthesize bizModel=_bizModel;
- (void).cxx_destruct;
- (_Bool)validateParams;
- (id)toDictionary;
- (id)init;

@end

