//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol PLSubscribeDelegate <NSObject>
- (void)triggerSubscribeAction:(_Bool)arg1 forChannel:(NSString *)arg2 avatar:(NSString *)arg3 completion:(void (^)(_Bool))arg4;
- (long long)relationshipOfUser:(NSString *)arg1;
@end

