//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface SegmentBaseModel : NSObject
{
    _Bool _enableBackupURL;
    long long _modelType;
    NSString *_size;
    NSString *_total_milliseconds_video;
    NSString *_total_milliseconds_audio;
    NSString *_secret;
    NSString *_fileid;
    NSString *_cdn_url;
    NSArray *_cdn_backup;
}

@property(retain, nonatomic) NSArray *cdn_backup; // @synthesize cdn_backup=_cdn_backup;
@property(retain, nonatomic) NSString *cdn_url; // @synthesize cdn_url=_cdn_url;
@property(retain, nonatomic) NSString *fileid; // @synthesize fileid=_fileid;
@property(retain, nonatomic) NSString *secret; // @synthesize secret=_secret;
@property(retain, nonatomic) NSString *total_milliseconds_audio; // @synthesize total_milliseconds_audio=_total_milliseconds_audio;
@property(retain, nonatomic) NSString *total_milliseconds_video; // @synthesize total_milliseconds_video=_total_milliseconds_video;
@property(retain, nonatomic) NSString *size; // @synthesize size=_size;
@property(nonatomic) _Bool enableBackupURL; // @synthesize enableBackupURL=_enableBackupURL;
@property(nonatomic) long long modelType; // @synthesize modelType=_modelType;
- (void).cxx_destruct;

@end

