//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class SettingCellView;

@protocol SettingCellViewDelegate
- (void)settingCellViewDidClickCheckBox:(SettingCellView *)arg1;
- (void)settingCellViewDidClickButton:(SettingCellView *)arg1;
- (void)settingCellViewDidClickSwitch:(SettingCellView *)arg1;
- (void)settingCellViewDidClick:(SettingCellView *)arg1;
@end

