//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface SKSelChannelView : UIView
{
    NSString *_title;
    UILabel *_textLabel;
    UIImageView *_downArrow;
}

@property(retain, nonatomic) UIImageView *downArrow; // @synthesize downArrow=_downArrow;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)fitLayout;
- (id)init;

@end

