//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class CALayer, NSArray, NSMutableArray, NSString, UIButton, UIColor, UIFont, UIImageView;

@interface SKSelectView : UIScrollView <UIScrollViewDelegate>
{
    double lastBouncesWidth_;
    _Bool closeMaskAnimation;
    _Bool enableCallBack;
    _Bool _verticalLayout;
    _Bool _showAllItemsInBounds;
    _Bool _scaleItemWhenSelected;
    _Bool _selectViewDefaultToggleState;
    int viewstyle;
    double x_offset;
    NSArray *items;
    long long selectIndex;
    UIColor *maskColor;
    NSMutableArray *textLayers;
    CALayer *maskLayer;
    id <SKSelectViewDelegate> selectViewDelegate;
    UIButton *toggleButton;
    UIImageView *arrowImageView;
    UIColor *textSelectColor;
    UIColor *textColor;
    long long textspan;
    long long _fontSize;
    UIFont *_textFont;
    UIFont *_textFontSelected;
    double _selectedItemScaleFactor;
}

@property(nonatomic) _Bool selectViewDefaultToggleState; // @synthesize selectViewDefaultToggleState=_selectViewDefaultToggleState;
@property(nonatomic) double selectedItemScaleFactor; // @synthesize selectedItemScaleFactor=_selectedItemScaleFactor;
@property(nonatomic) _Bool scaleItemWhenSelected; // @synthesize scaleItemWhenSelected=_scaleItemWhenSelected;
@property(nonatomic) _Bool showAllItemsInBounds; // @synthesize showAllItemsInBounds=_showAllItemsInBounds;
@property(nonatomic) _Bool verticalLayout; // @synthesize verticalLayout=_verticalLayout;
@property(retain, nonatomic) UIFont *textFontSelected; // @synthesize textFontSelected=_textFontSelected;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(nonatomic) long long fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) _Bool enableCallBack; // @synthesize enableCallBack;
@property(nonatomic) long long textspan; // @synthesize textspan;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(retain, nonatomic) UIColor *textSelectColor; // @synthesize textSelectColor;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView;
@property(retain, nonatomic) UIButton *toggleButton; // @synthesize toggleButton;
@property(nonatomic) __weak id <SKSelectViewDelegate> selectViewDelegate; // @synthesize selectViewDelegate;
@property(retain, nonatomic) CALayer *maskLayer; // @synthesize maskLayer;
@property(retain, nonatomic) NSMutableArray *textLayers; // @synthesize textLayers;
@property(retain, nonatomic) UIColor *maskColor; // @synthesize maskColor;
@property(nonatomic) long long selectIndex; // @synthesize selectIndex;
@property(retain, nonatomic) NSArray *items; // @synthesize items;
@property(nonatomic) _Bool closeMaskAnimation; // @synthesize closeMaskAnimation;
@property(nonatomic) double x_offset; // @synthesize x_offset;
@property(nonatomic) int viewstyle; // @synthesize viewstyle;
- (void).cxx_destruct;
- (void)makeFrameOriginPointToIntegerWithView:(id)arg1;
- (void)setHeight:(double)arg1;
- (double)height;
- (void)toggleAction;
- (void)showSelectedMask:(_Bool)arg1;
- (void)adjustArrowDirection;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)reload;
- (void)layoutSublayersOfLayer:(id)arg1;
- (struct CGRect)maskLayerFrameForSelectIndex:(long long)arg1;
- (void)setSelectionWithoutCallback:(long long)arg1;
- (void)refreshTextAndMaskerColor;
- (void)changeStyleToSearchFilter;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

