//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SokuJSONClient, SokuSwitchModel;

@interface SKSwitchManager : NSObject
{
    SokuSwitchModel *_switchModel;
    SokuJSONClient *_sokuJsonClient;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SokuJSONClient *sokuJsonClient; // @synthesize sokuJsonClient=_sokuJsonClient;
@property(retain, nonatomic) SokuSwitchModel *switchModel; // @synthesize switchModel=_switchModel;
- (void).cxx_destruct;
- (_Bool)enablePreload;
- (_Bool)mtopOpen;
- (_Bool)openAdvertBackground;
- (_Bool)rankSwitch;
- (_Bool)unlikeSwitch;
- (long long)getFeedBackPage;
- (_Bool)evokeLog;
- (void)requestSwitchDatas;

@end

