//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface SKTextRectViewB : UIView
{
    long long _tag_type;
    UILabel *_myLab;
    UIImageView *_rIMV;
}

@property(retain, nonatomic) UIImageView *rIMV; // @synthesize rIMV=_rIMV;
@property(retain, nonatomic) UILabel *myLab; // @synthesize myLab=_myLab;
@property(nonatomic) long long tag_type; // @synthesize tag_type=_tag_type;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

