//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class SKBaseLoadingView, SokuJSONClient, UIScreenEdgePanGestureRecognizer;

@interface SKUIBaseViewController : UIViewController
{
    SKBaseLoadingView *_loadingView;
    SokuJSONClient *_jsonClient;
    UIScreenEdgePanGestureRecognizer *_recognizer;
}

@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *recognizer; // @synthesize recognizer=_recognizer;
@property(retain, nonatomic) SokuJSONClient *jsonClient; // @synthesize jsonClient=_jsonClient;
- (void).cxx_destruct;
- (void)stopAnimationg;
- (void)startAnimating;
- (void)extraDealloc;
- (void)dealloc;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)swipeBackWithSender:(id)arg1;
- (void)loadView;
- (id)init;

@end

