//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView;

@interface SoonFilmCoverView : UIView
{
    UIView *_backView;
    UIImageView *_coverImageView;
    UIButton *_knowButton;
}

@property(retain, nonatomic) UIButton *knowButton; // @synthesize knowButton=_knowButton;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
- (void).cxx_destruct;
- (void)hide;
- (void)show;
- (void)showInView:(id)arg1;
- (void)know:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

