//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, STEffectsAudioPlayer;

@protocol STEffectsAudioPlayerDelegate <NSObject>
- (void)audioPlayerDidFinishPlaying:(STEffectsAudioPlayer *)arg1 successfully:(_Bool)arg2 name:(NSString *)arg3;
@end

