//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TBPLBaseTriggerService.h"

@class TBPopLayerTrackingService;

@interface TBPLViewTriggerService : TBPLBaseTriggerService
{
    TBPopLayerTrackingService *_trackingService;
}

@property(retain, nonatomic) TBPopLayerTrackingService *trackingService; // @synthesize trackingService=_trackingService;
- (void).cxx_destruct;
- (id)createTrackingServiceForVCIfNeeded:(id)arg1;
- (id)createTrackingServiceForMasterLayerIfNeeded:(id)arg1;
- (id)getTrackingServiceForMasterLayer:(id)arg1;
- (id)getTrackingServiceForOperation:(id)arg1;
- (void)cancelOperations:(id)arg1;
- (void)operateTrackingViewWithMasterLayer:(id)arg1 trackingViewOperationModel:(id)arg2;
- (void)handleTaskOperateWithMasterLayer:(id)arg1 handleTaskModel:(id)arg2;
- (void)selectAndOperateWithMasterLayer:(id)arg1 config:(id)arg2;
- (void)removeMsg:(id)arg1 hostView:(id)arg2;
- (void)acceptMsg:(id)arg1 param:(id)arg2 hostView:(id)arg3;
- (void)onConfigChanged;
- (void)openValidConfigs:(id)arg1 forEvent:(id)arg2;
- (void)fireEvent:(id)arg1;
- (void)reachNextPage:(id)arg1;
- (void)leavePreviousPage;
- (long long)getDomain;
- (id)initWithConfigCenter:(id)arg1;
- (void)swizzedPopLayerViewReceiveCloseActionWithPopRequest:(id)arg1 attachVC:(id)arg2;
- (void)swizzedOnReady:(id)arg1;
- (void)swizzedOnConfigChanged;
- (void)swizzedOpenValidConfigs:(id)arg1 forEvent:(id)arg2;
- (void)swizzPopLayerStatus:(_Bool)arg1;
- (void)outputText:(id)arg1;

@end

