//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBSDKPushCenterUserTrackEngine : NSObject
{
}

+ (void)uploadAgooPoint:(id)arg1 withStatus:(id)arg2 withErrorCode:(id)arg3 withExt:(id)arg4;
+ (void)uploadAgooPoint:(id)arg1 MsgStatus:(id)arg2;
+ (void)userTrackForReceivePushWithAPS:(id)arg1;
+ (void)activating;

@end

