//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TDNetworkDoctor : NSObject
{
}

+ (id)getIPWithHostName:(id)arg1;
+ (id)getHttpDNSResultLog;
+ (void)getNetworkFullTestResult:(CDUnknownBlockType)arg1;
+ (void)getNetworkTestResult:(CDUnknownBlockType)arg1;

@end

