//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, TimeTrackPoint;

@interface TimeTrackPointData : NSObject
{
    NSArray *_points;
    TimeTrackPoint *_headPoint;
    TimeTrackPoint *_tailPoint;
}

@property(nonatomic) __weak TimeTrackPoint *tailPoint; // @synthesize tailPoint=_tailPoint;
@property(nonatomic) __weak TimeTrackPoint *headPoint; // @synthesize headPoint=_headPoint;
@property(retain, nonatomic) NSArray *points; // @synthesize points=_points;
- (void).cxx_destruct;

@end

