//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "APPPostBaseCell.h"

@class NSString, TTFCustomButton, TTFRepliesPageViewModel, UIButton, UIImageView, UILabel;

@interface TTFPageTableViewCell : APPPostBaseCell
{
    _Bool _isPositiveSequence;
    _Bool _needRefresh;
    NSString *_totalCount;
    NSString *_headline;
    UILabel *_refreshIcon;
    UIImageView *_headerMarkImageView;
    UILabel *_statementLabel;
    UILabel *_numberLabel;
    TTFCustomButton *_sortButton;
    UIImageView *_sortImageView;
    UILabel *_sortLabel;
    UIButton *_refreshButton;
    UILabel *_refreshLabel;
}

+ (double)caculateCellHeight;
@property(retain, nonatomic) UILabel *refreshLabel; // @synthesize refreshLabel=_refreshLabel;
@property(retain, nonatomic) UIButton *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) UILabel *sortLabel; // @synthesize sortLabel=_sortLabel;
@property(retain, nonatomic) UIImageView *sortImageView; // @synthesize sortImageView=_sortImageView;
@property(retain, nonatomic) TTFCustomButton *sortButton; // @synthesize sortButton=_sortButton;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(retain, nonatomic) UILabel *statementLabel; // @synthesize statementLabel=_statementLabel;
@property(retain, nonatomic) UIImageView *headerMarkImageView; // @synthesize headerMarkImageView=_headerMarkImageView;
@property(nonatomic) _Bool needRefresh; // @synthesize needRefresh=_needRefresh;
@property(retain, nonatomic) UILabel *refreshIcon; // @synthesize refreshIcon=_refreshIcon;
@property(retain, nonatomic) NSString *headline; // @synthesize headline=_headline;
@property(retain, nonatomic) NSString *totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) _Bool isPositiveSequence; // @synthesize isPositiveSequence=_isPositiveSequence;
- (void).cxx_destruct;
- (void)bindViewModel:(id)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)refreshTouched:(id)arg1;
- (void)sortTouched:(id)arg1;

// Remaining properties
@property(nonatomic) __weak id <TTFPageTableViewCellDelegate> delegate; // @dynamic delegate;
@property(retain, nonatomic) TTFRepliesPageViewModel *viewModel; // @dynamic viewModel;

@end

