//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, TTFCommunityBlacklistService;

@interface TTFUserBlackListViewModel : NSObject
{
    _Bool _blocking;
    _Bool _canBeBlocking;
    _Bool _intrinsicBlocking;
    NSString *_text;
    NSString *_completionTip;
    long long _userID;
    long long _fandomID;
    TTFCommunityBlacklistService *_blacklistService;
}

@property(retain, nonatomic) TTFCommunityBlacklistService *blacklistService; // @synthesize blacklistService=_blacklistService;
@property(nonatomic) _Bool intrinsicBlocking; // @synthesize intrinsicBlocking=_intrinsicBlocking;
@property(nonatomic) long long fandomID; // @synthesize fandomID=_fandomID;
@property(nonatomic) long long userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSString *completionTip; // @synthesize completionTip=_completionTip;
@property(nonatomic) _Bool canBeBlocking; // @synthesize canBeBlocking=_canBeBlocking;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) _Bool blocking; // @synthesize blocking=_blocking;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *operationTip;
- (void)changeValueForObserving;
- (void)setupTextDescription;
- (id)initWithUserID:(long long)arg1 withFandomID:(long long)arg2 initWithBlocking:(_Bool)arg3;

@end

