//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YKFCommunityContentMgmtServiceInformPostAPI, YKFCommunityContentMgmtServiceInformReplyAPI, YKFCommunityFandomMgmtServiceListInformReasonsAPI, YKFCommunitySelectOptionListPO;

@interface TTPCommunityInformListService : NSObject
{
    YKFCommunityContentMgmtServiceInformReplyAPI *_informReplyApi;
    YKFCommunityContentMgmtServiceInformPostAPI *_informPostApi;
    YKFCommunityFandomMgmtServiceListInformReasonsAPI *_informReasonApi;
    YKFCommunitySelectOptionListPO *_informReason;
}

@property(retain, nonatomic) YKFCommunitySelectOptionListPO *informReason; // @synthesize informReason=_informReason;
@property(retain, nonatomic) YKFCommunityFandomMgmtServiceListInformReasonsAPI *informReasonApi; // @synthesize informReasonApi=_informReasonApi;
@property(retain, nonatomic) YKFCommunityContentMgmtServiceInformPostAPI *informPostApi; // @synthesize informPostApi=_informPostApi;
@property(retain, nonatomic) YKFCommunityContentMgmtServiceInformReplyAPI *informReplyApi; // @synthesize informReplyApi=_informReplyApi;
- (void).cxx_destruct;
- (void)fetchCommunityInformReasonListWithComplete:(CDUnknownBlockType)arg1;
- (void)sendCommunityInformItemWithPostId:(long long)arg1 fandomId:(long long)arg2 reason:(long long)arg3 complete:(CDUnknownBlockType)arg4;
- (void)sendCommunityInformItemWithReplyId:(long long)arg1 fandomId:(long long)arg2 reason:(long long)arg3 complete:(CDUnknownBlockType)arg4;

@end

