//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIImageView, UILabel;

@interface UICardCellView : UIView
{
    id _cardData;
    NSString *_playShowId;
    UIImageView *_imageView;
    UILabel *_label;
    UIImageView *_lastplayView;
    UIImageView *_markView;
    UILabel *_markTitleView;
}

@property(retain, nonatomic) UILabel *markTitleView; // @synthesize markTitleView=_markTitleView;
@property(retain, nonatomic) UIImageView *markView; // @synthesize markView=_markView;
@property(retain, nonatomic) UIImageView *lastplayView; // @synthesize lastplayView=_lastplayView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSString *playShowId; // @synthesize playShowId=_playShowId;
@property(retain, nonatomic) id cardData; // @synthesize cardData=_cardData;
- (void).cxx_destruct;
- (void)setCommonCardData:(id)arg1;
- (void)setCommonCardData:(id)arg1 isShowSeq:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

