//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (HYHexadecimal)
+ (id)hy_colorWithHexString:(id)arg1 alpha:(double)arg2;
+ (id)hy_colorWithHexString:(id)arg1;
+ (id)hy_colorWithHexadecimalValue:(unsigned long long)arg1 alpha:(double)arg2;
+ (id)hy_colorWithHexadecimalValue:(unsigned long long)arg1;
+ (id)hy_colorWithARGBDecimalValue:(unsigned long long)arg1;
@end

