//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (LTMUIImageAlphaAdditions)
- (struct CGImage *)ltm_newBorderMask:(unsigned long long)arg1 size:(struct CGSize)arg2;
- (id)ltm_transparentBorderImage:(unsigned long long)arg1;
- (id)ltm_imageWithAlpha;
- (_Bool)ltm_hasAlpha;
@end

