//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface UIImageView (CMSService)
- (void)cms_setImageWithURLString:(id)arg1 placeholderImage:(id)arg2 module:(id)arg3 imageSize:(struct CGSize)arg4 parameters:(id)arg5 completed:(CDUnknownBlockType)arg6;
@end

