//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (LS_Statistics)
- (void)setIsSpmActivated:(unsigned char)arg1;
- (unsigned char)isSpmActivated;
- (void)setSpmPage:(id)arg1;
- (id)spmPage;
@property(nonatomic) long long spmSection;
@property(nonatomic) long long spmRow;
@end

