//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (LS_AddChild)
- (void)ls_cycleFromViewController:(id)arg1 toViewController:(id)arg2 withFrame:(struct CGRect)arg3;
- (void)ls_cycleFromViewController:(id)arg1 toViewController:(id)arg2;
- (void)ls_hideContentController:(id)arg1;
- (void)ls_displayContentController:(id)arg1;
- (void)ls_displayContentController:(id)arg1 withFrame:(struct CGRect)arg2;
@end

