//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (LS_Frame)
@property(nonatomic) double ls_centerX;
@property(nonatomic) double ls_centerY;
@property(nonatomic) double ls_h;
@property(nonatomic) double ls_w;
@property(nonatomic) double ls_y;
@property(nonatomic) double ls_x;
@end

