//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UploadVideoThumbnailModel : NSObject
{
    _Bool _isCustomCover;
    long long _seq;
    long long _is_cover;
    NSString *_big_url;
    NSString *_small_url;
    NSString *_url;
}

@property(nonatomic) _Bool isCustomCover; // @synthesize isCustomCover=_isCustomCover;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *small_url; // @synthesize small_url=_small_url;
@property(retain, nonatomic) NSString *big_url; // @synthesize big_url=_big_url;
@property(nonatomic) long long is_cover; // @synthesize is_cover=_is_cover;
@property(nonatomic) long long seq; // @synthesize seq=_seq;
- (void).cxx_destruct;

@end

