//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VICAdapterInfo : NSObject
{
    id _adapter;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) id adapter; // @synthesize adapter=_adapter;
- (void).cxx_destruct;
- (id)adapterInstance;

@end

