//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class VICContainer;

@interface VICContainerSubModule : NSObject
{
    VICContainer *_container;
}

@property(nonatomic) __weak VICContainer *container; // @synthesize container=_container;
- (void).cxx_destruct;
- (id)initWithContainer:(id)arg1;

@end

