//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VICContainerSubModule.h"

@class VICDataManagerConfiguration, VICInteractionData;

@interface VICDataManager : VICContainerSubModule
{
    _Bool _stopAllOperations;
    int _retriedCount;
    id <VICHttpRequestProtocol> _httpRequestAdapter;
    VICInteractionData *_interactionData;
    VICDataManagerConfiguration *_configuraion;
}

@property(nonatomic) int retriedCount; // @synthesize retriedCount=_retriedCount;
@property(retain, nonatomic) VICDataManagerConfiguration *configuraion; // @synthesize configuraion=_configuraion;
@property(retain, nonatomic) VICInteractionData *interactionData; // @synthesize interactionData=_interactionData;
@property(retain, nonatomic) id <VICHttpRequestProtocol> httpRequestAdapter; // @synthesize httpRequestAdapter=_httpRequestAdapter;
- (void).cxx_destruct;
- (void)cleanLocalCache;
- (void)flushMemory;
- (id)getInteractionData;
- (id)pluginsWillUnload:(float)arg1 screenMode:(unsigned long long)arg2;
- (id)pluginsWillLoad:(float)arg1 screenMode:(unsigned long long)arg2;
- (_Bool)isScriptInBlackList:(id)arg1;
- (unsigned long long)mutextStrategy;
- (_Bool)canLoadStage:(id)arg1;
- (id)scriptWithId:(long long)arg1;
- (id)stageWithId:(long long)arg1;
- (void)downloadImageWithUrl:(id)arg1;
- (void)preload;
- (void)storeInteractionData:(id)arg1;
- (id)deviceContext;
- (void)stopAllOperations;
- (void)retryFetchInteractionData;
- (void)fetchInteractionData;
- (_Bool)isNetworkAvailable;

@end

