//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKTableViewCell.h"

@class SKVideoView, UITextView, ViewTypeBBigSpreadModel;

@interface ViewTypeBBigSpreadCell : SKTableViewCell
{
    ViewTypeBBigSpreadModel *_pModel;
    SKVideoView *_videoView;
    UITextView *_testView;
}

+ (float)getCellHeightWithModel:(id)arg1;
@property(retain, nonatomic) UITextView *testView; // @synthesize testView=_testView;
@property(retain, nonatomic) SKVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) ViewTypeBBigSpreadModel *pModel; // @synthesize pModel=_pModel;
- (void).cxx_destruct;
- (void)setUpTestView;
- (void)hideTestView;
- (void)sendClickLogWith_dType:(int)arg1;
- (void)jumpSpread_dType:(int)arg1;
- (void)setData:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

