//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SKTableViewCell.h"

@class SKEmergencyTextView, SKVideoView, UIImageView, UILabel, UIView, ViewTypeBEmergencyModel;

@interface ViewTypeBEmergencyCell : SKTableViewCell
{
    ViewTypeBEmergencyModel *_emergencyModel;
    UIImageView *_playIcon;
    SKVideoView *_videoView;
    SKEmergencyTextView *_text1;
    SKEmergencyTextView *_text2;
    UIView *_seperator;
    UILabel *_publish_timeLabel;
    UILabel *_titleLabel;
    UIImageView *_titleBgView;
}

+ (float)getCellHeight:(id)arg1;
@property(retain, nonatomic) UIImageView *titleBgView; // @synthesize titleBgView=_titleBgView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *publish_timeLabel; // @synthesize publish_timeLabel=_publish_timeLabel;
@property(retain, nonatomic) UIView *seperator; // @synthesize seperator=_seperator;
@property(retain, nonatomic) SKEmergencyTextView *text2; // @synthesize text2=_text2;
@property(retain, nonatomic) SKEmergencyTextView *text1; // @synthesize text1=_text1;
@property(retain, nonatomic) SKVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) UIImageView *playIcon; // @synthesize playIcon=_playIcon;
@property(retain, nonatomic) ViewTypeBEmergencyModel *emergencyModel; // @synthesize emergencyModel=_emergencyModel;
- (void).cxx_destruct;
- (id)getCellExposureDic:(id)arg1;
- (id)getKString:(id)arg1;
- (_Bool)didSentExpo:(id)arg1;
- (id)getCellExposureDicWithIsFirstLast:(_Bool)arg1 andTablview:(id)arg2;
- (void)setData:(id)arg1;
- (void)cellClicked:(int)arg1 model:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

