//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VIP_HomePageNewStatistical : NSObject
{
}

+ (void)touchVideoEventName:(id)arg1 inPage:(id)arg2 withTarget:(id)arg3 withRefercode:(id)arg4 withExtend:(id)arg5;
+ (void)vipCenterStatisticalControlName:(id)arg1 withSpm:(id)arg2 withExtend:(id)arg3;

@end

