//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VIP_HomePageStatistical : NSObject
{
}

+ (void)homePageStatistcalPrevue:(_Bool)arg1 title:(id)arg2;
+ (void)homePageTouchHeader:(_Bool)arg1;
+ (void)userLoginSucessStatistical;

@end

