//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSMutableDictionary, NSString, VIPARChannelManager, VIPARIdentifierItem, VIPARIdentifierModel, YKARLocalRecModel;

@interface VIPARResourceDispatcher : NSObject
{
    CDUnknownBlockType _timeoutBlock;
    CDUnknownBlockType _configBlock;
    NSString *_currentARActivityId;
    NSString *_currentARActivityUrl;
    long long _configState;
    VIPARIdentifierModel *_identifierModel;
    VIPARChannelManager *_channelManager;
    CDUnknownBlockType _handler;
    YKARLocalRecModel *_recModel;
    long long _activeHandleItem;
    NSMutableDictionary *_recFlyout;
    NSMutableDictionary *_dispatchFlyout;
    NSDictionary *_activityFlyout;
    NSDate *_channelDate;
    NSDate *_identifierDate;
    NSDate *_zipDate;
}

+ (_Bool)resourceExisted:(id)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSDate *zipDate; // @synthesize zipDate=_zipDate;
@property(retain, nonatomic) NSDate *identifierDate; // @synthesize identifierDate=_identifierDate;
@property(retain, nonatomic) NSDate *channelDate; // @synthesize channelDate=_channelDate;
@property(retain, nonatomic) NSDictionary *activityFlyout; // @synthesize activityFlyout=_activityFlyout;
@property(retain, nonatomic) NSMutableDictionary *dispatchFlyout; // @synthesize dispatchFlyout=_dispatchFlyout;
@property(retain, nonatomic) NSMutableDictionary *recFlyout; // @synthesize recFlyout=_recFlyout;
@property(nonatomic) long long activeHandleItem; // @synthesize activeHandleItem=_activeHandleItem;
@property(retain, nonatomic) YKARLocalRecModel *recModel; // @synthesize recModel=_recModel;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) VIPARChannelManager *channelManager; // @synthesize channelManager=_channelManager;
@property(retain, nonatomic) VIPARIdentifierModel *identifierModel; // @synthesize identifierModel=_identifierModel;
@property(nonatomic) long long configState; // @synthesize configState=_configState;
@property(retain, nonatomic) NSString *currentARActivityUrl; // @synthesize currentARActivityUrl=_currentARActivityUrl;
@property(retain, nonatomic) NSString *currentARActivityId; // @synthesize currentARActivityId=_currentARActivityId;
@property(copy, nonatomic) CDUnknownBlockType configBlock; // @synthesize configBlock=_configBlock;
@property(copy, nonatomic) CDUnknownBlockType timeoutBlock; // @synthesize timeoutBlock=_timeoutBlock;
- (void).cxx_destruct;
- (_Bool)checkLocalARResource;
@property(nonatomic) long long dispatchState;
- (void)trimInvalidFiles:(id)arg1;
- (void)handleUnZip:(id)arg1;
- (void)pickARResourceWithResourceId:(id)arg1 resourceUrl:(id)arg2 timeoutBlock:(CDUnknownBlockType)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)pickARResourceWithIdentifierItem:(id)arg1;
- (void)handleResourceDownload:(id)arg1;
- (void)dispatchARResourceWithDispatchHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) VIPARIdentifierItem *currentIdentItem;
- (id)recModelWithResourceId:(id)arg1;
- (id)init;
- (_Bool)activityShouldAutoJumtp:(id)arg1 jumpDuration:(out id *)arg2;
- (id)activityUrlWithTarget:(id)arg1;
- (id)animationUrlWithTarget:(id)arg1;
- (void)loadActivityConfig;
@property(readonly, nonatomic) NSString *confidenceVal;
@property(readonly, nonatomic) NSString *numberAICount;

@end

