//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VIPMyReservationRequestModel : NSObject
{
}

+ (void)myReservationRequestType:(long long)arg1 state:(long long)arg2 pl:(long long)arg3 pn:(long long)arg4 sucess:(CDUnknownBlockType)arg5 failture:(CDUnknownBlockType)arg6;

@end

