//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, VIPCMSAction;

@interface VIPNCPrizeModel : NSObject
{
    NSString *_title;
    VIPCMSAction *_action;
    NSArray *_contentsArr;
}

@property(retain, nonatomic) NSArray *contentsArr; // @synthesize contentsArr=_contentsArr;
@property(retain, nonatomic) VIPCMSAction *action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithInfo:(id)arg1;

@end

