//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, VIPNCBuyBtnModel;

@interface VIPNCMemberInfoModel : NSObject
{
    _Bool _valid;
    NSString *_bg_image;
    NSString *_exptime;
    NSString *_icon;
    long long _member_id;
    NSString *_member_name;
    NSString *_starttime;
    NSString *_title1;
    NSString *_title2;
    VIPNCBuyBtnModel *_btnModel;
}

@property(retain, nonatomic) VIPNCBuyBtnModel *btnModel; // @synthesize btnModel=_btnModel;
@property(nonatomic) _Bool valid; // @synthesize valid=_valid;
@property(retain, nonatomic) NSString *title2; // @synthesize title2=_title2;
@property(retain, nonatomic) NSString *title1; // @synthesize title1=_title1;
@property(retain, nonatomic) NSString *starttime; // @synthesize starttime=_starttime;
@property(retain, nonatomic) NSString *member_name; // @synthesize member_name=_member_name;
@property(nonatomic) long long member_id; // @synthesize member_id=_member_id;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *exptime; // @synthesize exptime=_exptime;
@property(retain, nonatomic) NSString *bg_image; // @synthesize bg_image=_bg_image;
- (void).cxx_destruct;
- (id)initWithInfo:(id)arg1;

@end

