//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage, VIPRankHeadItemView;

@interface VIPRankingHeaderView : UIView
{
    UIImage *_blurImage;
    CDUnknownBlockType _loadImage;
    CDUnknownBlockType _jumpToPlayVideo;
    VIPRankHeadItemView *_leftView;
    VIPRankHeadItemView *_centerView;
    VIPRankHeadItemView *_rightView;
}

@property(retain, nonatomic) VIPRankHeadItemView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) VIPRankHeadItemView *centerView; // @synthesize centerView=_centerView;
@property(retain, nonatomic) VIPRankHeadItemView *leftView; // @synthesize leftView=_leftView;
@property(copy, nonatomic) CDUnknownBlockType jumpToPlayVideo; // @synthesize jumpToPlayVideo=_jumpToPlayVideo;
@property(copy, nonatomic) CDUnknownBlockType loadImage; // @synthesize loadImage=_loadImage;
@property(retain, nonatomic) UIImage *blurImage; // @synthesize blurImage=_blurImage;
- (void).cxx_destruct;
- (void)jumpToPlayDetail:(id)arg1;
- (void)setLeftModel:(id)arg1 centerModel:(id)arg2 rightModel:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

