//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VIPCMSCardVideo.h"

@class NSString;

@interface VIPVHCMSCardVideo : VIPCMSCardVideo
{
    NSString *_imageHorizontalPath;
}

@property(copy, nonatomic) NSString *imageHorizontalPath; // @synthesize imageHorizontalPath=_imageHorizontalPath;
- (void).cxx_destruct;
- (_Bool)setupWithCMSInfo:(id)arg1;

@end

