//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKWebView.h"

@interface WKWebView (PSDWKWebView)
- (void)psdSetupPostMessageChannel;
- (void)psdSyncMainProcessCookie;
- (void)psdSyncDeviceCookieWithStorage:(id)arg1;
- (void)psdSyncSimulatorCookieWithStorage:(id)arg1;
- (void)psdHandleWKCookie;
- (void)psdSetupMessageHandler;
- (id)psdInitWithFrame:(struct CGRect)arg1 configuration:(id)arg2;
@end

