//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WMBJSONKit : NSObject
{
}

+ (id)JSONObjectWithString:(id)arg1;
+ (id)JSONObjectWithData:(id)arg1;
+ (id)stringWithJSONObject:(id)arg1;
+ (id)dataWithJSONObject:(id)arg1;

@end

