//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol WVH5ActionDelegate <NSObject>
- (void)shareResult:(long long)arg1 platformID:(long long)arg2;
- (void)updateSharePannelStatus:(_Bool)arg1;
- (void)openH5WithActionModel;
- (void)webViewEvaluateJavaScript:(NSString *)arg1 completionHandler:(void (^)(id, NSError *))arg2;
- (void)webViewSetLoginRefreshURLString:(NSString *)arg1;
- (void)webViewReload:(NSString *)arg1;
- (_Bool)webViewDelegateRespondsToRequireHalfScreenClose;
- (void)webViewDelegateRequireHalfScreenClose;
- (_Bool)isRespondsToOpenH5WithURLString;
- (_Bool)webViewDelegateRespondsToRequireClose;
- (void)webViewDelegateRequireClose;
@end

