//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WVDynamicHandler.h"

@interface WVYoukuAccountJSBridge : WVDynamicHandler
{
}

+ (id)buildSuccessDictWithContent:(id)arg1;
+ (id)defaultSuccess;
+ (id)parameterError;
+ (void)handleError:(id)arg1 withContent:(id)arg2;
+ (id)buildDictWithResultCode:(long long)arg1 resultMsg:(id)arg2;
+ (void)getUnionToken:(id)arg1 withWVBridgeContext:(id)arg2;
+ (_Bool)checkValidParams:(id)arg1;
+ (id)getPlatformWithParams:(id)arg1;
+ (id)getAnalyticsDataWithParams:(id)arg1;
+ (id)getRootViewControllerwithContent:(id)arg1;
+ (void)unbindThirdAccount:(id)arg1 withWVBridgeContext:(id)arg2;
+ (void)bindThirdAccount:(id)arg1 withWVBridgeContext:(id)arg2;
+ (void)queryThirdBindStatus:(id)arg1 withWVBridgeContext:(id)arg2;

@end

