//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface WXRecycleListDiffResult : NSObject
{
    NSMutableSet *_deleteIndexPaths;
    NSMutableSet *_insertIndexPaths;
    NSMutableSet *_reloadIndexPaths;
}

@property(readonly, nonatomic) NSMutableSet *reloadIndexPaths; // @synthesize reloadIndexPaths=_reloadIndexPaths;
@property(readonly, nonatomic) NSMutableSet *insertIndexPaths; // @synthesize insertIndexPaths=_insertIndexPaths;
@property(readonly, nonatomic) NSMutableSet *deleteIndexPaths; // @synthesize deleteIndexPaths=_deleteIndexPaths;
- (void).cxx_destruct;
- (id)description;
- (_Bool)hasChanges;
- (id)initWithInsertIndexPaths:(id)arg1 deleteIndexPaths:(id)arg2 reloadIndexPaths:(id)arg3;

@end

