//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "YKBarrageInteractBubbleViewDelegate.h"
#import "YKBarrageViewActionDelegate.h"
#import "YKBarrageViewItem.h"

@class NSMutableArray, NSNumber, NSString, UIImageView, UIView<YKBarrageViewProtocol>, YKBarrageInteractBubbleView, YKBarrageRenderEngine;

@interface YKBarrageDisplayView : UIView <YKBarrageInteractBubbleViewDelegate, YKBarrageViewItem, YKBarrageViewActionDelegate>
{
    CDUnknownBlockType _requestShareInfo;
    NSString *_videoId;
    YKBarrageRenderEngine *_renderEngine;
    NSMutableArray *_pausedBarrageViews;
    NSNumber *_pausedDate;
    YKBarrageInteractBubbleView *_interactView;
    UIView<YKBarrageViewProtocol> *_targetView;
    UIImageView *_imageView;
}

@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) __weak UIView<YKBarrageViewProtocol> *targetView; // @synthesize targetView=_targetView;
@property(retain, nonatomic) YKBarrageInteractBubbleView *interactView; // @synthesize interactView=_interactView;
@property(retain, nonatomic) NSNumber *pausedDate; // @synthesize pausedDate=_pausedDate;
@property(retain, nonatomic) NSMutableArray *pausedBarrageViews; // @synthesize pausedBarrageViews=_pausedBarrageViews;
@property(retain, nonatomic) YKBarrageRenderEngine *renderEngine; // @synthesize renderEngine=_renderEngine;
@property(retain, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(copy, nonatomic) CDUnknownBlockType requestShareInfo; // @synthesize requestShareInfo=_requestShareInfo;
- (void).cxx_destruct;
- (void)notifyDensityChangeTo:(long long)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)timeoutToDisplayBubble;
- (void)shareDMWithBarrage:(id)arg1 Others:(id)arg2 userID:(id)arg3;
- (void)shareDMAction:(id)arg1;
- (void)userDidInteractByActionType:(long long)arg1;
- (void)showInteractViewForBarrageView:(id)arg1 tapAtPoint:(struct CGPoint)arg2;
- (void)endInteracting;
- (void)beginInteractingOnView:(id)arg1;
- (void)dealloc;
- (void)resumeAnimation;
- (void)pauseAnimation;
- (id)displayingBarrageContents;
- (id)displayingBarrageArray;
- (_Bool)checkIsBarrageView:(id)arg1;
- (void)displayBarrages:(id)arg1;
- (void)relayoutWhenScreenChanged;
- (void)relayout;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

