//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YKBarrageManager;

@interface YKBarrageRouter : NSObject
{
    YKBarrageManager *_manager;
}

+ (void)triggerLoginCompletion:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
@property(nonatomic) __weak YKBarrageManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)postMessage:(id)arg1;
- (void)showSimpleInputViewWithParams:(id)arg1 needLogin:(_Bool)arg2 complete:(CDUnknownBlockType)arg3;
- (void)reportBarrage:(id)arg1;
- (id)paramStringWithArray:(id)arg1;
- (void)openDanmuPoolList;
- (id)danmuPoolURLString;
- (void)requestHotWordsListWithCompletion:(CDUnknownBlockType)arg1;
- (void)routeWithOpenHalfScreenUrl:(id)arg1;
- (void)routeWithUserActionModel:(id)arg1;
- (void)userDidReplyUserBarrage:(id)arg1;
- (void)userDidDisagreeUserBarrage:(id)arg1;
- (void)userDidLikeUserBarrage:(id)arg1;
- (void)starDidLikeUserBarrage:(id)arg1;
- (void)didClickSystemBarrage:(id)arg1;
- (void)didShowSystemBarrage:(id)arg1;

@end

