//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKBarrageBaseResponse.h"

@class NSDictionary;

@interface YKBarrageFetchUserRolesResponse : YKBarrageBaseResponse
{
    double _fetchInterval;
    NSDictionary *_taskRolesDict;
}

@property(retain, nonatomic) NSDictionary *taskRolesDict; // @synthesize taskRolesDict=_taskRolesDict;
@property(nonatomic) double fetchInterval; // @synthesize fetchInterval=_fetchInterval;
- (void).cxx_destruct;
- (void)parseTaskRolesFromArray:(id)arg1;
- (void)mergeFromJSON:(id)arg1;

@end

