//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YKPLHttpsConfigManagerDelegate.h"

@class AVFSSQLiteCache, NSDictionary, NSString, YKPLHttpsConfigManager;

@interface YKBaseConfigCenter : NSObject <YKPLHttpsConfigManagerDelegate>
{
    _Bool _isMock;
    NSString *_groupName;
    YKPLHttpsConfigManager *_httpsManager;
    AVFSSQLiteCache *_sqlCache;
    NSDictionary *_mockConfig;
    NSString *_arriveScm;
    struct _opaque_pthread_mutex_t _lock;
}

@property(copy, nonatomic) NSString *arriveScm; // @synthesize arriveScm=_arriveScm;
@property(retain, nonatomic) NSDictionary *mockConfig; // @synthesize mockConfig=_mockConfig;
@property(nonatomic) _Bool isMock; // @synthesize isMock=_isMock;
@property(nonatomic) struct _opaque_pthread_mutex_t lock; // @synthesize lock=_lock;
@property(retain, nonatomic) AVFSSQLiteCache *sqlCache; // @synthesize sqlCache=_sqlCache;
@property(retain, nonatomic) YKPLHttpsConfigManager *httpsManager; // @synthesize httpsManager=_httpsManager;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
- (void).cxx_destruct;
- (void)saveArriveScm:(id)arg1;
- (id)cacheKey;
- (id)currentTimeStamp;
- (void)startMockWithConfig:(id)arg1;
- (void)useConfigSucceedWithType:(id)arg1;
- (id)getConfigByKey:(id)arg1;
- (void)configDidChanged;
- (id)configCache;
- (void)setConfigCache:(id)arg1;
- (void)updateCacheConfigWithConfig:(id)arg1 type:(id)arg2;
- (void)intializeCacheConfig;
- (void)manager:(id)arg1 didUpdateConfig:(id)arg2 type:(unsigned long long)arg3 from:(unsigned long long)arg4;
- (_Bool)managerShouldUpdateCDNConfig;
- (void)startLoad;
- (void)dealloc;
- (id)initWithGroupName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

