//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UINavigationController, YKBCUser;

@interface YKBCCallback : NSObject
{
    CDUnknownBlockType _openWebviewBlock;
    CDUnknownBlockType _tipsDirectBlock;
    CDUnknownBlockType _playVideoBlock;
    CDUnknownBlockType _loginBlock;
    CDUnknownBlockType _currentUserBlock;
    CDUnknownBlockType _initBaichuanBlock;
    CDUnknownBlockType _paymentNewUserRequestBlock;
    CDUnknownBlockType _closeGiveScoreViewBlock;
    UINavigationController *_containerController;
    YKBCUser *_user;
}

@property(retain, nonatomic) YKBCUser *user; // @synthesize user=_user;
@property(nonatomic) __weak UINavigationController *containerController; // @synthesize containerController=_containerController;
@property(copy, nonatomic) CDUnknownBlockType closeGiveScoreViewBlock; // @synthesize closeGiveScoreViewBlock=_closeGiveScoreViewBlock;
@property(copy, nonatomic) CDUnknownBlockType paymentNewUserRequestBlock; // @synthesize paymentNewUserRequestBlock=_paymentNewUserRequestBlock;
@property(copy, nonatomic) CDUnknownBlockType initBaichuanBlock; // @synthesize initBaichuanBlock=_initBaichuanBlock;
@property(copy, nonatomic) CDUnknownBlockType currentUserBlock; // @synthesize currentUserBlock=_currentUserBlock;
@property(copy, nonatomic) CDUnknownBlockType loginBlock; // @synthesize loginBlock=_loginBlock;
@property(copy, nonatomic) CDUnknownBlockType playVideoBlock; // @synthesize playVideoBlock=_playVideoBlock;
@property(copy, nonatomic) CDUnknownBlockType tipsDirectBlock; // @synthesize tipsDirectBlock=_tipsDirectBlock;
@property(copy, nonatomic) CDUnknownBlockType openWebviewBlock; // @synthesize openWebviewBlock=_openWebviewBlock;
- (void).cxx_destruct;

@end

