//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CLZoomPickerViewDataSource.h"
#import "CLZoomPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextViewDelegate.h"

@class CAGradientLayer, CLZoomPickerView, NSIndexPath, NSMutableArray, NSString, UIButton, UIColor, UIImage, UIImageView, UILabel, UITableView, UITextField, UIWindow;

@interface ykbcAlertView : UIView <UITableViewDataSource, UITableViewDelegate, CLZoomPickerViewDelegate, CLZoomPickerViewDataSource, UITextViewDelegate>
{
    UIWindow *currWindow;
    UIView *alertView;
    UIView *line1View;
    UIView *line2View;
    UIView *line3View;
    UIView *line4View;
    UILabel *titleLabel;
    NSString *alertTitle;
    UILabel *contentLabel;
    NSString *alertContentText;
    UITextField *inputField;
    UIView *upView;
    CAGradientLayer *gradientLayer;
    UIButton *alertSubBotton;
    UILabel *subLabel;
    NSString *alertSubBottonText;
    UIImageView *subImageView;
    UIButton *alertCancelBotton;
    UILabel *cancelLabel;
    NSString *alertCancelText;
    CDUnknownBlockType buttonAtIndexBlock;
    UIColor *titleLabelTextColor;
    UIColor *contentLabelTextColor;
    UIColor *alertViewBackgroundColor;
    UIColor *subBottonTitleColor;
    UIColor *subBottonBackgroundColor;
    UIColor *subBottonBorderColor;
    UIColor *cancelButtonTitleColor;
    UIColor *cancelButtonBackgroundColor;
    UIColor *cancelButtonBorderColor;
    UIImage *alertViewMidImage;
    UIImageView *midImageView;
    UITableView *tableview1;
    NSIndexPath *indexPathNeedsSelect1;
    UITableView *tableview2;
    NSIndexPath *indexPathNeedsSelect2;
    long long height;
    UIImageView *_backImageView;
    CLZoomPickerView *_leftPickerView;
    CLZoomPickerView *_rightPickerView;
    NSMutableArray *_leftDataSource;
    NSMutableArray *_rightDataSource;
    NSString *_loanmoney;
    NSString *_loanday;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *loanday; // @synthesize loanday=_loanday;
@property(copy, nonatomic) NSString *loanmoney; // @synthesize loanmoney=_loanmoney;
@property(retain, nonatomic) NSMutableArray *rightDataSource; // @synthesize rightDataSource=_rightDataSource;
@property(retain, nonatomic) NSMutableArray *leftDataSource; // @synthesize leftDataSource=_leftDataSource;
@property(retain, nonatomic) CLZoomPickerView *rightPickerView; // @synthesize rightPickerView=_rightPickerView;
@property(retain, nonatomic) CLZoomPickerView *leftPickerView; // @synthesize leftPickerView=_leftPickerView;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
- (void).cxx_destruct;
- (void)setCancelButtonBorderColor:(id)arg1;
- (void)setCancelButtonBackgroundColor:(id)arg1;
- (void)setCancelButtonTitleColor:(id)arg1;
- (void)setSubBottonBorderColor:(id)arg1;
- (void)setSubBottonBackgroundColor:(id)arg1;
- (void)setSubBottonTitleColor:(id)arg1;
- (void)setAlertViewMidImage:(id)arg1;
- (void)setAlertViewBackgroundColor:(id)arg1;
- (void)setContentLabelTextColor:(id)arg1;
- (void)setTitleLabelTextColor:(id)arg1;
- (void)itemClickCancelBotton:(id)arg1;
- (void)itemClickSubView:(id)arg1;
- (void)modifyNick;
- (void)hideAlertView;
- (void)loadDataView;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addTableView1;
- (void)dealloc;
- (void)deviceOrientationChanged:(id)arg1;
- (void)showAlertView:(id)arg1 message:(id)arg2 height:(long long)arg3 subBottonTitle:(id)arg4 cancelButtonTitle:(id)arg5 handler:(CDUnknownBlockType)arg6;
- (void)gestureTapEvent:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)customView;
- (void)requestOnLoad;
- (void)loadPickerData;
- (void)initRightPickerView;
- (void)initLeftPickerView;
- (id)pickerView:(id)arg1 titleForRow:(unsigned long long)arg2;
- (long long)pickerView:(id)arg1;
- (void)pickerView:(id)arg1 changedIndex:(unsigned long long)arg2;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

