//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIButton, YKCacheAccelerationTrialMaskView;

@protocol YKCacheAccelerationTrialMaskViewDelegate <NSObject>
- (void)maskView:(YKCacheAccelerationTrialMaskView *)arg1 didSelectClose:(UIButton *)arg2;
@end

