//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComponentCardsController.h"

@interface YKChannelListCardsController : ComponentCardsController
{
    id <YKChannelListCardsControllerDelegate> _delegate;
}

@property(nonatomic) id <YKChannelListCardsControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)realRequestCardFailure;
- (void)realRequestCardSuccess;
- (void)receiveUserLoginStateChangedNotification:(id)arg1;
- (void)requestCardsSuccess:(id)arg1;
- (void)requestCardsWillStart;
- (void)loadContent;
- (void)loadData;
- (void)viewDidLoad;
- (void)loadView;
- (id)init;

@end

