//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ComponentCardsController.h"

#import "UITableViewDelegate.h"

@class EmbedPlayer, NSString;

@interface YKChannelSubectCardsController : ComponentCardsController <UITableViewDelegate>
{
    EmbedPlayer *_embedPlayer;
    id <YKChannelSubectCardsControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <YKChannelSubectCardsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) EmbedPlayer *embedPlayer; // @synthesize embedPlayer=_embedPlayer;
- (void).cxx_destruct;
- (void)cardsController:(id)arg1 didEndDisplayingCell:(id)arg2 forCardContentAtIndex:(long long)arg3;
- (void)requestCardsSuccess:(id)arg1;
- (void)loadView;
- (void)deinitEmbedPlayerIfNeeded;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

