//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAGradientLayer, CardVideo, CardVideoViewConfiguration, UIButton, UIImageView, UILabel;

@interface YKCSliderCardVideoView : UIView
{
    id <YKCSliderCardVideoViewDelegate> _delegate;
    CardVideo *_cardVideo;
    CardVideoViewConfiguration *_configuration;
    UIImageView *_defaultImageView;
    UIView *_videoContentView;
    UIImageView *_videoImageView;
    UIImageView *_gradientImageView;
    double _imageParallax;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    UIButton *_oMarkView;
    CAGradientLayer *_lunboGradientLayer;
}

+ (void)initialize;
@property(retain, nonatomic) CAGradientLayer *lunboGradientLayer; // @synthesize lunboGradientLayer=_lunboGradientLayer;
@property(retain, nonatomic) UIButton *oMarkView; // @synthesize oMarkView=_oMarkView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) double imageParallax; // @synthesize imageParallax=_imageParallax;
@property(retain, nonatomic) UIImageView *gradientImageView; // @synthesize gradientImageView=_gradientImageView;
@property(retain, nonatomic) UIImageView *videoImageView; // @synthesize videoImageView=_videoImageView;
@property(retain, nonatomic) UIView *videoContentView; // @synthesize videoContentView=_videoContentView;
@property(retain, nonatomic) UIImageView *defaultImageView; // @synthesize defaultImageView=_defaultImageView;
@property(retain, nonatomic) CardVideoViewConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) CardVideo *cardVideo; // @synthesize cardVideo=_cardVideo;
@property(nonatomic) __weak id <YKCSliderCardVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (struct CGSize)sizeWithText:(id)arg1 font:(id)arg2 maxWidth:(double)arg3 maxLine:(long long)arg4;
- (struct CGSize)sizeWithLabel:(id)arg1 maxWidth:(double)arg2;
- (void)refreshImageParallax;
- (void)makeLunBoGradient;
- (void)setVideoImageWithPath:(id)arg1;
- (void)refreshWithCardVideo:(id)arg1;
- (void)setupWithCardVideo:(id)arg1;
- (void)tapAction;
- (void)layoutOMarkView;
- (void)resetHasPostedColor:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

