//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EmbedPlayer, NSTimer, YKFashionViewController;

@interface YKFashionPlayerManager : NSObject
{
    _Bool _enabled;
    _Bool _endHadFired;
    EmbedPlayer *_embedPlayer;
    YKFashionViewController *_superViewController;
    NSTimer *_timer;
}

+ (id)shareInstance;
@property(nonatomic) _Bool endHadFired; // @synthesize endHadFired=_endHadFired;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak YKFashionViewController *superViewController; // @synthesize superViewController=_superViewController;
@property(nonatomic) __weak EmbedPlayer *embedPlayer; // @synthesize embedPlayer=_embedPlayer;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)timerAction;
- (void)stopTimer;
- (void)startTimer;
- (id)init;

@end

