//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor, UIImageView, UILabel, YKFRichTextLabel;

@interface YKFAnswerGroup : NSObject
{
    UIColor *_backgroundColor;
    UIImageView *_answerTagImageView;
    YKFRichTextLabel *_replyLabel;
    UILabel *_replyAgreedCountLabel;
}

@property(retain, nonatomic) UILabel *replyAgreedCountLabel; // @synthesize replyAgreedCountLabel=_replyAgreedCountLabel;
@property(retain, nonatomic) YKFRichTextLabel *replyLabel; // @synthesize replyLabel=_replyLabel;
@property(retain, nonatomic) UIImageView *answerTagImageView; // @synthesize answerTagImageView=_answerTagImageView;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;

@end

