//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSString;

@interface YKFAppjietuGetEditInfoRO : YKFAPIModel
{
    long long _shareSource;
    NSString *_showId;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *showId; // @synthesize showId=_showId;
@property(nonatomic) long long shareSource; // @synthesize shareSource=_shareSource;
- (void).cxx_destruct;

@end

