//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray, NSArray<YKFCommunityLevelPrivilegeItemPO>, YKFCommunityExpLevelItemPO;

@interface YKFCommunityLevelAndPrivilegeListItemPO : YKFAPIModel
{
    YKFCommunityExpLevelItemPO *_expLevelItemVO;
    NSArray<YKFCommunityLevelPrivilegeItemPO> *_levelPrivilegeItemVOList;
    NSArray *_newLevelAward;
    NSArray<YKFCommunityLevelPrivilegeItemPO> *_nextNewlevelPrivilegeItemVOList;
}

@property(retain, nonatomic) NSArray<YKFCommunityLevelPrivilegeItemPO> *nextNewlevelPrivilegeItemVOList; // @synthesize nextNewlevelPrivilegeItemVOList=_nextNewlevelPrivilegeItemVOList;
@property(retain, nonatomic, getter=getNewLevelAward) NSArray *newLevelAward; // @synthesize newLevelAward=_newLevelAward;
@property(retain, nonatomic) NSArray<YKFCommunityLevelPrivilegeItemPO> *levelPrivilegeItemVOList; // @synthesize levelPrivilegeItemVOList=_levelPrivilegeItemVOList;
@property(retain, nonatomic) YKFCommunityExpLevelItemPO *expLevelItemVO; // @synthesize expLevelItemVO=_expLevelItemVO;
- (void).cxx_destruct;

@end

