//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSString;

@interface YKFCommunityPostListTabPO : YKFAPIModel
{
    _Bool _displayVideo;
    long long _actionType;
    long long _tabId;
    NSString *_tabName;
}

@property(retain, nonatomic) NSString *tabName; // @synthesize tabName=_tabName;
@property(nonatomic) long long tabId; // @synthesize tabId=_tabId;
@property(nonatomic) _Bool displayVideo; // @synthesize displayVideo=_displayVideo;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;

@end

