//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray<YKFCommunityCardItemFandomInfo>, NSArray<YKFCommunityCardItemReplyPO>, NSString, YKFCommunityCardItemContentPO, YKFCommunityCardItemInteractionPO, YKFCommunityCardItemPublisherPO, YKFCommunityPostCursorPO, YKFCommunityYoukuVideoPO;

@interface YKFCommunityCardItemPO : YKFAPIModel
{
    YKFCommunityCardItemContentPO *_content;
    YKFCommunityPostCursorPO *_cursor;
    NSString *_extJson;
    NSArray<YKFCommunityCardItemFandomInfo> *_fandomInfos;
    YKFCommunityCardItemInteractionPO *_interactionVO;
    YKFCommunityCardItemPublisherPO *_publisherVO;
    NSArray<YKFCommunityCardItemReplyPO> *_replyVO;
    YKFCommunityYoukuVideoPO *_videoVO;
}

+ (id)textActionBlockCellVM;
@property(retain, nonatomic) YKFCommunityYoukuVideoPO *videoVO; // @synthesize videoVO=_videoVO;
@property(retain, nonatomic) NSArray<YKFCommunityCardItemReplyPO> *replyVO; // @synthesize replyVO=_replyVO;
@property(retain, nonatomic) YKFCommunityCardItemPublisherPO *publisherVO; // @synthesize publisherVO=_publisherVO;
@property(retain, nonatomic) YKFCommunityCardItemInteractionPO *interactionVO; // @synthesize interactionVO=_interactionVO;
@property(retain, nonatomic) NSArray<YKFCommunityCardItemFandomInfo> *fandomInfos; // @synthesize fandomInfos=_fandomInfos;
@property(retain, nonatomic) NSString *extJson; // @synthesize extJson=_extJson;
@property(retain, nonatomic) YKFCommunityPostCursorPO *cursor; // @synthesize cursor=_cursor;
@property(retain, nonatomic) YKFCommunityCardItemContentPO *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (void)makeUpTitleAndContentWithBlockVM:(id)arg1;
- (id)topicArrayFactory;
- (_Bool)isOwner;
- (id)weexBlockVMAdapter;
- (id)qaBlockVMAdapter;
- (id)voteActionBlockVMAdapterWithTip:(id)arg1;
- (id)votePreviewBlockVMAdapterWithTip:(id)arg1;
- (id)voteItemVMAdapterWithModel:(id)arg1 atIndex:(int)arg2;
- (id)replyBlockVMAdapter;
- (id)imageBlockVMAdapter;
- (id)postContentBlockVMAdapter;
- (id)outlineBlockVMAdapterWithImage:(id)arg1;
- (id)headerBlockVMAdapter;
- (id)weexBlocksCellVMAdapter;
- (id)faqBlocksCellVMAdapter;
- (id)votePreviewBlocksCellVMAdapter;
- (id)voteBlocksCellVMAdapter;
- (id)diagramTextBlocksCellVMAdapterWithShowSimpleStyle:(_Bool)arg1;
- (id)plainTextBlocksCellVMAdapterWithShowSimpleStyle:(_Bool)arg1;
- (void)configureLogicWithCellVM:(id)arg1;
- (id)simpleBlockCellVM;
- (id)blockCellVM;
- (long long)cellType;

@end

