//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFCommunityCardItemPO.h"

@class NSString;

@interface YKFCommunitySearchCardItemPO : YKFCommunityCardItemPO
{
    NSString *_extend;
}

@property(retain, nonatomic) NSString *extend; // @synthesize extend=_extend;
- (void).cxx_destruct;

@end

