//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray<YKFCommunityPlayerInfoPO>, NSString;

@interface YKFCommunityTeamInfoPO : YKFAPIModel
{
    NSString *_coach;
    long long _fandomId;
    NSString *_groupName;
    long long _obj_id;
    NSArray<YKFCommunityPlayerInfoPO> *_playerInfoVOS;
    NSString *_teamEnName;
    NSString *_teamName;
}

@property(retain, nonatomic) NSString *teamName; // @synthesize teamName=_teamName;
@property(retain, nonatomic) NSString *teamEnName; // @synthesize teamEnName=_teamEnName;
@property(retain, nonatomic) NSArray<YKFCommunityPlayerInfoPO> *playerInfoVOS; // @synthesize playerInfoVOS=_playerInfoVOS;
@property(nonatomic) long long obj_id; // @synthesize obj_id=_obj_id;
@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(nonatomic) long long fandomId; // @synthesize fandomId=_fandomId;
@property(retain, nonatomic) NSString *coach; // @synthesize coach=_coach;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

