//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFCommunityUserBasicPO.h"

@interface YKFCommunityUserChartPO : YKFCommunityUserBasicPO
{
    long long _praiseCount;
}

@property(nonatomic) long long praiseCount; // @synthesize praiseCount=_praiseCount;

@end

