//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class YKFCommunitySearchFandomListResPO, YKFCommunitySearchPostCardListPO, YKFCommunitySearchTopicListResPO;

@interface YKFCommunitySearchAggregationPO : YKFAPIModel
{
    YKFCommunitySearchFandomListResPO *_fandom;
    YKFCommunitySearchPostCardListPO *_postCardListVO;
    YKFCommunitySearchTopicListResPO *_topics;
}

@property(retain, nonatomic) YKFCommunitySearchTopicListResPO *topics; // @synthesize topics=_topics;
@property(retain, nonatomic) YKFCommunitySearchPostCardListPO *postCardListVO; // @synthesize postCardListVO=_postCardListVO;
@property(retain, nonatomic) YKFCommunitySearchFandomListResPO *fandom; // @synthesize fandom=_fandom;
- (void).cxx_destruct;

@end

