//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@interface YKFCommunityApplyDetailRO : YKFAPIModel
{
    long long _applyID;
    long long _communityId;
}

@property(nonatomic) long long communityId; // @synthesize communityId=_communityId;
@property(nonatomic) long long applyID; // @synthesize applyID=_applyID;

@end

