//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSString;

@interface YKFCommunityRealNameInfoPO : YKFAPIModel
{
    _Bool _certified;
    NSString *_message;
    NSString *_targetUrl;
}

@property(retain, nonatomic) NSString *targetUrl; // @synthesize targetUrl=_targetUrl;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) _Bool certified; // @synthesize certified=_certified;
- (void).cxx_destruct;

@end

