//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray<YKFCommunityStarChallengeMaterial>, NSString, YKFCommunityPostPO, YKFCommunityStarChallengeStyle;

@interface YKFCommunityStarChallengeDetailPO : YKFAPIModel
{
    _Bool _isFollowFandom;
    NSString *_artistHeadUrl;
    long long _artistId;
    NSString *_artistName;
    NSString *_coverUrl;
    long long _fandomId;
    NSString *_fandomSchemaUrl;
    long long _obj_id;
    NSString *_name;
    long long _postCount;
    NSString *_remark;
    NSArray<YKFCommunityStarChallengeMaterial> *_starChallengeMaterials;
    long long _starChallengePlayMode;
    YKFCommunityStarChallengeStyle *_starChallengeStyle;
    YKFCommunityPostPO *_starPostVO;
}

@property(retain, nonatomic) YKFCommunityPostPO *starPostVO; // @synthesize starPostVO=_starPostVO;
@property(retain, nonatomic) YKFCommunityStarChallengeStyle *starChallengeStyle; // @synthesize starChallengeStyle=_starChallengeStyle;
@property(nonatomic) long long starChallengePlayMode; // @synthesize starChallengePlayMode=_starChallengePlayMode;
@property(retain, nonatomic) NSArray<YKFCommunityStarChallengeMaterial> *starChallengeMaterials; // @synthesize starChallengeMaterials=_starChallengeMaterials;
@property(retain, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) long long postCount; // @synthesize postCount=_postCount;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) _Bool isFollowFandom; // @synthesize isFollowFandom=_isFollowFandom;
@property(nonatomic) long long obj_id; // @synthesize obj_id=_obj_id;
@property(retain, nonatomic) NSString *fandomSchemaUrl; // @synthesize fandomSchemaUrl=_fandomSchemaUrl;
@property(nonatomic) long long fandomId; // @synthesize fandomId=_fandomId;
@property(retain, nonatomic) NSString *coverUrl; // @synthesize coverUrl=_coverUrl;
@property(retain, nonatomic) NSString *artistName; // @synthesize artistName=_artistName;
@property(nonatomic) long long artistId; // @synthesize artistId=_artistId;
@property(retain, nonatomic) NSString *artistHeadUrl; // @synthesize artistHeadUrl=_artistHeadUrl;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

@end

