//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFPlainTextBlocksCell.h"

@class YKFDiagramTextBlocksCellVM, YKFFeedCardImagesBlock;

@interface YKFDiagramTextBlocksCell : YKFPlainTextBlocksCell
{
    YKFFeedCardImagesBlock *_imageBlock;
}

+ (id)defaultIdentifier;
@property(retain, nonatomic) YKFFeedCardImagesBlock *imageBlock; // @synthesize imageBlock=_imageBlock;
- (void).cxx_destruct;
- (void)handleImageViewClickAction;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, nonatomic) YKFDiagramTextBlocksCellVM *blocksCellVM; // @dynamic blocksCellVM;

@end

