//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFeedVideoCover.h"

@class UILabel, UIVisualEffectView, YKFeedCardBanner;

@interface YKFeedLiveCover : YKFeedVideoCover
{
    int _status;
    UILabel *_tip;
    UIVisualEffectView *_blurEffect;
    YKFeedCardBanner *_banner;
    double _startTime;
}

@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) YKFeedCardBanner *banner; // @synthesize banner=_banner;
@property(retain, nonatomic) UIVisualEffectView *blurEffect; // @synthesize blurEffect=_blurEffect;
@property(retain, nonatomic) UILabel *tip; // @synthesize tip=_tip;
@property(nonatomic) int status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)configCoverViewWithCoverUrl:(id)arg1 startTime:(double)arg2 status:(int)arg3;
- (void)relayout;
- (void)fillUI;
- (void)defaultConfig;

@end

