//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol YKFEmojisKBViewLayoutDelegate
- (long long)ykf_numberOfPages;
- (struct CGSize)ykf_sizeForCell;
- (long long)ykf_numberOfColumnsForPerPage;
- (long long)ykf_numberOfRowsForPerPage;
@end

