//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "YKFeedViewProtocol.h"

@class NSString, YKFeedModel;

@interface YKFeedChannelHeaderView : UIView <YKFeedViewProtocol>
{
    id <YKFeedViewDelegate> _delegate;
    YKFeedModel *_model;
}

+ (double)heightForWidth:(double)arg1 model:(id)arg2;
@property(retain, nonatomic) YKFeedModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <YKFeedViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

