//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "YKSTFeedStartPlayingViewDelegate.h"
#import "YKSTFeedViewProtocol.h"

@class CAGradientLayer, NSLayoutManager, NSString, NSTextContainer, NSTextStorage, UIImageView, UILabel, YKSTFeedModel, YKSTFeedStartPlayingView;

@interface YKFeedFocusPointBodyView : UIView <YKSTFeedStartPlayingViewDelegate, YKSTFeedViewProtocol>
{
    id <YKSTFeedViewDelegate> _delegate;
    YKSTFeedModel *_model;
    UIImageView *_videoImageView;
    YKSTFeedStartPlayingView *_startPlayingView;
    UILabel *_titleLabel;
    UILabel *_hotTagLabel;
    UILabel *_playCountLabel;
    CAGradientLayer *_topShadow;
    double _selfWidthCache;
    double _titleFirstLineHeadIndent;
    NSTextStorage *_textStorage;
    NSLayoutManager *_layoutManager;
    NSTextContainer *_textContainer;
    UILabel *_timeLabel;
    CAGradientLayer *_bottomShadow;
    struct CGSize _titleSizeCache;
}

+ (double)heightForWidth:(double)arg1 model:(id)arg2;
@property(retain, nonatomic) CAGradientLayer *bottomShadow; // @synthesize bottomShadow=_bottomShadow;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) NSTextContainer *textContainer; // @synthesize textContainer=_textContainer;
@property(retain, nonatomic) NSLayoutManager *layoutManager; // @synthesize layoutManager=_layoutManager;
@property(retain, nonatomic) NSTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(nonatomic) double titleFirstLineHeadIndent; // @synthesize titleFirstLineHeadIndent=_titleFirstLineHeadIndent;
@property(nonatomic) struct CGSize titleSizeCache; // @synthesize titleSizeCache=_titleSizeCache;
@property(nonatomic) double selfWidthCache; // @synthesize selfWidthCache=_selfWidthCache;
@property(retain, nonatomic) CAGradientLayer *topShadow; // @synthesize topShadow=_topShadow;
@property(retain, nonatomic) UILabel *playCountLabel; // @synthesize playCountLabel=_playCountLabel;
@property(retain, nonatomic) UILabel *hotTagLabel; // @synthesize hotTagLabel=_hotTagLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) YKSTFeedStartPlayingView *startPlayingView; // @synthesize startPlayingView=_startPlayingView;
@property(retain, nonatomic) UIImageView *videoImageView; // @synthesize videoImageView=_videoImageView;
@property(retain, nonatomic) YKSTFeedModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <YKSTFeedViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGRect)characterRectAtIndex:(unsigned long long)arg1;
- (void)configTextFrameCalculatorWithLabel:(id)arg1;
- (void)setupTextFrameCalculator;
- (void)toDarkfeedView:(id)arg1;
- (void)startPlayingViewDidClickPlay:(id)arg1;
- (void)relayoutSubviewsWithModel:(id)arg1;
- (void)tapCover;
- (void)fillRightBottomLabelWithModel:(id)arg1;
- (void)fillVideoFrontWithModel:(id)arg1;
- (void)fillLeftTopLabelWithModel:(id)arg1;
- (void)fillTitleLabelWithModel:(id)arg1;
- (id)p_hotTagFontWithModel:(id)arg1;
- (id)p_titleFontWithModel:(id)arg1;
- (id)p_fontWithSize:(double)arg1;
- (void)fillSubviewsModel:(id)arg1;
- (id)needExposeExtendsWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

