//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFeedCardBody.h"

#import "YKFeedStartPlayingViewDelegate.h"

@class NSAttributedString, NSString, UILabel, YKFeedMCModel, YKFeedStandardVideoCover, YKFeedStartPlayingView;

@interface YKFeedCardMCBody : YKFeedCardBody <YKFeedStartPlayingViewDelegate>
{
    NSAttributedString *_subtitle;
    YKFeedMCModel *_modelMC;
    UILabel *_subtitleLabel;
    YKFeedStartPlayingView *_startPlayingView;
    YKFeedStandardVideoCover *_cover;
}

+ (double)heightForModel:(id)arg1;
@property(retain, nonatomic) YKFeedStandardVideoCover *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) YKFeedStartPlayingView *startPlayingView; // @synthesize startPlayingView=_startPlayingView;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) __weak YKFeedMCModel *modelMC; // @synthesize modelMC=_modelMC;
@property(copy, nonatomic) NSAttributedString *subtitle; // @synthesize subtitle=_subtitle;
- (void).cxx_destruct;
- (void)startPlayingViewDidClickPlay:(id)arg1;
- (void)configPlayCardWithDescText:(id)arg1 subtitle:(id)arg2 coverUrl:(id)arg3 videoSizeText:(id)arg4 watchCount:(long long)arg5 duration:(long long)arg6;
- (void)configWithModel:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)relayout;
- (void)fillUI;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

