//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFPlanetLinearLayoutBlocksCellVM.h"

@class YKFFeedCardQABlockVM;

@interface YKFFaqBlocksCellVM : YKFPlanetLinearLayoutBlocksCellVM
{
    YKFFeedCardQABlockVM *_qaBlockVM;
}

@property(retain, nonatomic) YKFFeedCardQABlockVM *qaBlockVM; // @synthesize qaBlockVM=_qaBlockVM;
- (void).cxx_destruct;
- (Class)cellClass;
- (void)custumBlockVms;

@end

