//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFFanplayPageQuery.h"

@class NSString;

@interface YKFFanplayListFanWorkRO : YKFFanplayPageQuery
{
    long long _orderType;
    NSString *_playIds;
}

@property(retain, nonatomic) NSString *playIds; // @synthesize playIds=_playIds;
@property(nonatomic) long long orderType; // @synthesize orderType=_orderType;
- (void).cxx_destruct;

@end

