//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YKFAPIRequestProtocol.h"

@class NSString, YKJSONClient;

@interface YKFMTOPRequest : NSObject <YKFAPIRequestProtocol>
{
    YKJSONClient *_jsonClient;
    id _mtopRequest;
}

@property(retain, nonatomic) id mtopRequest; // @synthesize mtopRequest=_mtopRequest;
@property(retain, nonatomic) YKJSONClient *jsonClient; // @synthesize jsonClient=_jsonClient;
- (void).cxx_destruct;
- (void)cancel;
- (void)request:(id)arg1 method:(id)arg2 header:(id)arg3 parameters:(id)arg4 cachePolicy:(unsigned long long)arg5 callback:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

