//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WVDynamicHandler.h"

@interface YKFreeFlowJSBridge : WVDynamicHandler
{
}

- (id)transferCarrierType:(id)arg1;
- (void)nativeToH5:(id)arg1 withWVBridgeContext:(id)arg2;
- (void)unicomActivate:(id)arg1 withWVBridgeContext:(id)arg2;
- (void)unicomSubscribe:(id)arg1 withWVBridgeContext:(id)arg2;
- (void)deviceInfo:(id)arg1 withWVBridgeContext:(id)arg2;

@end

