//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXComponent.h"

#import "UIGestureRecognizerDelegate.h"
#import "YYTextViewDelegate.h"

@class NSAttributedString, NSString, UIColor, YYLabel;

@interface YKFRichTextComponent : WXComponent <YYTextViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _tapLinkDisable;
    _Bool _enabledLinkEvent;
    YYLabel *_label;
    NSAttributedString *_attributedText;
    NSAttributedString *_displayString;
    unsigned long long _numberOfLines;
    long long _displayCount;
    long long _fontSize;
    UIColor *_color;
}

@property(nonatomic) _Bool enabledLinkEvent; // @synthesize enabledLinkEvent=_enabledLinkEvent;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) long long fontSize; // @synthesize fontSize=_fontSize;
@property(nonatomic) _Bool tapLinkDisable; // @synthesize tapLinkDisable=_tapLinkDisable;
@property(nonatomic) long long displayCount; // @synthesize displayCount=_displayCount;
@property(nonatomic) unsigned long long numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(retain, nonatomic) NSAttributedString *displayString; // @synthesize displayString=_displayString;
@property(retain, nonatomic) NSAttributedString *attributedText; // @synthesize attributedText=_attributedText;
@property(retain, nonatomic) YYLabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (struct CGPoint)_convertPointToLayout:(struct CGPoint)arg1;
- (id)_getHighlightAtPoint:(struct CGPoint)arg1 range:(struct _NSRange *)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)replaceImageTagWithLinkTag:(id)arg1;
- (id)cgs_imageByRenderingViewForRetina:(id)arg1;
- (id)tagLabelCellWithColor:(id)arg1 withText:(id)arg2;
- (id)mutableParagraphStyleWithFont:(id)arg1 lineHeight:(double)arg2;
- (id)attributedStringWithTag:(id)arg1 tagColor:(id)arg2 tagOffsetY:(double)arg3 text:(id)arg4 textFont:(id)arg5 textColor:(id)arg6 lineHeight:(double)arg7;
- (id)getImgAttributes:(id)arg1;
- (long long)getHeight:(id)arg1;
- (long long)getWidth:(id)arg1;
- (id)getSrc:(id)arg1;
- (id)get:(id)arg1 tag:(id)arg2;
- (void)handleLink:(id)arg1 range:(struct _NSRange)arg2 attribute:(id)arg3;
- (void)handleAttachment:(id)arg1 range:(struct _NSRange)arg2 attribute:(id)arg3 imgSizeDict:(id)arg4;
- (id)transformAttributeString:(id)arg1 imgSizeDict:(id)arg2;
- (_Bool)textView:(id)arg1 shouldTapHighlight:(id)arg2 inRange:(struct _NSRange)arg3;
- (void)textView:(id)arg1 didTapHighlight:(id)arg2 inRange:(struct _NSRange)arg3 rect:(struct CGRect)arg4;
- (_Bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange)arg3;
- (void)updateText:(id)arg1;
- (struct CGSize)calceSize:(struct CGSize)arg1;
- (CDUnknownBlockType)measureBlock;
- (id)loadView;
- (void)updateStyles:(id)arg1;
- (void)internalUpdateStyle:(id)arg1;
- (void)internalUpdateAttributes:(id)arg1 fontSize:(id)arg2;
- (void)updateAttributes:(id)arg1;
- (id)initWithRef:(id)arg1 type:(id)arg2 styles:(id)arg3 attributes:(id)arg4 events:(id)arg5 weexInstance:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

