//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YKFCommonReplyToolBarProviderProtocol.h"

@class YKFReplyToolBar<YKFCommonReplyToolBarProtocol>, YKFReplyToolBarViewModel<YKFCommonReplyToolBarViewModelProtocol>;

@interface YKFReplyToolBarProvider : NSObject <YKFCommonReplyToolBarProviderProtocol>
{
    YKFReplyToolBar<YKFCommonReplyToolBarProtocol> *_bar;
    YKFReplyToolBarViewModel<YKFCommonReplyToolBarViewModelProtocol> *_barViewModel;
}

@property(retain, nonatomic) YKFReplyToolBarViewModel<YKFCommonReplyToolBarViewModelProtocol> *barViewModel; // @synthesize barViewModel=_barViewModel;
@property(retain, nonatomic) YKFReplyToolBar<YKFCommonReplyToolBarProtocol> *bar; // @synthesize bar=_bar;
- (void).cxx_destruct;

@end

