//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKFReplyKitEngine : NSObject
{
}

+ (void)registerDefaults;
+ (void)registerPlugin:(id)arg1 withClass:(Class)arg2 styleClazz:(Class)arg3;
+ (void)registerPlugin:(id)arg1 withClass:(Class)arg2;
+ (void)_registerDefaultPlugins;
+ (void)_loadALLRegisteredInPlistPlugins;
+ (void)_loadPluginsForDic:(id)arg1;

@end

