//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString, RACSignal;

@protocol YKFReplyToolAPIServiceProtocol

@optional
- (RACSignal *)sendReplySignalWithText:(NSString *)arg1 subText:(NSString *)arg2 textContentAsisstant:(id <YKFReplyToolTextContentAssistant>)arg3 nonTextContextProvider:(id <YKFReplyToolNonTextContentProvider>)arg4;
- (RACSignal *)sendReplySignalWithText:(NSString *)arg1 subText:(NSString *)arg2 textContentAsisstants:(NSArray *)arg3 nonTextContextProvider:(id <YKFReplyToolNonTextContentProvider>)arg4;
@end

