//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextFieldDelegate.h"
#import "YYTextViewDelegate.h"

@class NSString, UIView<YKFReplyTextViewProtocol>, YKFReplyContentTextViewModel, YKFReplyTextField, YKFReplyTextView;

@interface YKFReplyContentTextDefaultBaseCell : UITableViewCell <YYTextViewDelegate, UITextFieldDelegate>
{
    id <YKFReplyToolViewControllerProtocol> _parentViewController;
    YKFReplyTextView *_inputView;
    YKFReplyTextField *_subInputView;
    UIView<YKFReplyTextViewProtocol> *_currentInputView;
    YKFReplyContentTextViewModel *_viewModel;
}

@property(retain, nonatomic) YKFReplyContentTextViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) UIView<YKFReplyTextViewProtocol> *currentInputView; // @synthesize currentInputView=_currentInputView;
@property(retain, nonatomic) YKFReplyTextField *subInputView; // @synthesize subInputView=_subInputView;
@property(retain, nonatomic) YKFReplyTextView *inputView; // @synthesize inputView=_inputView;
@property(nonatomic) __weak id <YKFReplyToolViewControllerProtocol> parentViewController; // @synthesize parentViewController=_parentViewController;
- (void).cxx_destruct;
- (void)textFieldDidChange:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)parentViewWillChangeHeightWithPanelViewHeight:(double)arg1 nonTextContentViewHeight:(double)arg2 keyboardHeight:(double)arg3;
- (void)resetInputTextView;
- (void)bindViewModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

