//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSString, YKFSaintseiyaReportExtendDTO;

@interface YKFSaintseiyaCornerSignDTO : YKFAPIModel
{
    NSString *_img;
    NSString *_jumpUrl;
    long long _placeId;
    YKFSaintseiyaReportExtendDTO *_reportExtend;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) YKFSaintseiyaReportExtendDTO *reportExtend; // @synthesize reportExtend=_reportExtend;
@property(nonatomic) long long placeId; // @synthesize placeId=_placeId;
@property(retain, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(retain, nonatomic) NSString *img; // @synthesize img=_img;
- (void).cxx_destruct;

@end

