//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView, YKFStarReplyViewModel;

@protocol YKFStarReplyTableViewCellDelegate <NSObject>
- (void)starRefreshTouchedWithLabel:(UIView *)arg1;
- (void)didClickPhotoWithImageUrl:(NSString *)arg1 withViewModel:(YKFStarReplyViewModel *)arg2;
@end

