//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray<YKFSaintseiyaActivityItemDTO>, NSString, YKFSaintseiyaBattleTopicDTO;

@interface YKFSaintseiyaRankListDTO : YKFAPIModel
{
    NSArray<YKFSaintseiyaActivityItemDTO> *_itemDTOList;
    NSString *_shareUrl;
    YKFSaintseiyaBattleTopicDTO *_topBattle;
    NSString *_unit;
}

@property(retain, nonatomic) NSString *unit; // @synthesize unit=_unit;
@property(retain, nonatomic) YKFSaintseiyaBattleTopicDTO *topBattle; // @synthesize topBattle=_topBattle;
@property(retain, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) NSArray<YKFSaintseiyaActivityItemDTO> *itemDTOList; // @synthesize itemDTOList=_itemDTOList;
- (void).cxx_destruct;

@end

