//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSArray<YKFStararrivalPostMixedContentPO>, NSString;

@interface YKFStararrivalAssentContentPO : YKFAPIModel
{
    NSString *_action;
    NSString *_artistName;
    NSArray<YKFStararrivalPostMixedContentPO> *_contents;
    long long _gmtOperate;
    NSString *_userName;
}

@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) long long gmtOperate; // @synthesize gmtOperate=_gmtOperate;
@property(retain, nonatomic) NSArray<YKFStararrivalPostMixedContentPO> *contents; // @synthesize contents=_contents;
@property(retain, nonatomic) NSString *artistName; // @synthesize artistName=_artistName;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
- (void).cxx_destruct;

@end

