//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFSaintseiyaBasePageDataDTO.h"

@interface YKFSaintseiyaShotInfoPageDTO : YKFSaintseiyaBasePageDataDTO
{
    long long _isWhite;
    long long _shotTime;
}

@property(nonatomic) long long shotTime; // @synthesize shotTime=_shotTime;
@property(nonatomic) long long isWhite; // @synthesize isWhite=_isWhite;

@end

