//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKFAPIModel.h"

@class NSString, YKFSaintseiyaAudioParamDTO;

@interface YKFSaintseiyaPublishParamDTO : YKFAPIModel
{
    long long _activityItemId;
    YKFSaintseiyaAudioParamDTO *_audio;
    NSString *_cameraParam;
    long long _materialId;
    long long _musicId;
    long long _playType;
    long long _topicId;
    NSString *_videoId;
}

@property(retain, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(nonatomic) long long topicId; // @synthesize topicId=_topicId;
@property(nonatomic) long long playType; // @synthesize playType=_playType;
@property(nonatomic) long long musicId; // @synthesize musicId=_musicId;
@property(nonatomic) long long materialId; // @synthesize materialId=_materialId;
@property(retain, nonatomic) NSString *cameraParam; // @synthesize cameraParam=_cameraParam;
@property(retain, nonatomic) YKFSaintseiyaAudioParamDTO *audio; // @synthesize audio=_audio;
@property(nonatomic) long long activityItemId; // @synthesize activityItemId=_activityItemId;
- (void).cxx_destruct;

@end

