//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface YKFSynchronizeSerial : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
}

+ (void)execAsynBlock:(CDUnknownBlockType)arg1;
+ (void)execSyncBlock:(CDUnknownBlockType)arg1;
+ (id)synchronizeQueue;
- (void).cxx_destruct;
- (void)execAsynBlock:(CDUnknownBlockType)arg1;
- (void)execSyncBlock:(CDUnknownBlockType)arg1;
- (id)init;
- (void)dealloc;

@end

