//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface YKFTodayTasksListCell : UITableViewCell
{
    UIImageView *_taskIconImageView;
    UILabel *_taskTitleLabel;
    UILabel *_taskRewardsLabel;
    UILabel *_taskCompleteStatusLabel;
}

@property(retain, nonatomic) UILabel *taskCompleteStatusLabel; // @synthesize taskCompleteStatusLabel=_taskCompleteStatusLabel;
@property(retain, nonatomic) UILabel *taskRewardsLabel; // @synthesize taskRewardsLabel=_taskRewardsLabel;
@property(retain, nonatomic) UILabel *taskTitleLabel; // @synthesize taskTitleLabel=_taskTitleLabel;
@property(retain, nonatomic) UIImageView *taskIconImageView; // @synthesize taskIconImageView=_taskIconImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)updateCellWithItemVM:(id)arg1;

@end

