//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKFTimeUtil : NSObject
{
}

+ (id)timeCalendar;
+ (id)messageTimeWithDate:(id)arg1;
+ (id)chatListTimeWithDate:(id)arg1;
+ (id)zeroOfDate;
+ (id)chatTimeWithDate:(id)arg1;
+ (id)timeAccurateToWeek:(id)arg1;
+ (id)timeAccurateToSecond:(id)arg1;
+ (id)timeAccurateToMinites:(id)arg1;
+ (id)timeAccurateToDay:(id)arg1;

@end

