//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString, YKFTabViewController;

@protocol YKFTabViewBarPluginDataSource <NSObject>

@optional
- (NSAttributedString *)tabViewController:(YKFTabViewController *)arg1 selectedTitleForIndex:(long long)arg2;
- (NSAttributedString *)tabViewController:(YKFTabViewController *)arg1 normalTitleForIndex:(long long)arg2;
- (NSString *)tabViewController:(YKFTabViewController *)arg1 badgeForIndex:(long long)arg2;
- (NSString *)tabViewController:(YKFTabViewController *)arg1 titleForIndex:(long long)arg2;
@end

