//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, YKHLFollowGuideModel;

@interface YKHLFollowGuideViewCell : UITableViewCell
{
    YKHLFollowGuideModel *_model;
    UIImageView *_leftImageView;
    UIButton *_rightBtn;
    UILabel *_titleLable;
    UILabel *_detailLable;
    UILabel *_followLable;
}

@property(retain, nonatomic) UILabel *followLable; // @synthesize followLable=_followLable;
@property(retain, nonatomic) UILabel *detailLable; // @synthesize detailLable=_detailLable;
@property(retain, nonatomic) UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIImageView *leftImageView; // @synthesize leftImageView=_leftImageView;
@property(retain, nonatomic) YKHLFollowGuideModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)updateTightBtnState:(_Bool)arg1;
- (void)clickFollowBtn;
- (void)setUpUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

