//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, UIView;

@interface YKImmersedAnimationTransition : NSObject <UIViewControllerAnimatedTransitioning>
{
    _Bool _present;
    double _duration;
    UIView *_transitionView;
    struct CGRect _startFrame;
    struct CGRect _finalFrame;
}

@property(retain, nonatomic) UIView *transitionView; // @synthesize transitionView=_transitionView;
@property(nonatomic) struct CGRect finalFrame; // @synthesize finalFrame=_finalFrame;
@property(nonatomic) struct CGRect startFrame; // @synthesize startFrame=_startFrame;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic, getter=isPresent) _Bool present; // @synthesize present=_present;
- (void).cxx_destruct;
- (void)dismissWithTranstion:(id)arg1;
- (void)presentWithTransiton:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)registerWithDuration:(double)arg1 startFrame:(struct CGRect)arg2 finalFrame:(struct CGRect)arg3 transitionView:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

