//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKImmersedCard.h"

@class NSArray, NSMutableArray, UIButton, UIFont, UIView<YKImmersedRecmdProtocol>, YKFeedCardButton;

@interface YKImmersedCardBottom : YKImmersedCard
{
    long long _watchCount;
    long long _likeCount;
    long long _commentCount;
    UIFont *_tagFont;
    NSMutableArray *_tagBtnsQueue;
    NSArray *_tagModels;
    UIView<YKImmersedRecmdProtocol> *_recommendBar;
    YKFeedCardButton *_likeBtn;
    YKFeedCardButton *_commentBtn;
    UIButton *_moreBtn;
    struct CGSize _imgSize;
}

+ (double)heightForModel:(id)arg1;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) YKFeedCardButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) YKFeedCardButton *likeBtn; // @synthesize likeBtn=_likeBtn;
@property(retain, nonatomic) UIView<YKImmersedRecmdProtocol> *recommendBar; // @synthesize recommendBar=_recommendBar;
@property(retain, nonatomic) NSArray *tagModels; // @synthesize tagModels=_tagModels;
@property(retain, nonatomic) NSMutableArray *tagBtnsQueue; // @synthesize tagBtnsQueue=_tagBtnsQueue;
@property(retain, nonatomic) UIFont *tagFont; // @synthesize tagFont=_tagFont;
@property(nonatomic) struct CGSize imgSize; // @synthesize imgSize=_imgSize;
@property(nonatomic) long long commentCount; // @synthesize commentCount=_commentCount;
@property(nonatomic) long long likeCount; // @synthesize likeCount=_likeCount;
@property(nonatomic) long long watchCount; // @synthesize watchCount=_watchCount;
- (void).cxx_destruct;
- (CDUnknownBlockType)barTapBlock;
- (id)recommendBar2;
- (id)recommendBar1;
- (void)overflowBtnClicked:(id)arg1;
- (void)tagBtnClicked:(id)arg1;
- (void)commentBtnClicked:(id)arg1;
- (void)likeBtnClicked:(id)arg1;
- (id)buildTagBtn;
- (id)tagBtnWithTag:(long long)arg1;
- (_Bool)verifyBtnOverflowWithTitleSize:(struct CGSize)arg1 start:(double)arg2 tagMaxX:(double)arg3;
- (void)updateTagBtnsWithTagModels:(id)arg1 start:(double)arg2 tagMaxX:(double)arg3;
- (id)needExposeExtendsWithModel:(id)arg1;
- (void)configFooterViewWithLikeCount:(long long)arg1 commentCount:(long long)arg2 liked:(_Bool)arg3;
- (void)configWithModel:(id)arg1;
- (void)likeStateChanged:(id)arg1;
- (void)addNotifications;
- (id)dequeueTagBtn;
- (void)relayoutButtonWithFixedTop:(double)arg1;
- (void)relayout;
- (void)fillUI;
- (void)defaultConfig;

@end

