//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKLCTColorUtils : NSObject
{
}

+ (id)colorwithHexString:(id)arg1;
+ (id)colorWithRGB:(id)arg1 alpha:(id)arg2;

@end

