//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKLCTRInfo.h"

@class NSURL, UIFont, UIImage;

@interface YKLCTRImageInfo : YKLCTRInfo
{
    UIFont *_font;
    NSURL *_src;
    UIImage *_image;
    UIImage *_placeholder;
    NSURL *_cornerSrc;
    double _descent;
    double _ascent;
    struct CGSize _size;
    struct CGSize _cornerSize;
    struct CGPoint _position;
}

+ (id)imageWithImage:(id)arg1;
+ (id)imageWithSrc:(id)arg1 size:(struct CGSize)arg2;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(nonatomic) double ascent; // @synthesize ascent=_ascent;
@property(nonatomic) double descent; // @synthesize descent=_descent;
@property(nonatomic) struct CGSize cornerSize; // @synthesize cornerSize=_cornerSize;
@property(retain, nonatomic) NSURL *cornerSrc; // @synthesize cornerSrc=_cornerSrc;
@property(retain, nonatomic) UIImage *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) NSURL *src; // @synthesize src=_src;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
- (void).cxx_destruct;
- (id)init;

@end

