//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString, UIColor;

@interface YKLDanmakuInfoModel : NSObject
{
    _Bool _immediately;
    NSString *_text;
    NSAttributedString *_content;
    UIColor *_backgroundColor;
    double _fontSize;
    UIColor *_fontColor;
    UIColor *_fontColorTop;
    UIColor *_fontColorBottom;
    double _borderCornerSize;
    double _borderSize;
    UIColor *_borderColor;
    double _shadowSize;
    UIColor *_shadowColor;
    unsigned long long _row;
    long long _zindex;
    double _contentWidth;
    double _duration;
    double _time;
    double _paddingTop;
    double _paddingBottom;
    double _paddingLeft;
    double _paddingRight;
    double _margin;
    double _fontBorderSize;
    UIColor *_fontBorderColor;
    double _startTime;
    double _speed;
    struct CGSize _shadowOffset;
}

+ (id)stringByPaddingTheLeftToLength:(id)arg1 newLength:(unsigned long long)arg2 withString:(id)arg3 startingAtIndex:(unsigned long long)arg4;
@property(nonatomic) double speed; // @synthesize speed=_speed;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) UIColor *fontBorderColor; // @synthesize fontBorderColor=_fontBorderColor;
@property(nonatomic) double fontBorderSize; // @synthesize fontBorderSize=_fontBorderSize;
@property(nonatomic) double margin; // @synthesize margin=_margin;
@property(nonatomic) double paddingRight; // @synthesize paddingRight=_paddingRight;
@property(nonatomic) double paddingLeft; // @synthesize paddingLeft=_paddingLeft;
@property(nonatomic) double paddingBottom; // @synthesize paddingBottom=_paddingBottom;
@property(nonatomic) double paddingTop; // @synthesize paddingTop=_paddingTop;
@property(nonatomic) double time; // @synthesize time=_time;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double contentWidth; // @synthesize contentWidth=_contentWidth;
@property(nonatomic) long long zindex; // @synthesize zindex=_zindex;
@property(nonatomic) unsigned long long row; // @synthesize row=_row;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset=_shadowOffset;
@property(copy, nonatomic) UIColor *shadowColor; // @synthesize shadowColor=_shadowColor;
@property(nonatomic) double shadowSize; // @synthesize shadowSize=_shadowSize;
@property(copy, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderSize; // @synthesize borderSize=_borderSize;
@property(nonatomic) double borderCornerSize; // @synthesize borderCornerSize=_borderCornerSize;
@property(copy, nonatomic) UIColor *fontColorBottom; // @synthesize fontColorBottom=_fontColorBottom;
@property(copy, nonatomic) UIColor *fontColorTop; // @synthesize fontColorTop=_fontColorTop;
@property(copy, nonatomic) UIColor *fontColor; // @synthesize fontColor=_fontColor;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) NSAttributedString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) _Bool immediately; // @synthesize immediately=_immediately;
- (void).cxx_destruct;
- (id)parseWithDict:(id)arg1;
- (id)parseColorWithCss:(id)arg1;
- (id)init;

@end

