//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UIView;

@interface YKLInputOritationViewController : UIViewController
{
    UIView *_originView;
}

@property(nonatomic) __weak UIView *originView; // @synthesize originView=_originView;
- (void).cxx_destruct;
- (void)openWithOrientation:(long long)arg1;
- (void)changeOrientation:(long long)arg1;
- (void)deviceOrientationChanged:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

@end

