//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKLiveBarragePacket.h"

@interface YKLiveBarrageSettingsPacket : YKLiveBarragePacket
{
    long long _channelId;
    unsigned long long _heartbeatTimeInterval;
}

+ (void)load;
@property(nonatomic) unsigned long long heartbeatTimeInterval; // @synthesize heartbeatTimeInterval=_heartbeatTimeInterval;
@property(nonatomic) long long channelId; // @synthesize channelId=_channelId;
- (void)mergeFromJSON:(id)arg1;

@end

