//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol YKLPlayerTouchDelegate <NSObject>
- (void)touchesMoveWithPoint:(struct CGPoint)arg1;
- (void)touchesEndWithPoint:(struct CGPoint)arg1;
- (void)touchesBeganWithPoint:(struct CGPoint)arg1;
@end

