//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString, NSURL, UIColor, YYTextLayout;

@interface YKLYKChatMessage : NSObject
{
    YYTextLayout *_nickLayout;
    YYTextLayout *_contentLayout;
    NSAttributedString *_nickString;
    NSAttributedString *_contentString;
    NSURL *_avatar;
    NSURL *_avatarIcon;
    UIColor *_backgroundColor;
    double _cellHeight;
    long long _chatType;
    NSString *_cellType;
}

@property(copy, nonatomic) NSString *cellType; // @synthesize cellType=_cellType;
@property(nonatomic) long long chatType; // @synthesize chatType=_chatType;
@property(nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) NSURL *avatarIcon; // @synthesize avatarIcon=_avatarIcon;
@property(copy, nonatomic) NSURL *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSAttributedString *contentString; // @synthesize contentString=_contentString;
@property(copy, nonatomic) NSAttributedString *nickString; // @synthesize nickString=_nickString;
@property(retain, nonatomic) YYTextLayout *contentLayout; // @synthesize contentLayout=_contentLayout;
@property(retain, nonatomic) YYTextLayout *nickLayout; // @synthesize nickLayout=_nickLayout;
- (void).cxx_destruct;

@end

