//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKMapHost : NSObject
{
    _Bool _isEnable;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool isEnable; // @synthesize isEnable=_isEnable;
- (_Bool)isInWhitelist:(id)arg1;
- (id)mapHost:(id)arg1;

@end

