//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKPBaseCard.h"

@class UIImageView;

@interface YKPActivityImageCard : YKPBaseCard
{
    UIImageView *_maskImgView;
    UIImageView *_activityImgView;
}

+ (float)heightWithContext:(id)arg1;
@property(retain, nonatomic) UIImageView *activityImgView; // @synthesize activityImgView=_activityImgView;
@property(retain, nonatomic) UIImageView *maskImgView; // @synthesize maskImgView=_maskImgView;
- (void).cxx_destruct;
- (void)setupWithContext:(id)arg1;
- (void)layoutSubviews;
- (void)initialize;

@end

