//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SKPaymentTransactionObserver.h"
#import "SKProductsRequestDelegate.h"

@class NSString;

@interface YKPaymentCenter : NSObject <SKProductsRequestDelegate, SKPaymentTransactionObserver>
{
    _Bool _transactionObserverFlag;
    _Bool _canMakePayments;
    _Bool _receiveAppleResponse;
    NSString *_originalTransaction;
    id <YKPaymentDelegate> _delegate;
    NSString *_productID;
    NSString *_orderID;
    NSString *_hashUsername;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *hashUsername; // @synthesize hashUsername=_hashUsername;
@property(copy, nonatomic) NSString *orderID; // @synthesize orderID=_orderID;
@property(copy, nonatomic) NSString *productID; // @synthesize productID=_productID;
@property(nonatomic) _Bool receiveAppleResponse; // @synthesize receiveAppleResponse=_receiveAppleResponse;
@property(nonatomic) _Bool canMakePayments; // @synthesize canMakePayments=_canMakePayments;
@property(nonatomic) __weak id <YKPaymentDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool transactionObserverFlag; // @synthesize transactionObserverFlag=_transactionObserverFlag;
@property(readonly, copy, nonatomic) NSString *originalTransaction; // @synthesize originalTransaction=_originalTransaction;
- (void).cxx_destruct;
- (void)newPaymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (_Bool)paymentQueue:(id)arg1 shouldAddStorePayment:(id)arg2 forProduct:(id)arg3;
- (void)paymentQueue:(id)arg1 updatedTransactions:(id)arg2;
- (void)request:(id)arg1 didFailWithError:(id)arg2;
- (void)productsRequest:(id)arg1 didReceiveResponse:(id)arg2;
- (void)completePayment:(id)arg1;
- (void)applePaymentSuccess:(id)arg1;
- (void)applePaymentRestore;
- (void)applePaymentFailed:(id)arg1;
- (void)applePaymentStart;
- (void)resetStatus;
- (void)requestYKProduct:(id)arg1 orderID:(id)arg2 hashUsername:(id)arg3 listener:(id)arg4;
- (void)requestYKProduct:(id)arg1 orderID:(id)arg2 listener:(id)arg3;
- (void)requestYKProduct:(id)arg1 listener:(id)arg2;
- (void)addTransactionObserver;
- (id)init;
- (void)launch;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

