//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface YKPersonalCenterHistoryManager : NSObject
{
    NSArray *_dataSourceForRecords;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSArray *dataSourceForRecords; // @synthesize dataSourceForRecords=_dataSourceForRecords;
- (void).cxx_destruct;
- (unsigned long long)countOfRecords;
- (id)recordOfIndex:(unsigned long long)arg1;
- (void)fetchUserRecordsWithJSONClient:(id)arg1 needReload:(CDUnknownBlockType)arg2;

@end

