//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKPLDCacheSession : NSObject
{
    _Bool _isStart;
    float _costTime;
    unsigned long long _cacheCount;
    unsigned long long _cacheFailCount;
    long long _stopReason;
    double _start;
    double _end;
}

@property(nonatomic) double end; // @synthesize end=_end;
@property(nonatomic) double start; // @synthesize start=_start;
@property(nonatomic) _Bool isStart; // @synthesize isStart=_isStart;
@property(nonatomic) long long stopReason; // @synthesize stopReason=_stopReason;
@property(nonatomic) unsigned long long cacheFailCount; // @synthesize cacheFailCount=_cacheFailCount;
@property(nonatomic) float costTime; // @synthesize costTime=_costTime;
@property(nonatomic) unsigned long long cacheCount; // @synthesize cacheCount=_cacheCount;
- (void)refreshSession;
- (void)endSession;
- (void)startSession;

@end

