//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKPBaseService.h"

@class YKFFanplayFanWorkServiceGetFanWorkByIdAPI;

@interface YKPPlayerService : YKPBaseService
{
    YKFFanplayFanWorkServiceGetFanWorkByIdAPI *_getFanWorkByIdAPI;
}

@property(retain, nonatomic) YKFFanplayFanWorkServiceGetFanWorkByIdAPI *getFanWorkByIdAPI; // @synthesize getFanWorkByIdAPI=_getFanWorkByIdAPI;
- (void).cxx_destruct;
- (void)getFanWorkById:(long long)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)cancelAllRequest;

@end

