//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSString, UIImage;

@interface YKRecentReadChannel : NSObject <NSCoding>
{
    _Bool _isMoreItem;
    NSString *_uid;
    NSString *_encodeUid;
    NSString *_userName;
    NSString *_icon;
    NSString *_userUrl;
    NSString *_unread;
    NSString *_flag;
    UIImage *_moreIcon;
}

@property(nonatomic) _Bool isMoreItem; // @synthesize isMoreItem=_isMoreItem;
@property(retain, nonatomic) UIImage *moreIcon; // @synthesize moreIcon=_moreIcon;
@property(retain, nonatomic) NSString *flag; // @synthesize flag=_flag;
@property(retain, nonatomic) NSString *unread; // @synthesize unread=_unread;
@property(retain, nonatomic) NSString *userUrl; // @synthesize userUrl=_userUrl;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *encodeUid; // @synthesize encodeUid=_encodeUid;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)consumed;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDic:(id)arg1;

@end

