//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "YKSCommentEditViewDelegate.h"

@class NSString, UIScrollView, UITableView, UIVisualEffectView, YKSCommentEditView, YKSCommentNavBarView, YKSLoadingView;

@interface YKSCommentBaseViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, YKSCommentEditViewDelegate>
{
    _Bool _tableScrolled;
    _Bool _deceleratingBackToZero;
    double _decelerationDistanceRatio;
    _Bool _isGestureAnimation;
    _Bool _enabledScoll;
    UITableView *_tableView;
    YKSCommentNavBarView *_navBarView;
    YKSCommentEditView *_editView;
    UIVisualEffectView *_effectView;
    YKSLoadingView *_loadingView;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) YKSLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIVisualEffectView *effectView; // @synthesize effectView=_effectView;
@property(retain, nonatomic) YKSCommentEditView *editView; // @synthesize editView=_editView;
@property(retain, nonatomic) YKSCommentNavBarView *navBarView; // @synthesize navBarView=_navBarView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool enabledScoll; // @synthesize enabledScoll=_enabledScoll;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (id)vid;
- (void)didSendMsg:(id)arg1;
- (void)didClickSendBtn;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)didDismiss:(id)arg1;
- (void)gestureBack;
- (float)maxScrollHeight;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollingEnded;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)addComment:(id)arg1;
- (void)backActionWithTap;
- (void)backAction;
- (void)requestMore;
- (void)requestData;
- (void)reloadData;
- (void)didRequestDataFailure:(id)arg1;
- (void)didRequestDataSuccess;
- (void)stopLoading;
- (void)startLoading;
- (void)tapGestureAction:(id)arg1;
- (void)addTapGesture;
- (void)addTableFooter;
- (void)addTableHeader;
- (void)setupView;
- (void)keyboardWillBeHiden:(id)arg1;
- (void)keyboardWasShown:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

