//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UILabel, UISwitch;

@interface YKShortVideoSettingView : UIView
{
    id <YKShortVideoSettingViewDelegate> _delegate;
    UILabel *_titleLabel;
    UILabel *_subTitle;
    UISwitch *_switchButton;
    UIButton *_closeButton;
}

+ (void)initialize;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UISwitch *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <YKShortVideoSettingViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onSwitchBtnClick:(id)arg1;
- (void)onCloseBtnClick;
- (id)init;
- (void)analytics_onSwitchBtnClick:(id)arg1;

@end

