//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel, YKSRUFeedModel;

@interface YKSRUCardDescView : UIView
{
    UILabel *_titleLable;
    UILabel *_playcountLable;
    UIImageView *_nameIcon;
    UILabel *_nameLable;
    UIImageView *_bofangIcon;
    YKSRUFeedModel *_cardModel;
}

@property(retain, nonatomic) YKSRUFeedModel *cardModel; // @synthesize cardModel=_cardModel;
- (void).cxx_destruct;
- (void)removeNameIcon;
- (void)addNameIcon;
- (void)removeNameLabel;
- (void)addNameLable;
- (void)setData:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

