//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class YKSShareInfoItem;

@interface YKSShareCenter : NSObject
{
    id <YKSShareCenterDelegate> _delegate;
    id <YKSShareContentReformer> _contentReformer;
    YKSShareInfoItem *_currentShareInfo;
}

+ (_Bool)handleOpenURL:(id)arg1 application:(id)arg2;
+ (_Bool)checkUrlAndApplication:(id)arg1 application:(id)arg2;
+ (id)defaultCenter;
@property(retain, nonatomic) YKSShareInfoItem *currentShareInfo; // @synthesize currentShareInfo=_currentShareInfo;
@property(nonatomic) __weak id <YKSShareContentReformer> contentReformer; // @synthesize contentReformer=_contentReformer;
@property(nonatomic) __weak id <YKSShareCenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)toJsonString:(id)arg1;
- (void)debugToastInfoInvalid;
- (_Bool)internalSendToPlatform:(int)arg1;
- (_Bool)sendContent:(id)arg1 toPlatform:(int)arg2 delegate:(id)arg3;
- (id)init;
- (void)dealloc;

@end

