//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface YKSShareModel : NSObject
{
    _Bool _isShowQR;
    _Bool _isYouKuApp;
    int _sourceId;
    NSString *_contentId;
    NSString *_url;
    NSString *_thumbnailUrl;
    NSString *_titleText;
    NSString *_descText;
    NSDictionary *_shareInfo;
    NSString *_qrCodeViewType;
    NSString *_posterBgImageUrl;
    NSString *_userHeadImageUrl;
    unsigned long long _userSex;
    NSString *_userAge;
    NSString *_userConstellation;
    NSString *_userNickName;
    NSString *_userAPPId;
    NSMutableDictionary *_extensionAnaalytics;
    NSString *_pageName_Analytics;
    NSString *_ab_SPM_Analytics;
}

@property(nonatomic) _Bool isYouKuApp; // @synthesize isYouKuApp=_isYouKuApp;
@property(copy, nonatomic) NSString *ab_SPM_Analytics; // @synthesize ab_SPM_Analytics=_ab_SPM_Analytics;
@property(copy, nonatomic) NSString *pageName_Analytics; // @synthesize pageName_Analytics=_pageName_Analytics;
@property(retain, nonatomic) NSMutableDictionary *extensionAnaalytics; // @synthesize extensionAnaalytics=_extensionAnaalytics;
@property(copy, nonatomic) NSString *userAPPId; // @synthesize userAPPId=_userAPPId;
@property(copy, nonatomic) NSString *userNickName; // @synthesize userNickName=_userNickName;
@property(copy, nonatomic) NSString *userConstellation; // @synthesize userConstellation=_userConstellation;
@property(copy, nonatomic) NSString *userAge; // @synthesize userAge=_userAge;
@property(nonatomic) unsigned long long userSex; // @synthesize userSex=_userSex;
@property(copy, nonatomic) NSString *userHeadImageUrl; // @synthesize userHeadImageUrl=_userHeadImageUrl;
@property(copy, nonatomic) NSString *posterBgImageUrl; // @synthesize posterBgImageUrl=_posterBgImageUrl;
@property(copy, nonatomic) NSString *qrCodeViewType; // @synthesize qrCodeViewType=_qrCodeViewType;
@property(nonatomic) _Bool isShowQR; // @synthesize isShowQR=_isShowQR;
@property(copy, nonatomic) NSDictionary *shareInfo; // @synthesize shareInfo=_shareInfo;
@property(copy, nonatomic) NSString *descText; // @synthesize descText=_descText;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(copy, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
@property(nonatomic) int sourceId; // @synthesize sourceId=_sourceId;
- (void).cxx_destruct;

@end

