//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, YKSTFeedHeaderModel;

@interface YKSTFeedBaseHeaderView : UIView
{
    YKSTFeedHeaderModel *_model;
    UIImageView *_bgImgView;
    UIView *_topWhiteCoverView;
    UIView *_centerCoverView;
    UIView *_topCoverView;
    UIView *_topWhiteCoverLine;
}

@property(retain, nonatomic) UIView *topWhiteCoverLine; // @synthesize topWhiteCoverLine=_topWhiteCoverLine;
@property(retain, nonatomic) UIView *topCoverView; // @synthesize topCoverView=_topCoverView;
@property(retain, nonatomic) UIView *centerCoverView; // @synthesize centerCoverView=_centerCoverView;
@property(retain, nonatomic) UIView *topWhiteCoverView; // @synthesize topWhiteCoverView=_topWhiteCoverView;
@property(retain, nonatomic) UIImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
@property(retain, nonatomic) YKSTFeedHeaderModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (double)bgImgHeight;
- (void)setBGImgViewFrame:(struct CGRect)arg1;
- (void)layoutUIComponents;
- (void)setupSubviews;
- (id)initWithHeadModel:(id)arg1;

@end

