//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, YKSTFeedModel;

@interface YKSTFeedAdPlayEndView : UIView
{
    id <YKSTFeedAdPlayEndViewDelegate> _delegate;
    YKSTFeedModel *_model;
    UIImageView *_bgImageView;
    UIView *_coverView;
    UIButton *_replayBtn;
}

@property(retain, nonatomic) UIButton *replayBtn; // @synthesize replayBtn=_replayBtn;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) YKSTFeedModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <YKSTFeedAdPlayEndViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)replayAction:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

