//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ComponentCardsController, YKSTFeedModel, YKSTFeedsFetchNextFeedScenario, YKSTFeedsManager, YKSTFeedsPlayCustomFeedScenario, YKSTFeedsPlayNextFeedScenario;

@protocol YKSTFeedsManagerDelegate <NSObject>
- (YKSTFeedsPlayCustomFeedScenario *)feedsMgr:(YKSTFeedsManager *)arg1 playFeedScenarioAtIndex:(unsigned long long)arg2;
- (YKSTFeedModel *)feedsMgr:(YKSTFeedsManager *)arg1 playFeedForIndex:(unsigned long long)arg2;
- (void)feedsMgr:(YKSTFeedsManager *)arg1 didStopPlayFeed:(YKSTFeedModel *)arg2;
- (void)feedsMgr:(YKSTFeedsManager *)arg1 didStartPlayFeed:(YKSTFeedModel *)arg2;
- (void)feedsMgr:(YKSTFeedsManager *)arg1 notifyRemoveFeed:(YKSTFeedModel *)arg2;
- (YKSTFeedsFetchNextFeedScenario *)feedsMgr:(YKSTFeedsManager *)arg1 fetchNextFeedScenarioWithSrcFeed:(YKSTFeedModel *)arg2;
- (YKSTFeedsPlayNextFeedScenario *)feedsMgr:(YKSTFeedsManager *)arg1 playNextFeedScenarioWithFeed:(YKSTFeedModel *)arg2;
- (YKSTFeedModel *)feedsMgr:(YKSTFeedsManager *)arg1 playNextFeedForSrcFeed:(YKSTFeedModel *)arg2;
- (ComponentCardsController *)componentCardsController;

@optional
- (int)shareSourceIdWithfeedsMgr:(YKSTFeedsManager *)arg1;
@end

