//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMSAction, NSString;

@interface YKSTPlayLaterModel : NSObject
{
    NSString *_img;
    NSString *_showId;
    NSString *_subTitle;
    NSString *_title;
    CMSAction *_action;
}

@property(retain, nonatomic) CMSAction *action; // @synthesize action=_action;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *showId; // @synthesize showId=_showId;
@property(retain, nonatomic) NSString *img; // @synthesize img=_img;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

