//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKSVPhotosUtility : NSObject
{
}

+ (void)saveImageDataToAlbum:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (void)guideToSetting:(id)arg1;
+ (void)verifyAlbumAuthorizationWithCompletionHandler:(CDUnknownBlockType)arg1 onVC:(id)arg2;

@end

