//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton;

@interface YKSVImageTextSeeMoreVideoFooterCell : UITableViewCell
{
    id <YKSVImageTextSeeMoreVideoFooterCellDelegate> _delegate;
    UIButton *_seeMoreButton;
}

@property(retain, nonatomic) UIButton *seeMoreButton; // @synthesize seeMoreButton=_seeMoreButton;
@property(nonatomic) __weak id <YKSVImageTextSeeMoreVideoFooterCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSeeMoreBtnClicked;
- (id)init;

@end

