//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface YKSVideoDescCache : NSObject
{
    NSMutableDictionary *_videoDesCache;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableDictionary *videoDesCache; // @synthesize videoDesCache=_videoDesCache;
- (void).cxx_destruct;
- (id)getVideoDescCacheForVideoId:(id)arg1;
- (void)saveVideoDescCache:(id)arg1 forVideoId:(id)arg2;

@end

