//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YKUDConfigManager : NSObject
{
    _Bool _allowsCellularDownload;
    _Bool _isLogin;
    _Bool _onSpeedUpMode;
    _Bool _useBgMusic;
    long long _memberType;
    long long _downloadVideoCount;
    long long _retryCountForVideo;
    long long _retryCountForDownloadRequest;
    long long _retryCountFor40X;
    long long _retryCountForUPS;
    long long _retryCountForRequestInner;
    long long _upsRetryDelay;
    NSString *_defaultUA;
}

+ (id)sharedInstance;
@property(retain) NSString *defaultUA; // @synthesize defaultUA=_defaultUA;
@property long long upsRetryDelay; // @synthesize upsRetryDelay=_upsRetryDelay;
@property long long retryCountForRequestInner; // @synthesize retryCountForRequestInner=_retryCountForRequestInner;
@property long long retryCountForUPS; // @synthesize retryCountForUPS=_retryCountForUPS;
@property long long retryCountFor40X; // @synthesize retryCountFor40X=_retryCountFor40X;
@property long long retryCountForDownloadRequest; // @synthesize retryCountForDownloadRequest=_retryCountForDownloadRequest;
@property long long retryCountForVideo; // @synthesize retryCountForVideo=_retryCountForVideo;
@property(nonatomic) _Bool useBgMusic; // @synthesize useBgMusic=_useBgMusic;
- (void).cxx_destruct;
@property(readonly) _Bool useResume;
- (_Bool)downloadIn3GFromLocalCheck;
- (void)refresh;
- (void)updateToDefaults;
@property(nonatomic) long long downloadVideoCount; // @synthesize downloadVideoCount=_downloadVideoCount;
@property(nonatomic) _Bool onSpeedUpMode; // @synthesize onSpeedUpMode=_onSpeedUpMode;
@property(nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
@property(nonatomic) long long memberType; // @synthesize memberType=_memberType;
@property(nonatomic) _Bool allowsCellularDownload; // @synthesize allowsCellularDownload=_allowsCellularDownload;
- (void)loadFromDefaults;
- (id)init;

@end

