//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, YKUPlayView;

@protocol YKUPlayViewDelegate <NSObject>

@optional
- (void)playView:(YKUPlayView *)arg1 playInterrupted:(NSError *)arg2;
- (void)playView:(YKUPlayView *)arg1 playError:(NSError *)arg2;
- (void)playViewDidPlayEnd:(YKUPlayView *)arg1;
- (void)playViewContinuePlay:(YKUPlayView *)arg1;
- (void)playViewNeedWaitting:(YKUPlayView *)arg1;
- (void)playView:(YKUPlayView *)arg1 playProgress:(double)arg2;
- (void)playView:(YKUPlayView *)arg1 didKnowDuration:(double)arg2;
- (void)playViewDidPausePlay:(YKUPlayView *)arg1;
- (void)playViewDidStartPlay:(YKUPlayView *)arg1;
- (_Bool)playViewShouldStartPlay:(YKUPlayView *)arg1;
@end

