//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

#import "YKUploadDelegate.h"

@class AFHTTPClient, NSMutableSet, NSString, UploadTask;

@interface YKUploadOperation : NSOperation <YKUploadDelegate>
{
    _Bool _finished_;
    _Bool _executing_;
    _Bool _isStart;
    UploadTask *_context;
    id <YKUploadDelegate> _delegate;
    AFHTTPClient *_httpclient;
    NSMutableSet *_tasks;
    Class _state;
}

@property(retain, nonatomic) Class state; // @synthesize state=_state;
@property(nonatomic) _Bool isStart; // @synthesize isStart=_isStart;
@property(nonatomic) _Bool executing_; // @synthesize executing_=_executing_;
@property(nonatomic) _Bool finished_; // @synthesize finished_=_finished_;
@property(retain, nonatomic) NSMutableSet *tasks; // @synthesize tasks=_tasks;
@property(retain, nonatomic) AFHTTPClient *httpclient; // @synthesize httpclient=_httpclient;
@property(nonatomic) id <YKUploadDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UploadTask *context; // @synthesize context=_context;
- (void)uploadDidWait:(id)arg1;
- (void)uploadDidCancel:(id)arg1;
- (void)uploadDidSuccess:(id)arg1;
- (void)uploadDidReceiveData:(id)arg1;
- (void)uploadDidStart:(id)arg1;
- (void)uploadDidError:(id)arg1;
- (void)performHTTPPostDataRequest:(id)arg1 data:(id)arg2 success:(CDUnknownBlockType)arg3;
- (void)performHTTPRequest:(id)arg1 method:(id)arg2 parameters:(id)arg3 success:(CDUnknownBlockType)arg4;
- (void)performHTTPPostRequest:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3;
- (void)performHTTPGetRequest:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)cancel;
- (void)complete:(_Bool)arg1;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (_Bool)isConcurrent;
- (void)cancelUpload;
- (void)main;
- (void)start;
- (void)dealloc;
- (void)addTasksObject:(Class)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

