//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKVIPEquityAPI : NSObject
{
}

+ (id)getDefaultEquity;
+ (void)getAllEquity:(CDUnknownBlockType)arg1;
+ (id)getEquityByEquityID:(id)arg1 bizKey:(id)arg2;
+ (void)getEquityByEquityID:(id)arg1 bizKey:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
+ (id)getEquityByEquityID:(id)arg1;
+ (void)getEquityByEquityID:(id)arg1 withBlock:(CDUnknownBlockType)arg2;

@end

