//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UILabel;

@interface YKVIPPacketCloseButton : UIButton
{
    UILabel *_numberLabel;
    UILabel *_titleLab;
}

@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
- (void).cxx_destruct;
- (void)didChangeNumberLabel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 showTime:(_Bool)arg2;

@end

