//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKVIPBaseComponent.h"

@class YKVIPHotShowingCell;

@interface YKVIPHotShowingComponent : YKVIPBaseComponent
{
    YKVIPHotShowingCell *_hsCell;
}

- (void).cxx_destruct;
- (id)exposeArrayForComponent:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)heightForRowAtIndexPath:(id)arg1;
- (long long)numberOfRowsInComponent;

@end

