//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel, YKVIPCardImageView, YKVIPShortVideoModel;

@interface YKVIPPlayerEndFollowView : UIView
{
    YKVIPShortVideoModel *_itemModel;
    id <YKVIPPlayerEndFollowViewDelegate> _delegate;
    UIImageView *_bgImageView;
    YKVIPCardImageView *_videoImgView;
    UILabel *_markLabel;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIButton *_followBtn;
    UIButton *_replayBtn;
}

@property(retain, nonatomic) UIButton *replayBtn; // @synthesize replayBtn=_replayBtn;
@property(retain, nonatomic) UIButton *followBtn; // @synthesize followBtn=_followBtn;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *markLabel; // @synthesize markLabel=_markLabel;
@property(retain, nonatomic) YKVIPCardImageView *videoImgView; // @synthesize videoImgView=_videoImgView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(nonatomic) __weak id <YKVIPPlayerEndFollowViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak YKVIPShortVideoModel *itemModel; // @synthesize itemModel=_itemModel;
- (void).cxx_destruct;
- (id)creatVideoDict;
- (void)uploadExpose:(id)arg1;
- (void)uploadStatistical:(id)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)unCollection:(id)arg1;
- (void)collection:(id)arg1;
- (void)videoAction;
- (void)collectionAction:(id)arg1;
- (void)replayAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

