//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKVIPEquityCache : NSObject
{
}

+ (id)getDefaultEquitys;
+ (id)getOrangeSetting;
+ (void)cleanAllCache;
+ (void)cleanDiskCache;
+ (void)setDiskCache:(id)arg1;
+ (id)getDiskCacheNoCheck;
+ (id)getDiskCache;
+ (void)cleanMemCache;
+ (void)setMemCache:(id)arg1;
+ (id)getMemCacheNoCheck;
+ (id)getMemCache;

@end

