//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "YKVIPBaseCellDelegate.h"
#import "YKVIPComponentProtocol.h"

@class NSIndexPath, NSString, YKVIPComponentModel, YKVIPPageService;

@interface YKVIPBaseComponent : NSObject <YKVIPComponentProtocol, YKVIPBaseCellDelegate>
{
    YKVIPComponentModel *_componentModel;
    YKVIPPageService *_pageService;
    double _cellPadding;
    NSIndexPath *_indexPath;
}

@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) double cellPadding; // @synthesize cellPadding=_cellPadding;
@property(nonatomic) __weak YKVIPPageService *pageService; // @synthesize pageService=_pageService;
@property(retain, nonatomic) YKVIPComponentModel *componentModel; // @synthesize componentModel=_componentModel;
- (void).cxx_destruct;
- (void)resetExpose;
- (void)exposeInCell:(id)arg1;
- (id)exposeArrayForComponent:(id)arg1;
- (void)tableView:(id)arg1 didDisplayComponentAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndScrollComponentAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingComponentAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayComponentAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)heightForRowAtIndexPath:(id)arg1;
- (long long)numberOfRowsInComponent;
- (id)initWithComponentModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

