//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, VIPCMSComponentContext, YKVIPCMSDolbySliderView;

@interface YKVIPCMSDolbySliderCell : UITableViewCell
{
    YKVIPCMSDolbySliderView *_sliderView;
    VIPCMSComponentContext *_componentContext;
    UIImageView *_bgImgView;
    UIImageView *_sliderImgView;
}

@property(retain, nonatomic) UIImageView *sliderImgView; // @synthesize sliderImgView=_sliderImgView;
@property(retain, nonatomic) UIImageView *bgImgView; // @synthesize bgImgView=_bgImgView;
@property(retain, nonatomic) VIPCMSComponentContext *componentContext; // @synthesize componentContext=_componentContext;
@property(retain, nonatomic) YKVIPCMSDolbySliderView *sliderView; // @synthesize sliderView=_sliderView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setupSliderViewWithDelegate:(id)arg1 componentContext:(id)arg2 frame:(struct CGRect)arg3;

@end

