//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIScrollViewDelegate.h"
#import "YKVIPTabMenuDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSString, UIScrollView, UIViewController, UIViewController<YKVIPPageDelegate>, YKVIPPageItem, YKVIPTabMenu;

@interface YKVIPPagesManager : NSObject <UIScrollViewDelegate, YKVIPTabMenuDelegate>
{
    NSMutableArray *_pagesArray;
    NSMutableArray *_usingPagesArray;
    NSMutableDictionary *_reusePagesDictionary;
    YKVIPPageItem *_selectedPageItem;
    YKVIPPageItem *_placeholderPageItem;
    _Bool _active;
    UIViewController *_containerController;
    long long _preloadDepth;
    double _topviewHeight;
    UIScrollView *_scrollView;
    YKVIPTabMenu *_menuView;
    id <YKVIPPagesManagerDelegate> _delegate;
    long long _numberOfPages;
    double _pageSpacing;
    long long _indexForSelectedPage;
    double _scrollProgress;
}

@property(readonly, nonatomic) double scrollProgress; // @synthesize scrollProgress=_scrollProgress;
@property(readonly, nonatomic) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) long long indexForSelectedPage; // @synthesize indexForSelectedPage=_indexForSelectedPage;
@property(nonatomic) double pageSpacing; // @synthesize pageSpacing=_pageSpacing;
@property(readonly, nonatomic) long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) __weak id <YKVIPPagesManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) YKVIPTabMenu *menuView; // @synthesize menuView=_menuView;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) double topviewHeight; // @synthesize topviewHeight=_topviewHeight;
@property(nonatomic) long long preloadDepth; // @synthesize preloadDepth=_preloadDepth;
@property(nonatomic) __weak UIViewController *containerController; // @synthesize containerController=_containerController;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stopAtEndWithYKVIPTabMenu:(id)arg1;
- (void)ykVIPTabMenu:(id)arg1 exposureWithItems:(id)arg2 atIndexs:(id)arg3;
- (void)ykVIPTabMenu:(id)arg1 didSelectMenuItem:(id)arg2 atIndex:(long long)arg3;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)reloadPages:(long long)arg1;
- (void)reloadPages;
- (void)removeUsingPageItem:(id)arg1;
- (id)appendUsingPageItemWithIndex:(long long)arg1;
- (id)loadReusePageItemWithIdentifier:(id)arg1;
- (void)saveReusePageItem:(id)arg1;
- (void)updateSelectedPageWithItem:(id)arg1;
- (void)updateSelectedIndexFromScrollView;
- (void)updateSelectedIndex:(long long)arg1 byMenuView:(_Bool)arg2;
- (void)updateSelectedIndex:(long long)arg1;
@property(readonly, nonatomic) __weak UIViewController<YKVIPPageDelegate> *selectedPage;
- (void)updatePage:(id)arg1 active:(_Bool)arg2 finish:(_Bool)arg3;
- (void)didDeactivateAnimated:(_Bool)arg1;
- (void)willDeactivateAnimated:(_Bool)arg1;
- (void)didActivateAnimated:(_Bool)arg1;
- (void)willActivateAnimated:(_Bool)arg1;
- (void)loadMenuItemsWithSelectedIndex:(long long)arg1;
- (void)reloadMenuItems;
- (void)setupMenuViewWithFrame:(struct CGRect)arg1;
- (void)scrollToSelectedPage;
- (void)setupScrollViewWithFrame:(struct CGRect)arg1 className:(id)arg2;
- (void)setupScrollViewWithFrame:(struct CGRect)arg1;
- (id)subControllers;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

