//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, VIPCMSAction, YKVIPMarkModel;

@interface YKVIPItemModel : NSObject
{
    _Bool _isFavourite;
    NSString *_type;
    NSString *_imgUrl;
    NSString *_gifImg;
    NSString *_title;
    NSString *_subtitle;
    NSString *_subtitleType;
    NSString *_desc;
    NSString *_summary;
    NSString *_summaryType;
    NSString *_playVV;
    VIPCMSAction *_action;
    NSString *_spm;
    YKVIPMarkModel *_markModel;
    NSDictionary *_sourceDict;
    double _summaryWidth;
}

@property(nonatomic) double summaryWidth; // @synthesize summaryWidth=_summaryWidth;
@property(retain, nonatomic) NSDictionary *sourceDict; // @synthesize sourceDict=_sourceDict;
@property(retain, nonatomic) YKVIPMarkModel *markModel; // @synthesize markModel=_markModel;
@property(retain, nonatomic) NSString *spm; // @synthesize spm=_spm;
@property(retain, nonatomic) VIPCMSAction *action; // @synthesize action=_action;
@property(nonatomic) _Bool isFavourite; // @synthesize isFavourite=_isFavourite;
@property(retain, nonatomic) NSString *playVV; // @synthesize playVV=_playVV;
@property(retain, nonatomic) NSString *summaryType; // @synthesize summaryType=_summaryType;
@property(retain, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *subtitleType; // @synthesize subtitleType=_subtitleType;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *gifImg; // @synthesize gifImg=_gifImg;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)updateTextWidth;
- (id)initItemModelWithDictionary:(id)arg1;

@end

