//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKVIPItemModel.h"

@class NSString;

@interface YKVIPAdModel : YKVIPItemModel
{
    _Bool _needDismissWhenHide;
    long long _adCountdown;
    NSString *_adId;
}

@property(retain, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(nonatomic) _Bool needDismissWhenHide; // @synthesize needDismissWhenHide=_needDismissWhenHide;
@property(nonatomic) long long adCountdown; // @synthesize adCountdown=_adCountdown;
- (void).cxx_destruct;
- (id)initItemModelWithDictionary:(id)arg1;

@end

