//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, VIPCMSAction;

@interface YKVIPInfo : NSObject
{
    long long _infoID;
    NSString *_scm;
    NSString *_title;
    NSString *_img;
    NSString *_hint;
    NSString *_spm;
    NSString *_trackInfo;
    VIPCMSAction *_action;
}

+ (id)initModelWithDict:(id)arg1;
@property(retain, nonatomic) VIPCMSAction *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *trackInfo; // @synthesize trackInfo=_trackInfo;
@property(copy, nonatomic) NSString *spm; // @synthesize spm=_spm;
@property(copy, nonatomic) NSString *hint; // @synthesize hint=_hint;
@property(copy, nonatomic) NSString *img; // @synthesize img=_img;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *scm; // @synthesize scm=_scm;
@property(nonatomic) long long infoID; // @synthesize infoID=_infoID;
- (void).cxx_destruct;

@end

