//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YKWeexURLUtils : NSObject
{
}

+ (id)encodeField:(id)arg1;
+ (_Bool)isBlank:(id)arg1;
+ (id)urlByAppendParamAndValue:(id)arg1 withParamAndValue:(id)arg2;

@end

