//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YKWXMediaNode.h"

@class NSString, UIColor;

@interface YKWXTextNode : YKWXMediaNode
{
    float _fontSize;
    NSString *_text;
    UIColor *_color;
}

@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property(nonatomic) float fontSize; // @synthesize fontSize=_fontSize;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)draw;
- (id)initWithParam:(id)arg1;

@end

