//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSString, YTEngineScreenMode;

@interface YTEngineConfigurationItem : NSObject
{
    _Bool _enableLoop;
    _Bool _enableXAd;
    _Bool _enableAdCache;
    _Bool _enableScreenContent;
    _Bool _enableWatermark;
    _Bool _enableWoVideo;
    _Bool _enableP2P;
    _Bool _enableAudioMode;
    _Bool _enableSteroAudioMode;
    _Bool _enableVPM;
    _Bool _enableSubscriptButton;
    _Bool _enableHlpUtLogModule;
    long long _sourceType;
    NSString *_vvSource;
    YTEngineScreenMode *_defaultScreenMode;
    double _animateDuration;
    long long _videoPositionTimeInterval;
    NSString *_userAgent;
    NSDictionary *_AdParam;
    id <YTEnginePlayerYoukuDataSource> _youkuDataSource;
    id <YTEnginePlayerAdDataSource> _adDataSource;
    id <YTEngineAirPlayerDelegate> _airplayerDelegate;
    id <YTEngineAudioPlayerDelegate> _audioPlayerDelegate;
    NSArray *_engineModules;
    NSString *_hlpccode;
}

@property(copy, nonatomic) NSString *hlpccode; // @synthesize hlpccode=_hlpccode;
@property(nonatomic) _Bool enableHlpUtLogModule; // @synthesize enableHlpUtLogModule=_enableHlpUtLogModule;
@property(nonatomic) _Bool enableSubscriptButton; // @synthesize enableSubscriptButton=_enableSubscriptButton;
@property(nonatomic) _Bool enableVPM; // @synthesize enableVPM=_enableVPM;
@property(nonatomic) _Bool enableSteroAudioMode; // @synthesize enableSteroAudioMode=_enableSteroAudioMode;
@property(nonatomic) _Bool enableAudioMode; // @synthesize enableAudioMode=_enableAudioMode;
@property(nonatomic) _Bool enableP2P; // @synthesize enableP2P=_enableP2P;
@property(nonatomic) _Bool enableWoVideo; // @synthesize enableWoVideo=_enableWoVideo;
@property(nonatomic) _Bool enableWatermark; // @synthesize enableWatermark=_enableWatermark;
@property(nonatomic) _Bool enableScreenContent; // @synthesize enableScreenContent=_enableScreenContent;
@property(nonatomic) _Bool enableAdCache; // @synthesize enableAdCache=_enableAdCache;
@property(nonatomic) _Bool enableXAd; // @synthesize enableXAd=_enableXAd;
@property(retain, nonatomic) NSArray *engineModules; // @synthesize engineModules=_engineModules;
@property(nonatomic) __weak id <YTEngineAudioPlayerDelegate> audioPlayerDelegate; // @synthesize audioPlayerDelegate=_audioPlayerDelegate;
@property(nonatomic) __weak id <YTEngineAirPlayerDelegate> airplayerDelegate; // @synthesize airplayerDelegate=_airplayerDelegate;
@property(nonatomic) __weak id <YTEnginePlayerAdDataSource> adDataSource; // @synthesize adDataSource=_adDataSource;
@property(nonatomic) __weak id <YTEnginePlayerYoukuDataSource> youkuDataSource; // @synthesize youkuDataSource=_youkuDataSource;
@property(nonatomic) _Bool enableLoop; // @synthesize enableLoop=_enableLoop;
@property(retain, nonatomic) NSDictionary *AdParam; // @synthesize AdParam=_AdParam;
@property(nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(nonatomic) long long videoPositionTimeInterval; // @synthesize videoPositionTimeInterval=_videoPositionTimeInterval;
@property(nonatomic) double animateDuration; // @synthesize animateDuration=_animateDuration;
@property(retain, nonatomic) YTEngineScreenMode *defaultScreenMode; // @synthesize defaultScreenMode=_defaultScreenMode;
@property(copy, nonatomic) NSString *vvSource; // @synthesize vvSource=_vvSource;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
- (void).cxx_destruct;

@end

