//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "YTEBaseModel.h"

@class NSArray, NSString;

@interface YTEUpsNodePreviewModel : YTEBaseModel
{
    NSArray *_thumb;
    NSString *_timespan;
}

@property(copy, nonatomic) NSString *timespan; // @synthesize timespan=_timespan;
@property(copy, nonatomic) NSArray *thumb; // @synthesize thumb=_thumb;

@end

