//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIButton, UIImageView, UILabel, YTInstallProgressView;

@interface YTInstallAppView : UIView
{
    id <YTInstallAppViewDelegate> _delegate;
    UIView *_containerView;
    UIImageView *_bgImageView;
    UIImageView *_iconImageView;
    UILabel *_titleLabel1;
    UILabel *_titleLabel2;
    UIButton *_installAppButton;
    YTInstallProgressView *_installProgressView;
    NSArray *_aryDeviceList;
}

@property(retain, nonatomic) NSArray *aryDeviceList; // @synthesize aryDeviceList=_aryDeviceList;
@property(retain, nonatomic) YTInstallProgressView *installProgressView; // @synthesize installProgressView=_installProgressView;
@property(retain, nonatomic) UIButton *installAppButton; // @synthesize installAppButton=_installAppButton;
@property(retain, nonatomic) UILabel *titleLabel2; // @synthesize titleLabel2=_titleLabel2;
@property(retain, nonatomic) UILabel *titleLabel1; // @synthesize titleLabel1=_titleLabel1;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <YTInstallAppViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)processAppStatus:(long long)arg1 packageName:(id)arg2 state:(long long)arg3 progress:(long long)arg4;
- (void)setInstallButtonTitle:(id)arg1;
- (void)onBtnClick:(id)arg1;
- (void)setDatas:(id)arg1;
- (void)initSubViews:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

