//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface YTPlaylinkFeedbackManager : NSObject
{
    _Bool _isUploading;
    NSString *_namePrefix;
    NSString *_infoString;
    NSString *_playErrorString;
    NSString *_playErrorCode;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *playErrorCode; // @synthesize playErrorCode=_playErrorCode;
@property(retain, nonatomic) NSString *playErrorString; // @synthesize playErrorString=_playErrorString;
@property(retain, nonatomic) NSString *infoString; // @synthesize infoString=_infoString;
@property(retain, nonatomic) NSString *namePrefix; // @synthesize namePrefix=_namePrefix;
@property(nonatomic) _Bool isUploading; // @synthesize isUploading=_isUploading;
- (void).cxx_destruct;
- (void)uploadPlaylinkInfo;
- (_Bool)playlinkOrangeSwitcher;
- (void)playlinkUpload:(id)arg1 extendInfo:(id)arg2;
- (id)init;

@end

