//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface YTWirelessOrangeBrandingUnit : NSObject
{
    NSArray *_cfgs;
    NSArray *_devs;
}

@property(retain, nonatomic) NSArray *devs; // @synthesize devs=_devs;
@property(retain, nonatomic) NSArray *cfgs; // @synthesize cfgs=_cfgs;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;

@end

