//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UILabel;

@interface YTWirelessSearchingView : UIView
{
    UIView *_containerView;
    UIActivityIndicatorView *_indicatorView;
    UILabel *_titleLabel;
}

@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)processEndSearch;
- (void)processStartSearch;
- (void)initSubViews:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

