//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ZPDImageBrowserView;

@protocol ZPDImageBrowserViewDelegate <NSObject>
- (void)imageBrowserViewDidImageSave:(ZPDImageBrowserView *)arg1;
- (void)imageBrowserViewDidPageChange;
- (void)imageBrowserViewDidDismiss:(ZPDImageBrowserView *)arg1;
- (void)imageBrowserViewDidShow:(ZPDImageBrowserView *)arg1;
@end

