//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WXModuleProtocol.h"

@class NSString, WXSDKInstance, ZPDImageBrowser;

@interface ZPDMiniAppModule : NSObject <WXModuleProtocol>
{
    WXSDKInstance *weexInstance;
    ZPDImageBrowser *_imageBrowser;
}

+ (id)wx_export_method_128;
+ (id)wx_export_method_88;
+ (id)wx_export_method_76;
+ (id)wx_export_method_66;
+ (id)wx_export_method_59;
+ (id)wx_export_method_52;
+ (id)wx_export_method_45;
+ (id)wx_export_method_38;
+ (id)wx_export_method_27;
@property(retain, nonatomic) ZPDImageBrowser *imageBrowser; // @synthesize imageBrowser=_imageBrowser;
@property(nonatomic) __weak WXSDKInstance *weexInstance; // @synthesize weexInstance;
- (void).cxx_destruct;
- (void)updateCommentTotal:(id)arg1;
- (id)getParentViewController;
- (void)showGalleryImages:(id)arg1;
- (void)notifyLikedStatus:(id)arg1;
- (void)notifyEditStatus:(id)arg1;
- (void)postFocusStateChangedEvent:(id)arg1;
- (void)focusUser:(id)arg1;
- (void)stopAnimating;
- (void)startAnimating;
- (void)close;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

